In [79]:
import pandas as pd

print(pd.__version__)

2.3.1

In [80]:
! /opt/anaconda3/bin/python -m pip list

Package                           Version
--------------------------------- -------------------
absl-py                           2.5.0
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.19.0
aiohappyeyeballs                  2.4.4
aiohttp                           3.11.10
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.16.2
altair                            5.5.0
anaconda-anon-usage               0.7.1
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.11.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.3
appscript                         1.3.0
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asgiref                           3.9.1
astroid                           3.3.8
astropy                           7.0.0
astropy-iers-data                 0.2025.1.13.0.34.51
asttokens                         3.0.0
astunparse                        1.6.3
async-lru                         2.0.4
asyncssh                          2.17.0
atomicwrites                      1.4.0
attrs                             24.3.0
Automat                           24.8.1
autopep8                          2.0.4
babel                             2.16.0
bcrypt                            4.3.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.10.0
bleach                            6.2.0
blinker                           1.9.0
bokeh                             3.6.2
boltons                           24.1.0
botocore                          1.36.3
Bottleneck                        1.4.2
Brotli                            1.0.9
cachetools                        5.5.1
certifi                           2025.7.14
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.8
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             25.5.1
conda-anaconda-telemetry          0.1.2
conda-anaconda-tos                0.2.0
conda-build                       25.5.0
conda-content-trust               0.2.0
conda_index                       0.6.1
conda-libmamba-solver             25.4.0
conda-pack                        0.7.1
conda-package-handling            2.4.0
conda_package_streaming           0.11.0
conda-repo-cli                    1.0.165
conda-token                       0.6.0
constantly                        23.10.4
contourpy                         1.3.1
cookiecutter                      1.7.3
cryptography                      44.0.1
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           1.0.1
dask                              2025.2.0
dask-expr                         2.0.0
datashader                        0.18.0
debugpy                           1.8.11
decorator                         5.1.1
defusedxml                        0.7.1
Deprecated                        1.2.13
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2025.2.0
distro                            1.9.0
Django                            5.2.6
django-cors-headers               4.9.0
djangorestframework               3.16.1
djangorestframework_simplejwt     5.5.1
dmglib                            0.9.5
docstring-to-markdown             0.11
docutils                          0.21.2
et_xmlfile                        1.1.0
evalidate                         2.0.3
executing                         0.8.3
fastjsonschema                    2.20.0
filelock                          3.17.0
flake8                            7.1.1
Flask                             3.1.0
flatbuffers                       25.12.19
fonttools                         4.55.3
frozendict                        2.4.2
frozenlist                        1.5.0
fsspec                            2025.3.2
gast                              0.7.0
gitdb                             4.0.7
GitPython                         3.1.43
gmpy2                             2.2.1
google-auth                       2.42.1
google-genai                      1.48.0
google-pasta                      0.2.0
greenlet                          3.1.1
grpcio                            1.82.1
h11                               0.16.0
h5py                              3.12.1
HeapDict                          1.0.1
hf-xet                            1.2.0
holoviews                         1.20.2
httpcore                          1.0.9
httpx                             0.28.1
hvplot                            0.11.3
hyperlink                         21.0.0
idna                              3.7
imageio                           2.37.0
imagesize                         1.4.1
imbalanced-learn                  0.13.0
importlib_metadata                8.5.0
incremental                       24.7.2
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.29.5
ipython                           8.30.0
ipywidgets                        8.1.5
isort                             6.0.1
itemadapter                       0.3.0
itemloaders                       1.3.2
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jaraco.context                    0.0.0
jaraco.functools                  4.1.0
jedi                              0.19.2
jellyfish                         1.1.3
Jinja2                            3.1.6
jinja2-time                       0.2.0
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.25
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.12.0
jupyter-lsp                       2.2.5
jupyter_server                    2.15.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.3.4
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
keras                             3.15.0
keyring                           25.6.0
kiwisolver                        1.4.8
lazy_loader                       0.4
lckr_jupyterlab_variableinspector 3.2.4
libarchive-c                      5.1
libclang                          18.1.1
libmambapy                        2.0.5
lief                              0.16.4
linkify-it-py                     2.0.0
llvmlite                          0.44.0
lmdb                              1.6.2
locket                            1.0.0
lxml                              5.3.0
lz4                               4.3.2
Mako                              1.2.3
Markdown                          3.8
markdown-it-py                    2.2.0
MarkupSafe                        3.0.2
matplotlib                        3.10.0
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.2.0
mistune                           3.1.2
ml_dtypes                         0.5.4
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.1.0
multipledispatch                  0.6.0
mypy                              1.14.1
mypy_extensions                   1.0.0
namex                             0.1.0
narwhals                          1.31.0
navigator-updater                 0.5.1
nb_conda_kernels                  2.5.2
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest_asyncio                      1.6.0
networkx                          3.4.2
nltk                              3.9.1
notebook                          7.3.2
notebook_shim                     0.2.4
numba                             0.61.0
numexpr                           2.10.1
numpy                             2.1.3
numpydoc                          1.2
opencv-python                     4.12.0.88
openpyxl                          3.1.5
opt_einsum                        3.4.0
optree                            0.19.1
overrides                         7.4.0
packaging                         24.2
pandas                            2.3.1
pandocfilters                     1.5.0
panel                             1.7.0
param                             2.2.0
parsel                            1.8.1
parso                             0.8.4
partd                             1.4.2
pathspec                          0.10.3
patsy                             1.0.1
pexpect                           4.8.0
pickleshare                       0.7.5
pillow                            11.1.0
pip                               25.1
pkce                              1.0.3
pkginfo                           1.12.0
platformdirs                      4.3.7
plotly                            5.24.1
pluggy                            1.5.0
ply                               3.11
poyo                              0.5.0
prometheus_client                 0.21.1
prompt_toolkit                    3.0.43
propcache                         0.3.1
Protego                           0.4.0
protobuf                          7.35.1
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyarrow                           19.0.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.12.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.6
pydantic                          2.10.3
pydantic_core                     2.27.1
pydantic-settings                 2.6.1
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.5
pyflakes                          3.2.0
PyGithub                          2.4.0
Pygments                          2.19.1
PyJWT                             2.10.1
pylint                            3.3.5
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyNaCl                            1.5.0
pyobjc-core                       10.1
pyobjc-framework-Cocoa            10.1
pyobjc-framework-CoreServices     10.1
pyobjc-framework-FSEvents         10.1
pyodbc                            5.2.0
pyOpenSSL                         25.0.0
pyparsing                         3.2.0
PyQt5                             5.15.10
PyQt5_sip                         12.13.0
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytest                            8.3.4
python-dateutil                   2.9.0.post0
python-dotenv                     1.1.0
python-json-logger                3.2.1
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.12.2
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytz                              2024.1
pyuca                             1.2
pyviz_comms                       3.0.2
PyWavelets                        1.8.0
PyYAML                            6.0.2
pyzmq                             26.2.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.4.0
qtconsole                         5.6.1
QtPy                              2.4.1
queuelib                          1.6.2
readchar                          4.0.5
referencing                       0.30.2
regex                             2024.11.6
requests                          2.32.3
requests-file                     2.1.0
requests-toolbelt                 1.0.0
rfc3339_validator                 0.1.4
rfc3986_validator                 0.1.1
rich                              13.9.4
roman-numerals-py                 3.1.0
rope                              1.13.0
rpds-py                           0.22.3
rsa                               4.9.1
Rtree                             1.0.1
ruamel.yaml                       0.18.10
ruamel.yaml.clib                  0.2.12
ruamel_yaml_conda                 0.17.21
s3fs                              2025.3.2
scikit-image                      0.25.0
scikit-learn                      1.6.1
scipy                             1.15.3
Scrapy                            2.12.0
seaborn                           0.13.2
semver                            3.0.2
Send2Trash                        1.8.2
sentry-sdk                        2.18.0
service-identity                  24.2.0
setuptools                        72.1.0
shellingham                       1.5.0
sip                               6.7.12
six                               1.17.0
sklearn-compat                    0.1.3
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            8.2.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
spyder                            6.0.7
spyder-kernels                    3.0.5
SQLAlchemy                        2.0.39
sqlparse                          0.5.3
stack-data                        0.2.0
statsmodels                       0.14.4
streamlit                         1.45.1
superqt                           0.7.3
sympy                             1.13.3
tables                            3.10.2
tabulate                          0.9.0
tblib                             3.1.0
tenacity                          9.0.0
tensorflow                        2.21.0
termcolor                         3.3.0
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2025.2.18
tinycss2                          1.4.0
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.13.2
toolz                             1.0.0
tornado                           6.5.1
tqdm                              4.67.1
traitlets                         5.14.3
truststore                        0.10.0
Twisted                           24.11.0
typer                             0.9.0
typer-slim                        0.20.0
typing_extensions                 4.12.2
tzdata                            2025.2
uc-micro-py                       1.0.1
ujson                             5.10.0
Unidecode                         1.3.8
urllib3                           2.3.0
w3lib                             2.1.2
watchdog                          4.0.2
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        15.0.1
Werkzeug                          3.1.3
whatthepatch                      1.0.2
wheel                             0.45.1
widgetsnbextension                4.0.13
wrapt                             1.17.0
wurlitzer                         3.0.2
xarray                            2025.4.0
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.18.0
zict                              3.0.0
zipp                              3.21.0
zope.interface                    7.1.1
zstandard                         0.23.0

1 . Creating data

In [81]:
df = pd.DataFrame({'Yes' :[50 , 10] , 'No' : [20 , 30]})
df_1 = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']} , index= ['Product A ' , 'Product B'])
print(df)
print(df_1)

   Yes  No
0   50  20
1   10  30
                      Bob           Sue
Product A     I liked it.  Pretty good.
Product B   It was awful.        Bland.

Series

In [82]:
pd.Series([1,2,3,4,5] , index=['sales 2023' ,'sales 2024' ,'sales 2025','sales 2026','sales 2027',] , name= 'prodctname')

sales 2023    1
sales 2024    2
sales 2025    3
sales 2026    4
sales 2027    5
Name: prodctname, dtype: int64

Reading data files

In [83]:
data = pd.read_csv('iris_data.csv')
print(data.head())
print(data.shape)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
(150, 6)

2. Indexing, Selecting & Assigning

In [84]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [85]:
data['SepalLengthCm'][1]

np.float64(4.9)

Indexing in pandas

In [86]:
# index-based selection
data.iloc[0]
# to get first row of data in a DataFrame

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [87]:
data.iloc[:,0]
# row-first, column-second

0        1
1        2
2        3
3        4
4        5
      ...
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64

In [88]:
data.iloc[:4,1]

0    5.1
1    4.9
2    4.7
3    4.6
Name: SepalLengthCm, dtype: float64

In [89]:
data.loc[3] # for an example we give an index of [1,9] it will consider till 1 to 8 which is iloc , so in loc it will consider 1 to 9

Id                         4
SepalLengthCm            4.6
SepalWidthCm             3.1
PetalLengthCm            1.5
PetalWidthCm             0.2
Species          Iris-setosa
Name: 3, dtype: object

Manipulating the index

In [90]:
data.set_index("Id")

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [91]:
data.Species == 'Iris-setosa'
# we've been indexing various strides of data

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: Species, Length: 150, dtype: bool

In [92]:
data.loc[data.Species == 'Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [93]:
data.loc[(data.Species == 'Iris-setosa') & (data.SepalLengthCm == 5.1)]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa

In [94]:
data.loc[(data.Species == 'Iris-setosa') | (data.SepalLengthCm == 5.1)]
# which is rated above average

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
40,41,5.0,3.5,1.3,0.3,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
44,45,5.1,3.8,1.9,0.4,Iris-setosa
45,46,4.8,3.0,1.4,0.3,Iris-setosa
46,47,5.1,3.8,1.6,0.2,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
98,99,5.1,2.5,3.0,1.1,Iris-versicolor

In [95]:
data.loc[data.PetalWidthCm.isin([0.2])]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [96]:
data.loc[data.PetalWidthCm.notnull()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

Summary Functions and Maps

In [ ]:
print(data.SepalLengthCm.describe)

<bound method NDFrame.describe of 0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64>

In [101]:
print(data.SepalLengthCm.mean())

5.843333333333334

In [102]:
print(data.SepalLengthCm.unique())

[5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]

In [103]:
mean = data.SepalLengthCm.mean()
data.SepalLengthCm.map(lambda p: p - mean)

0     -0.743333
1     -0.943333
2     -1.143333
3     -1.243333
4     -0.843333
         ...
145    0.856667
146    0.456667
147    0.656667
148    0.356667
149    0.056667
Name: SepalLengthCm, Length: 150, dtype: float64

In [107]:
mean_data = data.SepalLengthCm.mean()
def mean(data):
    data.SepalLengthCm = data.SepalLengthCm - mean_data
    return data

print(data.apply(mean  , axis='columns'))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1      -0.743333           3.5            1.4           0.2
1      2      -0.943333           3.0            1.4           0.2
2      3      -1.143333           3.2            1.3           0.2
3      4      -1.243333           3.1            1.5           0.2
4      5      -0.843333           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146       0.856667           3.0            5.2           2.3
146  147       0.456667           2.5            5.0           1.9
147  148       0.656667           3.0            5.2           2.0
148  149       0.356667           3.4            5.4           2.3
149  150       0.056667           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

Grouping and Sorting

In [111]:
data.groupby('SepalLengthCm').PetalLengthCm.count()

SepalLengthCm
4.3     1
4.4     3
4.5     1
4.6     4
4.7     2
4.8     5
4.9     6
5.0    10
5.1     9
5.2     4
5.3     1
5.4     6
5.5     7
5.6     6
5.7     8
5.8     7
5.9     3
6.0     6
6.1     6
6.2     4
6.3     9
6.4     7
6.5     5
6.6     2
6.7     8
6.8     3
6.9     4
7.0     1
7.1     1
7.2     3
7.3     1
7.4     1
7.6     1
7.7     4
7.9     1
Name: PetalLengthCm, dtype: int64

In [112]:
data.groupby('SepalLengthCm').PetalLengthCm.min()

SepalLengthCm
4.3    1.1
4.4    1.3
4.5    1.3
4.6    1.0
4.7    1.3
4.8    1.4
4.9    1.4
5.0    1.2
5.1    1.4
5.2    1.4
5.3    1.5
5.4    1.3
5.5    1.3
5.6    3.6
5.7    1.5
5.8    1.2
5.9    4.2
6.0    4.0
6.1    4.0
6.2    4.3
6.3    4.4
6.4    4.3
6.5    4.6
6.6    4.4
6.7    4.4
6.8    4.8
6.9    4.9
7.0    4.7
7.1    5.9
7.2    5.8
7.3    6.3
7.4    6.1
7.6    6.6
7.7    6.1
7.9    6.4
Name: PetalLengthCm, dtype: float64

In [ ]:
data.groupby('SepalLengthCm').apply( lambda p : p.PetalLengthCm.iloc[0])

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_13631/1697162426.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data.groupby('SepalLengthCm').apply( lambda p : p.PetalLengthCm.iloc[0])

SepalLengthCm
4.3    1.1
4.4    1.4
4.5    1.3
4.6    1.5
4.7    1.3
4.8    1.6
4.9    1.4
5.0    1.4
5.1    1.4
5.2    1.5
5.3    1.5
5.4    1.7
5.5    1.4
5.6    3.6
5.7    1.5
5.8    1.2
5.9    4.2
6.0    4.0
6.1    4.7
6.2    4.5
6.3    4.7
6.4    4.5
6.5    4.6
6.6    4.6
6.7    4.4
6.8    4.8
6.9    4.9
7.0    4.7
7.1    5.9
7.2    6.1
7.3    6.3
7.4    6.1
7.6    6.6
7.7    6.7
7.9    6.4
dtype: float64

In [128]:
countries_reviewed  = data.groupby(['SepalLengthCm','SepalWidthCm']).PetalLengthCm.agg([len,max,min])
countries_reviewed

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_13631/1032662803.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  countries_reviewed  = data.groupby(['SepalLengthCm','SepalWidthCm']).PetalLengthCm.agg([len,max,min])
/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_13631/1032662803.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  countries_reviewed  = data.groupby(['SepalLengthCm','SepalWidthCm']).PetalLengthCm.agg([len,max,min])

                            len  max  min
SepalLengthCm SepalWidthCm
4.3           3.0             1  1.1  1.1
4.4           2.9             1  1.4  1.4
              3.0             1  1.3  1.3
              3.2             1  1.3  1.3
4.5           2.3             1  1.3  1.3
...                         ...  ...  ...
7.7           2.6             1  6.9  6.9
              2.8             1  6.7  6.7
              3.0             1  6.1  6.1
              3.8             1  6.7  6.7
7.9           3.8             1  6.4  6.4

[116 rows x 3 columns]

In [ ]:
data.reset_index

<bound method DataFrame.reset_index of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [135]:
data.sort_values(by='SepalLengthCm', ascending= False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
131,132,7.9,3.8,6.4,2.0,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
...,...,...,...,...,...,...
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa

Data Types and Missing Values

In [136]:
data.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [138]:
data[pd.isnull(data)]

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   NaN            NaN           NaN            NaN           NaN     NaN
1   NaN            NaN           NaN            NaN           NaN     NaN
2   NaN            NaN           NaN            NaN           NaN     NaN
3   NaN            NaN           NaN            NaN           NaN     NaN
4   NaN            NaN           NaN            NaN           NaN     NaN
..   ..            ...           ...            ...           ...     ...
145 NaN            NaN           NaN            NaN           NaN     NaN
146 NaN            NaN           NaN            NaN           NaN     NaN
147 NaN            NaN           NaN            NaN           NaN     NaN
148 NaN            NaN           NaN            NaN           NaN     NaN
149 NaN            NaN           NaN            NaN           NaN     NaN

[150 rows x 6 columns]

Renaming and Combining

In [140]:
data.rename(columns={'SepalLengthCm' : 'Sepal'})

      Id  Sepal  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1    5.1           3.5            1.4           0.2     Iris-setosa
1      2    4.9           3.0            1.4           0.2     Iris-setosa
2      3    4.7           3.2            1.3           0.2     Iris-setosa
3      4    4.6           3.1            1.5           0.2     Iris-setosa
4      5    5.0           3.6            1.4           0.2     Iris-setosa
..   ...    ...           ...            ...           ...             ...
145  146    6.7           3.0            5.2           2.3  Iris-virginica
146  147    6.3           2.5            5.0           1.9  Iris-virginica
147  148    6.5           3.0            5.2           2.0  Iris-virginica
148  149    6.2           3.4            5.4           2.3  Iris-virginica
149  150    5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]