In [103]:
import pandas as pd

In [104]:
data = pd.read_csv('pokemon_data.csv')

In [105]:
print(data.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [106]:
data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [107]:
data['Name'][:10]

0                    Bulbasaur
1                      Ivysaur
2                     Venusaur
3        VenusaurMega Venusaur
4                   Charmander
5                   Charmeleon
6                    Charizard
7    CharizardMega Charizard X
8    CharizardMega Charizard Y
9                     Squirtle
Name: Name, dtype: object

In [108]:
data[['Name' , 'Type 1']][:10]

                        Name Type 1
0                  Bulbasaur  Grass
1                    Ivysaur  Grass
2                   Venusaur  Grass
3      VenusaurMega Venusaur  Grass
4                 Charmander   Fire
5                 Charmeleon   Fire
6                  Charizard   Fire
7  CharizardMega Charizard X   Fire
8  CharizardMega Charizard Y   Fire
9                   Squirtle  Water

In [109]:
data.iloc[1:4]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [110]:
data.loc[1:4]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [111]:
# for index, row in data.iterrows():
#     print(index,row['Name'])

data['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [112]:
data.loc[data['Name'] == 'Venusaur']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [113]:
data.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [114]:
data.sort_values(['Name' , 'Type 1'],ascending= False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [115]:
data['Total Average'] = data['HP'] + data['Attack'] + data['Defense'] + data['Sp. Atk'] + data['Sp. Def'] + data['Speed'] + data['Generation']
print(data.columns)
print(data['Total Average'])
data.head()
data = data.drop(columns = ['Total Average'])

data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total Average'],
      dtype='object')
0      319
1      406
2      526
3      626
4      310
      ...
795    606
796    706
797    606
798    686
799    606
Name: Total Average, Length: 800, dtype: int64

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [116]:
data['total'] = data.iloc[:,4:10].sum(axis =1)
cols = list(data.columns.values)
data = data[cols[:4] + [cols[-1]] + cols[4:12]]
data.head(5)

,#,Name,Type 1,Type 2,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [117]:
import re
print(data.loc[data['Type 1'].str.contains('fire|glass' ,flags = re.I , regex= True )])

       #                       Name Type 1    Type 2  total   HP  Attack  \
4      4                 Charmander   Fire       NaN    309   39      52
5      5                 Charmeleon   Fire       NaN    405   58      64
6      6                  Charizard   Fire    Flying    534   78      84
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104
42    37                     Vulpix   Fire       NaN    299   38      41
43    38                  Ninetales   Fire       NaN    505   73      76
63    58                  Growlithe   Fire       NaN    350   55      70
64    59                   Arcanine   Fire       NaN    555   90     110
83    77                     Ponyta   Fire       NaN    410   50      85
84    78                   Rapidash   Fire       NaN    500   65     100
135  126                     Magmar   Fire       NaN    495   65      95
147  136                    Flareon   Fire       NaN    525   65     130
158  146                    Moltres   Fire    Flying    580   90     100
169  155                  Cyndaquil   Fire       NaN    309   39      52
170  156                    Quilava   Fire       NaN    405   58      64
171  157                 Typhlosion   Fire       NaN    534   78      84
236  218                     Slugma   Fire       NaN    250   40      40
237  219                   Magcargo   Fire      Rock    410   50      50
259  240                      Magby   Fire       NaN    365   45      75
263  244                      Entei   Fire       NaN    580  115     115
270  250                      Ho-oh   Fire    Flying    680  106     130
276  255                    Torchic   Fire       NaN    310   45      60
277  256                  Combusken   Fire  Fighting    405   60      85
278  257                   Blaziken   Fire  Fighting    530   80     120
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160
352  322                      Numel   Fire    Ground    305   60      60
353  323                   Camerupt   Fire    Ground    460   70     100
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120
355  324                    Torkoal   Fire       NaN    470   70      85
435  390                   Chimchar   Fire       NaN    309   44      58
436  391                   Monferno   Fire  Fighting    405   64      78
437  392                  Infernape   Fire  Fighting    534   76     104
518  467                  Magmortar   Fire       NaN    540   75      95
542  485                    Heatran   Fire     Steel    600   91      90
557  498                      Tepig   Fire       NaN    308   65      63
558  499                    Pignite   Fire  Fighting    418   90      93
559  500                     Emboar   Fire  Fighting    528  110     123
572  513                    Pansear   Fire       NaN    316   50      53
573  514                   Simisear   Fire       NaN    498   75      98
614  554                   Darumaka   Fire       NaN    315   70      90
615  555    DarmanitanStandard Mode   Fire       NaN    480  105     140
616  555         DarmanitanZen Mode   Fire   Psychic    540  105      30
692  631                    Heatmor   Fire       NaN    484   85      97
721  653                   Fennekin   Fire       NaN    307   40      45
722  654                    Braixen   Fire       NaN    409   59      59
723  655                    Delphox   Fire   Psychic    534   75      69
730  662                Fletchinder   Fire    Flying    382   62      73
731  663                 Talonflame   Fire    Flying    499   78      81
735  667                     Litleo   Fire    Normal    369   62      50
736  668                     Pyroar   Fire    Normal    507   86      68
799  721                  Volcanion   Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         43       60       50     65           1      False
5         58       80       65     80           1      False
6         78      109       85    100           1      False
7        111      130       85    100           1      False
8         78      159      115    100           1      False
42        40       50       65     65           1      False
43        75       81      100    100           1      False
63        45       70       50     60           1      False
64        80      100       80     95           1      False
83        55       65       65     90           1      False
84        70       80       80    105           1      False
135       57      100       85     93           1      False
147       60       95      110     65           1      False
158       90      125       85     90           1       True
169       43       60       50     65           2      False
170       58       80       65     80           2      False
171       78      109       85    100           2      False
236       40       70       40     20           2      False
237      120       80       80     30           2      False
259       37       70       55     83           2      False
263       85       90       75    100           2       True
270       90      110      154     90           2       True
276       40       70       50     45           3      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
352       40       65       45     35           3      False
353       70      105       75     40           3      False
354      100      145      105     20           3      False
355      140       85       70     20           3      False
435       44       58       44     61           4      False
436       52       78       52     81           4      False
437       71      104       71    108           4      False
518       67      125       95     83           4      False
542      106      130      106     77           4       True
557       45       45       45     45           5      False
558       55       70       55     55           5      False
559       65      100       65     65           5      False
572       48       53       48     64           5      False
573       63       98       63    101           5      False
614       45       15       45     50           5      False
615       55       30       55     95           5      False
616      105      140      105     55           5      False
692       66      105       66     65           5      False
721       40       62       60     60           6      False
722       58       90       70     73           6      False
723       72      114      100    104           6      False
730       55       56       52     84           6      False
731       71       74       69    126           6      False
735       58       73       54     72           6      False
736       72      109       66    106           6      False
799      120      130       90     70           6       True

In [118]:
print(data.loc[data['Type 1'].str.contains('p[a-z]*' ,flags = re.I , regex= True )])

       #                 Name   Type 1  Type 2  total  HP  Attack  Defense  \
28    23                Ekans   Poison     NaN    288  35      60       44
29    24                Arbok   Poison     NaN    438  60      85       69
34    29     Nidoran (Female)   Poison     NaN    275  55      47       52
35    30             Nidorina   Poison     NaN    365  70      62       67
36    31            Nidoqueen   Poison  Ground    505  90      92       87
..   ...                  ...      ...     ...    ...  ..     ...      ...
747  678       MeowsticFemale  Psychic     NaN    466  74      48       76
760  690               Skrelp   Poison   Water    320  50      60       60
761  691             Dragalge   Poison  Dragon    494  65      75       90
797  720  HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720   HoopaHoopa Unbound  Psychic    Dark    680  80     160       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
28        40       54     55           1      False
29        65       79     80           1      False
34        40       40     41           1      False
35        55       55     56           1      False
36        75       85     76           1      False
..       ...      ...    ...         ...        ...
747       83       81    104           6      False
760       60       60     30           6      False
761       97      123     44           6      False
797      150      130     70           6       True
798      170      130     80           6       True

[85 rows x 13 columns]

In [119]:
data.to_csv('modified_txt')

In [122]:
data.groupby(['Type 1'] ).mean(numeric_only=True).sort_values('Defense' , ascending= False)

,#,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [ ]:
data.columns
# data[['Sp. Def', 'Speed', 'Legendary']].dtypes

Index(['#', 'Name', 'Type 1', 'Type 2', 'total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')