In [266]:
import pandas as pd

In [267]:
data = pd.read_csv('bios.csv')
data

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [268]:
data.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name',
       'Name order'],
      dtype='object')

In [269]:
df = data.copy()

- [x] bullet points in the  full name and last name
- [x] split height and weight 
- [x] divide the born date , born place same with died also 
- [] for died null values we could chnage the value to not dead or no like some kind of words 
- [] age of time of dead  
- [] extra columns which has most of Nan values

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [271]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [272]:
df.describe(include='all')

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
count,145500,145500,145500,145500,143772,34042,145499,145500.000000,107833,95832,9145,399,7167,8259,30739,7844
unique,70,2,144663,142780,135475,32654,696,NaN,4658,40559,7350,168,7098,94,30417,1
top,Competed in Olympic Games,Male,Wang•Nan,Ivan•Ivanov,1931,"(Deceased, details unknown)",United States,NaN,180 cm / 75 kg,"CSKA Moskva, Moskva (RUS)",Pena,Sir,Kim Mi-Jung,Russian Federation,王•楠,Oriental
freq,134613,106325,6,13,30,42,10114,NaN,556,337,15,49,4,2104,5,7844
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73686.188955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42868.960158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36663.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73302.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110306.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149814.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [273]:
len(df[df['Used name'].str.contains('•')])

145500

In [274]:
df['Name'] = df['Used name'].str.replace('•' ,' ')
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,Polina Luchnikova
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,Valeriya Merkusheva
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,Yuliya Smirnova
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips

In [275]:
df['Full name'].str.contains('•', na = False).sum()

np.int64(145252)

In [276]:
df[['height_cm','weight_kg']] = df['Measurements'].str.split('/' , expand= True)
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,Polina Luchnikova,167 cm,61 kg
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,Valeriya Merkusheva,168 cm,65 kg
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,Yuliya Smirnova,163 cm,55 kg
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166 cm,None
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [277]:
# check if the measurement values has All the same sign which is /
df['weight_kg'].fillna(df['height_cm'] , inplace= True)
df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(' cm') ,errors= 'coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(' kg') ,errors= 'coerce')
# change the kg and cm get rid of them
df[~df['Measurements'].str.contains('/' , na= False) & df['Measurements'].notna()]

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_22767/669109823.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight_kg'].fillna(df['height_cm'] , inplace= True)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178.0,NaN
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191.0,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,NaN,120.0
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161.0,NaN
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov,168.0,NaN
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva,160.0,NaN
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina,190.0,NaN
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183.0,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166.0,NaN

In [278]:
df.sort_values('height_cm',ascending=False)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg
89070,Competed in Olympic Games • Other,Male,Yao•Ming,Yao•Ming,"12 September 1980 in Xuhui District, Shanghai ...",NaN,People's Republic of China,89782,226 cm / 141 kg,"Shanghai Sharks, Shanghai (CHN) / Houston Rock...",NaN,NaN,NaN,NaN,姚•明,Oriental,Yao Ming,226.0,141.0
5781,Competed in Olympic Games,Male,"Thomas Loren ""Tommy""•Burleson",Tommy•Burleson,"24 February 1952 in Crossnore, North Carolina ...",NaN,United States,5804,223 cm / 102 kg,"NC State Wolfpack, Raleigh (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Tommy Burleson,223.0,102.0
6978,Competed in Olympic Games,Male,Arvydas Romas•Sabonis,Arvydas•Sabonis,"19 December 1964 in Kaunas, Kaunas (LTU)",NaN,Lithuania Soviet Union,7013,223 cm / 122 kg,"Žalgiris Kaunas, Kaunas (LTU) / Real Madrid, M...",Sabas,NaN,"Arvidas Romas Sabonis, Арвидас Ромас Сабонис",Lithuania,NaN,NaN,Arvydas Sabonis,223.0,122.0
89075,Competed in Olympic Games,Male,Roberto•Dueñas Hernández,Roberto•Dueñas,"1 November 1975 in Madrid, Madrid (ESP)",NaN,Spain,89787,221 cm / 137 kg,"FC Barcelona, Barcelona (ESP)",NaN,NaN,NaN,NaN,NaN,NaN,Roberto Dueñas,221.0,137.0
120266,Competed in Olympic Games,Male,Zhang•Zhaoxu,Zhang•Zhaoxu,"18 November 1987 in Binzhou, Shandong (CHN)",NaN,People's Republic of China,122147,221 cm / 110 kg,"Shanghai Sharks, Shanghai (CHN)",NaN,NaN,NaN,NaN,张•兆旭,Oriental,Zhang Zhaoxu,221.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,Competed in Olympic Games,Male,Sin•Ye-Chan,Sin•Ye-Chan,13 June 1995,NaN,Republic of Korea,149217,NaN,NaN,NaN,NaN,Shin Ye-Chan,NaN,신•예찬,Oriental,Sin Ye-Chan,NaN,NaN
145491,Competed in Olympic Games,Male,Matthew•Wepke,Matthew•Wepke,5 December 1989,NaN,Jamaica,149218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matthew Wepke,NaN,NaN
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos•García-Ordóñez,"24 April 1927 in La Habana (Havana), Ciudad de...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlos García-Ordóñez,NaN,NaN
145493,Competed in Olympic Games,Female,Landysh Ilsurovna•Falyakhova,Landysh•Falyakhova,"31 August 1998 in Dva Polya Artash, Respublika...",NaN,ROC,149220,NaN,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Ландыш Ильсуровна•Фаляхова,NaN,Landysh Falyakhova,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [279]:
date_pattern = r'(\d+ \w+ \d{4} |\d{4})'
df['born_date'] = df['Born'].str.extract(date_pattern)
# df[df['Born'].str.match(date_pattern , na= False) & df['Born'].notna()]
df['born_date'] = pd.to_datetime(df['born_date'],format= 'mixed' , errors= 'coerce')
df['Died_date'] = df['Died'].str.extract(date_pattern)
# df[df['Born'].str.match(date_pattern , na= False) & df['Born'].notna()]
df['Died_date'] = pd.to_datetime(df['Died_date'],format= 'mixed' , errors= 'coerce')
df['born_year'] = df['Born'].str.extract(r'(\d{4})')

In [288]:
# get city region from born column
location_pattern = r'in ([\w\s-]+), ([\w\s-]+) \((\w+)\)'
df['Born'].str.extract(location_pattern)

                   0                     1    2
0           Bordeaux               Gironde  FRA
1             Meulan              Yvelines  FRA
2           Biarritz  Pyrénées-Atlantiques  FRA
3        Paris VIIIe                 Paris  FRA
4         Wandsworth               England  GBR
...              ...                   ...  ...
145495         Serov            Sverdlovsk  RUS
145496           NaN                   NaN  NaN
145497        Kotlas           Arkhangelsk  RUS
145498         Niort           Deux-Sèvres  FRA
145499  Dulwich Hill       New South Wales  AUS

[145500 rows x 3 columns]

In [289]:
df[['born_city' ,'born_region' ,'born_country']] = df['Born'].str.extract(location_pattern)
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,Name,height_cm,weight_kg,born_date,Died_date,born_year,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02,1886,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,NaT,1969,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,1898-08-13,1994-07-17,1898,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1978-03-20,1895,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25,1878,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,Polina Luchnikova,167.0,61.0,2002-01-30,NaT,2002,Serov,Sverdlovsk,RUS
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,NaN,Valeriya Merkusheva,168.0,65.0,1999-09-20,NaT,1999,NaN,NaN,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,NaN,Yuliya Smirnova,163.0,55.0,1998-05-08,NaT,1998,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,André Foussard,166.0,NaN,1899-05-19,1986-03-18,1899,Niort,Deux-Sèvres,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,...,NaN,Bill Phillips,NaN,NaN,1913-07-15,2003-10-20,1913,Dulwich Hill,New South Wales,AUS

In [ ]:
# remove columns