In [471]:
import pandas as pd

In [472]:
data = pd.read_excel('Amazon_Products_Reviews_Dataset_UNCLEANED.xlsx')
df= data.copy()

- [] product_id remove B0 as most them have the same
- [] product_name it shouldn't be having any any spaces 
- [] category has all capitals in few need to capitalize it 
- [] Discounted_price has Rs: in few and not and it has INR marks in few rest it is missing it has negative values 
- [] in actual_price it has same as Discounted_price and few they are in float like 699.00 it has negative values 
- [] rating_count it has '|'  '-1' '3'  '2' so few symbols int values and negative values it needs to be in float values 
- []  discount_percentage it has '-15%' '39' few are in negative and only integers without % symbol
- [] change all the datatypes

kaggle gathered insights :

product_id : Check duplicate values, remove extra spaces, ensure all Product IDs are in the same format.
product_name : 30 missing values, remove extra spaces and convert to Proper Case.
category : 30 missing values, remove extra spaces and standardize category names.
Discounted_Price (INR) : Remove ₹, Rs., commas and spaces, convert data type to Float, all values should be > 0.
actual_price : Remove ₹ and commas, convert data type to Float, all values should be > 0 and greater than or equal to Discounted Price.
discount_percentage : Remove % symbol, convert data type to Float, all values should be > 0 and < 100.
rating : Missing values, convert data type to Float, rating should be between 1 and 5.
Rating Count : Remove commas, convert data type to Int, all values should be ≥ 0.
about_product : 30 missing values, remove extra spaces and unwanted special characters.
user_id : 30 missing values, ensure proper formatting and remove extra spaces.
user_name : 30 missing values, convert into Proper Case and remove extra spaces.
review_id : Check duplicate values and ensure all Review IDs are unique.
review_title : 30 missing values, remove extra spaces and unwanted symbols.
review_content : 30 missing values, clean unwanted spaces, special characters and blank text.
IMG_LINK : 30 missing values, ensure all links are valid and start with https://.
product_link : 30 missing values, ensure all links are valid and remove broken URLs.
Duplicate Records : Remove duplicate rows from the dataset.
Missing Values : Fill numeric columns with Median and categorical columns with Mode or "Unknown".
Data Type : Convert all price, rating, discount and rating count columns into appropriate numeric data types.

In [473]:
df.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

In [474]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1479 non-null   object
 1   product_name            1476 non-null   object
 2   category                1473 non-null   object
 3   Discounted_Price (INR)  1473 non-null   object
 4   actual_price            1473 non-null   object
 5   discount_percentage     1473 non-null   object
 6   rating                  1470 non-null   object
 7   Rating Count            1468 non-null   object
 8   about_product           1473 non-null   object
 9   user_id                 1487 non-null   object
 10  user_name               1486 non-null   object
 11  review_id               1487 non-null   object
 12  review_title            1481 non-null   object
 13  review_content          1483 non-null   object
 14  IMG_LINK                1476 non-null   object
 15  product_link            1476 non-null   object
dtypes: object(16)
memory usage: 187.0+ KB

In [475]:
df.isnull().sum()

product_id                16
product_name              19
category                  22
Discounted_Price (INR)    22
actual_price              22
discount_percentage       22
rating                    25
Rating Count              27
about_product             22
user_id                    8
user_name                  9
review_id                  8
review_title              14
review_content            12
IMG_LINK                  19
product_link              19
dtype: int64

In [476]:
df.duplicated().sum()
df = df.drop_duplicates()

In [477]:
df.describe(include='all')

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
count,1473,1470,1467,1467,1467,1467,1464,1462,1467,1481,1480,1481,1475,1477,1470,1470
unique,1350,1346,260,610,520,141,32,1138,1289,1199,1204,1194,1192,1214,1406,1454
top,B08DDRGWTJ,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,60%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/LG-Convertible-Anti-Viru...
freq,4,5,222,54,110,55,243,9,5,10,10,10,10,8,3,2

In [478]:
columns = df.columns

for i in columns:
    print(i)
    print(df[i].unique())

product_id
['B08SMJT55F' 'B07F6GXNPB' 'B08TTRVWKY' ... 'B091JF2TFD' 'B0B3JSWG81'
 'B00PVT30YI']
product_name
['boAt Stone 250 Portable Wireless Speaker with 5W RMS Immersive Audio, RGB LEDs, Up to 8HRS Playtime, IPX7 Water Resistance, Multi-Compatibility Modes(Black)'
 'EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER DUST BAGS FOR EXCEL, ACE, 300, JET MODELS - SET OF 10'
 'MILTON Smart Egg Boiler 360-Watts (Transparent and Silver Grey), Boil Up to 7 Eggs'
 ...
 'Boult Audio BassBuds Oak in-Ear Wired Earphones with 10mm Extra Bass Driver and HD Sound with mic(Brown)'
 'NGI Store 2 Pieces Pet Hair Removers for Your Laundry Catcher Lint Remover for Washing Machine Lint Remover Reusable Portable Silica Gel Clothes Washer Dryer Floating Ball'
 'Kitchen Mart Stainless Steel South Indian Filter Coffee Drip Maker, Madras Kappi, Drip Decotion Maker160ml (2 Cup)']
category
['Electronics|HomeAudio|Speakers|BluetoothSpeakers'
 ' Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice'
 nan
 'Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters'
 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks'
 'computers&accessories|accessories&peripherals|cables&accessories|cables|usbcables'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Electronics|WearableTechnology|SmartWatches'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers'
 'Computers&Accessories|Tablets'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders '
 'Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps'
 'Electronics|GeneralPurposeBatteries&BatteryChargers'
 ' Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor'
 'Computers&Accessories|ExternalDevices&DataStorage|PenDrives'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets'
 'HOME&KITCHEN|KITCHEN&HOMEAPPLIANCES|VACUUM,CLEANING&IRONING|IRONS,STEAMERS&ACCESSORIES|IRONS|DRYIRONS'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers'
 'Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles'
 'Computers&Accessories|NetworkingDevices|Routers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums'
 'OFFICEPRODUCTS|OFFICEPAPERPRODUCTS|PAPER|STATIONERY|PENS,PENCILS&WRITINGSUPPLIES|PENS&REFILLS|GELINKROLLERBALLPENS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters'
 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers '
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands'
 'electronics|mobiles&accessories|smartphones&basicmobiles|smartphones'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers'
 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|EXTERNALHARDDISKS'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop'
 'Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines'
 ' Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'electronics|wearabletechnology|smartwatches'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles'
 'Electronics|Accessories|MemoryCards|MicroSD'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|MICE'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts'
 'Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines'
 'Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums'
 'Computers&Accessories|Accessories&Peripherals|Cabels&Accessories|Cabels|USBCabels'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters'
 'home&kitchen|kitchen&homeappliances|smallkitchenappliances|kettles&hotwaterdispensers|kettle&toastersets'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets'
 'Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters'
 'Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers'
 'Electronics|HomeAudio|Accessories|Adapters'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders'
 'Computers&Accessories|Printers,Inks&Accessories|Printers'
 'OfficeProducts|OfficeElectronics|Calculators|Financial&Business'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers'
 'Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports'
 'Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors'
 ' OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons'
 'Electronics|Mobiles&Accessories|MobileAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers'
 'Computers&Accessories|Accessories&Peripherals|USBHubs'
 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts'
 'Electronics|Mobiles&Accessories|MobileAccessories|StylusPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens'
 'Electronics|HomeTheater,TV&Video|Projectors'
 'Electronics|Headphones,Earbuds&Accessories|Adapters'
 'Computers&Accessories|Monitors'
 'Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies'
 'Computers&Accessories|Components|InternalSolidStateDrives'
 ' Computers&Accessories|NetworkingDevices|Routers'
 ' Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|VideoCameras'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear'
 'electronics|mobiles&accessories|mobileaccessories|chargers|wallchargers'
 'Electronics|HomeTheater,TV&Video|Accessories|3DGlasses'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|PENDRIVES'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|ACCESSORIES|CABLES|HDMICABLES'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|CABLES&ACCESSORIES|CABLES|USBCABLES'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries'
 'MusicalInstruments|Microphones|Condenser'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes'
 'HOME&KITCHEN|HEATING,COOLING&AIRQUALITY|WATERHEATERS&GEYSERS|INSTANTWATERHEATERS'
 'home&kitchen|homestorage&organization|laundryorganization|laundrybaskets'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables '
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums'
 'Home&Kitchen|CraftMaterials|Scrapbooking|Tape'
 'Electronics|PowerAccessories|SurgeProtectors'
 'Computers&Accessories|Accessories&Peripherals|HardDiskBags'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters'
 'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|KEYBOARDS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases'
 'electronics|hometheater,tv&video|accessories|tvmounts,stands&turntables|tvwall&ceilingmounts'
 'Electronics|Headphones,Earbuds&Accessories|Cases'
 'Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'HomeImprovement|Electrical|CordManagement'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets'
 ' Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Electronics|Accessories|MemoryCards|SecureDigitalCards'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits'
 'Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers '
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales'
 'ELECTRONICS|HEADPHONES,EARBUDS&ACCESSORIES|HEADPHONES|IN-EAR'
 ' Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges'
 'Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems'
 'Home&Kitchen|CraftMaterials|PaintingMaterials'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms'
 'OfficeProducts|OfficeElectronics|Calculators|Basic'
 ' Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables '
 'electronics|mobiles&accessories|mobileaccessories|automobileaccessories|cradles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers '
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters'
 'Computers&Accessories|NetworkingDevices|DataCards&Dongles'
 'OfficeProducts|OfficeElectronics|Calculators|Scientific'
 'Electronics|Cameras&Photography|SecurityCameras|DomeCameras'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags'
 'Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales'
 'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases'
 ' Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens'
 'Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits'
 'Electronics|HomeAudio|MediaStreamingDevices|StreamingClients'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|TELEVISIONS|SMARTTELEVISIONS'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders '
 'computers&accessories|networkingdevices'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens'
 ' Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Electronics|HomeAudio|Speakers|SoundbarSpeakers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights'
 'Electronics|Cameras&Photography|Accessories|Film'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories'
 'Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives'
 ' Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners'
 'Electronics|Headphones,Earbuds&Accessories|Earpads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers '
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams'
 'Computers&Accessories|Laptops|TraditionalLaptops'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons '
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps '
 'Computers&Accessories|Components|InternalHardDrives'

In [479]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

1. Product_id

In [480]:
df['product_id'].str.contains('B0').sum()

1454

In [481]:
df['product_id'].shape
df['product_id'].isna().sum()

np.int64(9)

In [482]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [483]:
df['product_id'] = df['product_id'].str.replace('B0' , '')
df['product_id'] = df['product_id'].str.replace('b0' , '')
df
# df.loc[~df['product_id'].str.startswith('B0' , na= False) ,'product_id']

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [484]:
df.loc[~df['product_id'].str.startswith('B0' , na= False) ,'product_id']

0       8SMJT55F
1       7F6GXNPB
2       8TTRVWKY
3       1MQ2A86A
4       8GM5S4CQ
          ...
1490    756K5DYZ
1491    1LY9W8AF
1492    91JF2TFD
1493    B3JSWG81
1494    0PVT30YI
Name: product_id, Length: 1482, dtype: object

In [485]:
df['product_id'].isna().sum()
df['product_id'] = df['product_id'].fillna('Unknown')

In [486]:
df['product_id'].isna().sum()

np.int64(0)

In [487]:
df['product_id'].duplicated().sum()

np.int64(131)

In [488]:
df['product_id'] = df['product_id'].str.strip()

2. Product_name

In [489]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [490]:
df['product_name'].isna().sum()

np.int64(12)

In [491]:
df['product_name'] = df['product_name'].str.capitalize()

In [492]:
df[df['product_name'] == df['product_name'].str.upper()]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [493]:
df['product_name'] = df['product_name'].str.strip()

3. Categories
category : 30 missing values, remove extra spaces and standardize category names.

In [494]:

df['category'].isna().sum()
df[df['category'] == df['category'].str.upper()]
df['category'] = df['category'].str.capitalize()

In [495]:
df[df['category'] == df['category'].str.upper()].sum()

product_id                0
product_name              0
category                  0
Discounted_Price (INR)    0
actual_price              0
discount_percentage       0
rating                    0
Rating Count              0
about_product             0
user_id                   0
user_name                 0
review_id                 0
review_title              0
review_content            0
IMG_LINK                  0
product_link              0
dtype: object

In [496]:
df['category'].duplicated().sum()

np.int64(1244)

In [497]:
df['category'] = df['category'].str.strip()

4 . Discounted price
Discounted_Price (INR) : Remove ₹, Rs., commas and spaces, convert data type to Float, all values should be > 0.

In [498]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,Boat stone 250 portable wireless speaker with ...,Electronics|homeaudio|speakers|bluetoothspeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,Eureka forbes euroclean paper vacuum cleaner d...,"home&kitchen|kitchen&homeappliances|vacuum,cle...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,Milton smart egg boiler 360-watts (transparent...,Home&kitchen|kitchen&homeappliances|smallkitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech m331 silent plus wireless mouse, 2.4g...",Computers&accessories|accessories&peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells instanio 10 litre storage water heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige iris 750 watt mixer grinder with 3 st...,Home&kitchen|kitchen&homeappliances|smallkitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello eliza plastic laundry bag/basket, 50 lit...",Home&kitchen|homestorage&organization|laundryo...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult audio bassbuds oak in-ear wired earphone...,"Electronics|headphones,earbuds&accessories|hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,Ngi store 2 pieces pet hair removers for your ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen mart stainless steel south indian filt...,"Home&kitchen|kitchen&homeappliances|coffee,tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [499]:
df['Discounted_Price (INR)'].isnull().sum()
df.loc[~df['Discounted_Price (INR)'].str.contains('₹|Rs|,|\s', na=False), ['Discounted_Price (INR)']]

     Discounted_Price (INR)
3                       NaN
40                      289
54                      299
84                      449
110                     249
...                     ...
1395                    599
1397                   1399
1412                   5799
1436                    115
1463                    599

[62 rows x 1 columns]

In [500]:
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('₹' , '')
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('Rs. ' , '')
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace(',' , '')
df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('₹|Rs\. |,', '' , regex=True)
df['Discounted_Price (INR)']

0         1199
1          253
2         1099
3          NaN
4         6990
         ...
1490      3249
1491    998.06
1492       499
1493       199
1494       292
Name: Discounted_Price (INR), Length: 1482, dtype: object

In [501]:
df['Discounted_Price (INR)'] = pd.to_numeric(df['Discounted_Price (INR)'].str.strip().str.replace('\s+', '', regex=True),errors='coerce')
df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].astype('float')

In [503]:
df['Discounted_Price (INR)'].dtype

dtype('float64')