In [3607]:
import pandas as pd
import numpy as np

In [3608]:
data = pd.read_excel('Amazon_Products_Reviews_Dataset_UNCLEANED.xlsx')
df= data.copy()

- [] product_id remove B0 as most them have the same
- [] product_name it shouldn't be having any any spaces 
- [] category has all capitals in few need to capitalize it 
- [] Discounted_price has Rs: in few and not and it has INR marks in few rest it is missing it has negative values 
- [] in actual_price it has same as Discounted_price and few they are in float like 699.00 it has negative values 
- [] rating_count it has '|'  '-1' '3'  '2' so few symbols int values and negative values it needs to be in float values 
- []  discount_percentage it has '-15%' '39' few are in negative and only integers without % symbol
- [] change all the datatypes

kaggle gathered insights :

- [x] product_id : Check duplicate values, remove extra spaces, ensure all Product IDs are in the same format.
- [x] product_name : 30 missing values, remove extra spaces and convert to Proper Case.
- [x] category : 30 missing values, remove extra spaces and standardize category names.
- [x] Discounted_Price (INR) : Remove ₹, Rs., commas and spaces, convert data type to Float, all values should be > 0.
- [x] actual_price : Remove ₹ and commas, convert data type to Float, all values should be > 0 and greater than or equal to Discounted Price.
- [x] discount_percentage : Remove % symbol, convert data type to Float, all values should be > 0 and < 100.
- [x] rating : Missing values, convert data type to Float, rating should be between 1 and 5.
- [x] Rating Count : Remove commas, convert data type to Int, all values should be ≥ 0.
- [x] about_product : 30 missing values, remove extra spaces and unwanted special characters.
- [x] user_id : 30 missing values, ensure proper formatting and remove extra spaces.
- [x] user_name : 30 missing values, convert into Proper Case and remove extra spaces.
- [x] review_id : Check duplicate values and ensure all Review IDs are unique.
- [x] review_title : 30 missing values, remove extra spaces and unwanted symbols.
- [x] review_content : 30 missing values, clean unwanted spaces, special characters and blank text.
- [x]IMG_LINK : 30 missing values, ensure all links are valid and start with https://.
- [x] product_link : 30 missing values, ensure all links are valid and remove broken URLs.
- [x] Duplicate Records : Remove duplicate rows from the dataset.
- [x] Missing Values : Fill numeric columns with Median and categorical columns with Mode or "Unknown".
- [x] Data Type : Convert all price, rating, discount and rating count columns into appropriate numeric data types.

In [3609]:
df.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

In [3610]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1479 non-null   object
 1   product_name            1476 non-null   object
 2   category                1473 non-null   object
 3   Discounted_Price (INR)  1473 non-null   object
 4   actual_price            1473 non-null   object
 5   discount_percentage     1473 non-null   object
 6   rating                  1470 non-null   object
 7   Rating Count            1468 non-null   object
 8   about_product           1473 non-null   object
 9   user_id                 1487 non-null   object
 10  user_name               1486 non-null   object
 11  review_id               1487 non-null   object
 12  review_title            1481 non-null   object
 13  review_content          1483 non-null   object
 14  IMG_LINK                1476 non-null   object
 15  product_link            1476 non-null   object
dtypes: object(16)
memory usage: 187.0+ KB

In [3611]:
df.isnull().sum()

product_id                16
product_name              19
category                  22
Discounted_Price (INR)    22
actual_price              22
discount_percentage       22
rating                    25
Rating Count              27
about_product             22
user_id                    8
user_name                  9
review_id                  8
review_title              14
review_content            12
IMG_LINK                  19
product_link              19
dtype: int64

In [3612]:
df.duplicated().sum()
df = df.drop_duplicates()

In [3613]:
df.describe(include='all')

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
count,1473,1470,1467,1467,1467,1467,1464,1462,1467,1481,1480,1481,1475,1477,1470,1470
unique,1350,1346,260,610,520,141,32,1138,1289,1199,1204,1194,1192,1214,1406,1454
top,B08DDRGWTJ,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,60%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/LG-Convertible-Anti-Viru...
freq,4,5,222,54,110,55,243,9,5,10,10,10,10,8,3,2

In [3614]:
columns = df.columns

for i in columns:
    print(i)
    print(df[i].unique())

product_id
['B08SMJT55F' 'B07F6GXNPB' 'B08TTRVWKY' ... 'B091JF2TFD' 'B0B3JSWG81'
 'B00PVT30YI']
product_name
['boAt Stone 250 Portable Wireless Speaker with 5W RMS Immersive Audio, RGB LEDs, Up to 8HRS Playtime, IPX7 Water Resistance, Multi-Compatibility Modes(Black)'
 'EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER DUST BAGS FOR EXCEL, ACE, 300, JET MODELS - SET OF 10'
 'MILTON Smart Egg Boiler 360-Watts (Transparent and Silver Grey), Boil Up to 7 Eggs'
 ...
 'Boult Audio BassBuds Oak in-Ear Wired Earphones with 10mm Extra Bass Driver and HD Sound with mic(Brown)'
 'NGI Store 2 Pieces Pet Hair Removers for Your Laundry Catcher Lint Remover for Washing Machine Lint Remover Reusable Portable Silica Gel Clothes Washer Dryer Floating Ball'
 'Kitchen Mart Stainless Steel South Indian Filter Coffee Drip Maker, Madras Kappi, Drip Decotion Maker160ml (2 Cup)']
category
['Electronics|HomeAudio|Speakers|BluetoothSpeakers'
 ' Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice'
 nan
 'Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters'
 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks'
 'computers&accessories|accessories&peripherals|cables&accessories|cables|usbcables'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Electronics|WearableTechnology|SmartWatches'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers'
 'Computers&Accessories|Tablets'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders '
 'Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps'
 'Electronics|GeneralPurposeBatteries&BatteryChargers'
 ' Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor'
 'Computers&Accessories|ExternalDevices&DataStorage|PenDrives'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets'
 'HOME&KITCHEN|KITCHEN&HOMEAPPLIANCES|VACUUM,CLEANING&IRONING|IRONS,STEAMERS&ACCESSORIES|IRONS|DRYIRONS'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers'
 'Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles'
 'Computers&Accessories|NetworkingDevices|Routers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums'
 'OFFICEPRODUCTS|OFFICEPAPERPRODUCTS|PAPER|STATIONERY|PENS,PENCILS&WRITINGSUPPLIES|PENS&REFILLS|GELINKROLLERBALLPENS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters'
 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers '
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands'
 'electronics|mobiles&accessories|smartphones&basicmobiles|smartphones'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers'
 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|EXTERNALHARDDISKS'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop'
 'Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines'
 ' Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'electronics|wearabletechnology|smartwatches'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles'
 'Electronics|Accessories|MemoryCards|MicroSD'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|MICE'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts'
 'Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines'
 'Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums'
 'Computers&Accessories|Accessories&Peripherals|Cabels&Accessories|Cabels|USBCabels'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters'
 'home&kitchen|kitchen&homeappliances|smallkitchenappliances|kettles&hotwaterdispensers|kettle&toastersets'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets'
 'Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters'
 'Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers'
 'Electronics|HomeAudio|Accessories|Adapters'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders'
 'Computers&Accessories|Printers,Inks&Accessories|Printers'
 'OfficeProducts|OfficeElectronics|Calculators|Financial&Business'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers'
 'Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports'
 'Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors'
 ' OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons'
 'Electronics|Mobiles&Accessories|MobileAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers'
 'Computers&Accessories|Accessories&Peripherals|USBHubs'
 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts'
 'Electronics|Mobiles&Accessories|MobileAccessories|StylusPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens'
 'Electronics|HomeTheater,TV&Video|Projectors'
 'Electronics|Headphones,Earbuds&Accessories|Adapters'
 'Computers&Accessories|Monitors'
 'Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies'
 'Computers&Accessories|Components|InternalSolidStateDrives'
 ' Computers&Accessories|NetworkingDevices|Routers'
 ' Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|VideoCameras'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear'
 'electronics|mobiles&accessories|mobileaccessories|chargers|wallchargers'
 'Electronics|HomeTheater,TV&Video|Accessories|3DGlasses'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|PENDRIVES'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|ACCESSORIES|CABLES|HDMICABLES'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|CABLES&ACCESSORIES|CABLES|USBCABLES'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries'
 'MusicalInstruments|Microphones|Condenser'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes'
 'HOME&KITCHEN|HEATING,COOLING&AIRQUALITY|WATERHEATERS&GEYSERS|INSTANTWATERHEATERS'
 'home&kitchen|homestorage&organization|laundryorganization|laundrybaskets'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables '
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums'
 'Home&Kitchen|CraftMaterials|Scrapbooking|Tape'
 'Electronics|PowerAccessories|SurgeProtectors'
 'Computers&Accessories|Accessories&Peripherals|HardDiskBags'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters'
 'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|KEYBOARDS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases'
 'electronics|hometheater,tv&video|accessories|tvmounts,stands&turntables|tvwall&ceilingmounts'
 'Electronics|Headphones,Earbuds&Accessories|Cases'
 'Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'HomeImprovement|Electrical|CordManagement'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets'
 ' Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Electronics|Accessories|MemoryCards|SecureDigitalCards'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits'
 'Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers '
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales'
 'ELECTRONICS|HEADPHONES,EARBUDS&ACCESSORIES|HEADPHONES|IN-EAR'
 ' Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges'
 'Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems'
 'Home&Kitchen|CraftMaterials|PaintingMaterials'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms'
 'OfficeProducts|OfficeElectronics|Calculators|Basic'
 ' Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables '
 'electronics|mobiles&accessories|mobileaccessories|automobileaccessories|cradles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers '
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters'
 'Computers&Accessories|NetworkingDevices|DataCards&Dongles'
 'OfficeProducts|OfficeElectronics|Calculators|Scientific'
 'Electronics|Cameras&Photography|SecurityCameras|DomeCameras'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags'
 'Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales'
 'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases'
 ' Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens'
 'Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits'
 'Electronics|HomeAudio|MediaStreamingDevices|StreamingClients'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|TELEVISIONS|SMARTTELEVISIONS'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders '
 'computers&accessories|networkingdevices'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens'
 ' Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Electronics|HomeAudio|Speakers|SoundbarSpeakers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights'
 'Electronics|Cameras&Photography|Accessories|Film'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories'
 'Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives'
 ' Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners'
 'Electronics|Headphones,Earbuds&Accessories|Earpads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers '
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams'
 'Computers&Accessories|Laptops|TraditionalLaptops'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons '
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps '
 'Computers&Accessories|Components|InternalHardDrives'

In [3615]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

1. Product_id

In [3616]:
df['product_id'].str.contains('B0').sum()

1454

In [3617]:
df['product_id'].shape
df['product_id'].isna().sum()

np.int64(9)

In [3618]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3619]:
df['product_id'] = df['product_id'].str.replace('B0' , '')
df['product_id'] = df['product_id'].str.replace('b0' , '')
df
# df.loc[~df['product_id'].str.startswith('B0' , na= False) ,'product_id']

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3620]:
df.loc[~df['product_id'].str.startswith('B0' , na= False) ,'product_id']

0       8SMJT55F
1       7F6GXNPB
2       8TTRVWKY
3       1MQ2A86A
4       8GM5S4CQ
          ...
1490    756K5DYZ
1491    1LY9W8AF
1492    91JF2TFD
1493    B3JSWG81
1494    0PVT30YI
Name: product_id, Length: 1482, dtype: object

In [3621]:
df['product_id'].isna().sum()
df['product_id'] = df['product_id'].fillna('Unknown')

In [3622]:
df['product_id'].isna().sum()

np.int64(0)

In [3623]:
df['product_id'].duplicated().sum()

np.int64(131)

In [3624]:
df['product_id'] = df['product_id'].str.strip()

2. Product_name

In [3625]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3626]:
df['product_name'].isna().sum()

np.int64(12)

In [3627]:
df['product_name'] = df['product_name'].str.capitalize()

In [3628]:
df[df['product_name'] == df['product_name'].str.upper()]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3629]:
df['product_name'] = df['product_name'].str.strip()

3. Categories
category : 30 missing values, remove extra spaces and standardize category names.

In [3630]:

df['category'].isna().sum()
df[df['category'] == df['category'].str.upper()]
df['category'] = df['category'].str.capitalize()

In [3631]:
df[df['category'] == df['category'].str.upper()].sum()

product_id                0
product_name              0
category                  0
Discounted_Price (INR)    0
actual_price              0
discount_percentage       0
rating                    0
Rating Count              0
about_product             0
user_id                   0
user_name                 0
review_id                 0
review_title              0
review_content            0
IMG_LINK                  0
product_link              0
dtype: object

In [3632]:
df['category'].duplicated().sum()

np.int64(1244)

In [3633]:
df['category'] = df['category'].str.strip()

4 . Discounted price
Discounted_Price (INR) : Remove ₹, Rs., commas and spaces, convert data type to Float, all values should be > 0.

In [3634]:
df

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,Boat stone 250 portable wireless speaker with ...,Electronics|homeaudio|speakers|bluetoothspeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,Eureka forbes euroclean paper vacuum cleaner d...,"home&kitchen|kitchen&homeappliances|vacuum,cle...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,Milton smart egg boiler 360-watts (transparent...,Home&kitchen|kitchen&homeappliances|smallkitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech m331 silent plus wireless mouse, 2.4g...",Computers&accessories|accessories&peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells instanio 10 litre storage water heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige iris 750 watt mixer grinder with 3 st...,Home&kitchen|kitchen&homeappliances|smallkitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello eliza plastic laundry bag/basket, 50 lit...",Home&kitchen|homestorage&organization|laundryo...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult audio bassbuds oak in-ear wired earphone...,"Electronics|headphones,earbuds&accessories|hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,Ngi store 2 pieces pet hair removers for your ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen mart stainless steel south indian filt...,"Home&kitchen|kitchen&homeappliances|coffee,tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3635]:
df['Discounted_Price (INR)'].isnull().sum()
df.loc[~df['Discounted_Price (INR)'].str.contains('₹|Rs|,|\s', na=False), ['Discounted_Price (INR)']]

     Discounted_Price (INR)
3                       NaN
40                      289
54                      299
84                      449
110                     249
...                     ...
1395                    599
1397                   1399
1412                   5799
1436                    115
1463                    599

[62 rows x 1 columns]

In [3636]:
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('₹' , '')
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('Rs. ' , '')
# df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace(',' , '')
df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].str.replace('₹|Rs\. |,', '' , regex=True)
df['Discounted_Price (INR)']

0         1199
1          253
2         1099
3          NaN
4         6990
         ...
1490      3249
1491    998.06
1492       499
1493       199
1494       292
Name: Discounted_Price (INR), Length: 1482, dtype: object

In [3637]:
df['Discounted_Price (INR)'] = pd.to_numeric(df['Discounted_Price (INR)'].str.strip().str.replace('\s+', '', regex=True),errors='coerce')
df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].astype('float')

In [3638]:
df['Discounted_Price (INR)'].dtype

dtype('float64')

In [3639]:
df[df['Discounted_Price (INR)'] < 0]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
365,9L8DSSFH,7seven® compatible for samsung smart 4k ultra ...,"Electronics|hometheater,tv&video|accessories|r...",-399.0,₹999,60%,3.6,493,1. 7SEVEN Compatible remote suitable for all O...,"AH5G2FWQ6AJBXK2IDCA22BNQTT2A,AEEV73PQDYYMSQSW4...","MONTY,Qais Makani,Rajat Shuvra Roy,Amith PJ,Dh...","RVEWH0LAEO3NH,R3E42NTD6HXN1Q,R3IC0VLPIDBPTY,R1...","Overall Good,Works well. Will comment on durab...",Overall replacement of original samsung remote...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/7SEVENTM-Compatible-Repl...
539,1I1LDZGA,Pigeon kessel multipurpose kettle (12173) 1.2 ...,Home&kitchen|kitchen&homeappliances|smallkitch...,-1499.0,"₹1,775",16%,3.9,"14,667",Warranty: 1 year on product|Power: 600 watts ;...,"AE7WYVO3LE7NWMHVORZVUYS55TJQ,AFMN7VI5JFZCWKPLS...","Jyoti Dwivedi,Malav,Amazon Customer,Seema,Sun....","R3SMQ18FRX81ZM,RM8D6XNWRSKRD,R20K0WT99IF7SW,R2...","Nice product,Best for hostel guys,Easy to hand...","Go for it .... Nice product,I loved the produc...",https://m.media-amazon.com/images/I/41orhoQwtG...,https://www.amazon.in/Pigeon-Kessel-1-2-Litre-...
947,8CTNJ985,Wayona usb type c 65w fast charging 2m/6ft lon...,Computers&accessories|accessories&peripherals|...,-325.0,₹999,67%,4.3,"2,651",~ QC3.0 FAST CHARGING & DATA SYNC : This 2mete...,"AFVNMGQ2XHQL55BFESLIHGPCW6LA,AFRUZM3EU3T6M7HFW...","Soumya R.,sivaramakrishnan c,shradha nair,Moha...","R1LNA5SHXIW7IM,RGCS38FNYUI9H,R2WOUJZTB4QW94,R3...","Worth the money spent,Nice product also the st...",Cable is long and durable. Its worth the purch...,https://m.media-amazon.com/images/I/416qO6VZHg...,https://www.amazon.in/Wayona-Charging-Charger-...
1088,8CYNJ5KY,Hp 682 black original ink cartridge,"Computers&accessories|printers,inks&accessorie...",-828.0,₹861,4%,4.2,"4,567",Page yield-480|Compatible with HP Deskjet plus...,"AHCS34T4DOHWPNKZ2G3W76AITIKA,AGEMHG7WVU23NHOM3...","Hrishikesh,Mir Manzoor,Hanumathkumar,Amazon Cu...","R3C592OSGL2F93,R1E0XZJHFH6TXM,R2ENRB8YO7Y4S1,R...","On average is ok ok pricing,Good,Quality good....",A lot of people rate this product low as there...,https://m.media-amazon.com/images/I/4152kKO7W8...,https://www.amazon.in/682-Black-Original-Ink-C...
1133,9474JWN6,Healthsense rechargeable lint remover for clot...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",-999.0,"₹1,500",33,4.2,386,RECHARGEABLE CORDLESS: Long lasting multiple U...,"AFXT4M4YZCGYWUG22BMXEOB7VUOA,AEZWBVOWAZGCLKUNZ...","GB SLG,Jemin,Ashwini Vetekar,Kusum,sonu ali,Am...","RVV3VEBYM65XS,R25CPGMH2YOEGC,RL1N0IR94UURO,RJD...","👍 nice,Lint removed instantly and effortlessly...","Like,Loved the product alot. After cleaning of...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/HealthSense-New-Feel-Rec...
1213,9DSQXCM8,House of quirk reusable sticky picker cleaner ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",-299.0,₹499,40%,3.9,"1,015","Quickly removes lint, dust, dandruff and pet h...","AHEE4KV3RGGHWUXGCNXJ4DMKM53A,AGEUYT4DWSJF64CD5...","ANILKUMAR,Sudeep Jain,siri srujana,Dipankar Pa...","R2XK30UZ0P7UXJ,R3NQKJO364XETX,R1CYYHWHYX2NX1,R...","Good to use,Really good in this price,Lint rol...","Good to use,Really good product in this price ...",https://m.media-amazon.com/images/I/31t6ATbG1j...,https://www.amazon.in/House-Quirk-Reusable-Eas...
1313,123P3PWE,Rico irpro 1500 watt japanese technology elect...,"Home&kitchen|heating,cooling&airquality|waterh...",-999.0,"₹1,075",7%,4.1,"9,275",High Class Premium No 1 Quality compare to any...,"AGB3FQ7523INWDNY3MAHJWA5ZGIQ,AFOLHTLOEWQQPINOV...","MANEESH Jaggari,Vishal dhan,K. Chandrababu,md ...","R2700E7W1TZOD3,RJYAUT0FRKDMB,RL8FH0EY6MYW2,R3L...","Excellent to Use, Adequate Cord length but Too...",1) Cord Length could be increased little more ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Rico-1500-W-immersion-wa...
1325,B19VJXQZ,Ecovacs deebot n8 2-in-1 robotic vacuum cleane...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",-27900.0,"₹59,900",53%,4.4,"5,298",FREE HOME INSTALLATION & FREE HOME SERVICE: We...,"AFDTW4TES6JHT7YJUXKDFQJPRZXQ,AFEBFFAOMPMC6L3DM...","Jaydeep,Jayakrishnan R","R1BD0HURZRIGKV,RKQY8Y6U3Y4BT","A perfect balance of price and performance,Gre...",Very happy with the product performance.Instal...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/ECOVACS-Robotic-Powerful...

In [3640]:
df.loc[df['Discounted_Price (INR)'] <= 0] = np.nan
df['Discounted_Price (INR)'] = df['Discounted_Price (INR)'].fillna(df['Discounted_Price (INR)'].median())

In [3641]:
df['Discounted_Price (INR)'].head()
df['Discounted_Price (INR)'].isna().sum()

np.int64(0)

5 . Actual_price : 
actual_price : Remove ₹ and commas, convert data type to Float, all values should be > 0 and greater than or equal to Discounted Price.

In [3642]:
df['actual_price']

0        ₹3,990
1          ₹500
2        ₹1,899
3        ₹1,645
4       ₹14,290
         ...
1490     ₹6,295
1491     ₹1,282
1492     ₹1,299
1493       ₹999
1494       ₹499
Name: actual_price, Length: 1482, dtype: object

In [3643]:
df['actual_price'] = df['actual_price'].str.replace('₹|,|Rs.','' , regex = True,)
df.loc[~df['actual_price'].str.contains('₹|,|Rs. ',regex=True, na=False),['actual_price']]

     actual_price
0            3990
1             500
2            1899
3            1645
4           14290
...           ...
1490         6295
1491         1282
1492         1299
1493          999
1494          499

[1482 rows x 1 columns]

In [3644]:
df['actual_price']

0        3990
1         500
2        1899
3        1645
4       14290
        ...
1490     6295
1491     1282
1492     1299
1493      999
1494      499
Name: actual_price, Length: 1482, dtype: object

In [3645]:
df['actual_price'] = df['actual_price'].astype('float')

In [3646]:
df.loc[~(df['actual_price'].abs() >= df['Discounted_Price (INR)'])]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,94JB13XL,"Noise colorfit ultra smart watch with 1.75"" hd...",Electronics|wearabletechnology|smartwatches,2499.0,NaN,58%,4.1,"38,879","1.75” TruViewTM display: See the clear, bigger...","AEZH7UN4SKV7VKJ3NYH7D7CBHA4A,AEEMDECLMB6ZOYW4M...","shiv,Pankaj Bhatt,Dipanshu Kr Biswas,Jeet Jang...","R1JO87DOGUEQHC,R1UQ0AYNB30CZS,R34O4E591I5RJN,R...","Budget friendly watch,Good product at this pri...","I liked the watch, the battery of this watch i...",https://m.media-amazon.com/images/I/41YBVJ+UTx...,https://www.amazon.in/Noise-ColorFit-Bezel-Les...
329,Unknown,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,83342NKJ,Mi braided usb type-c cable for charging adapt...,Computers&accessories|accessories&peripherals|...,349.0,0.0,13%,4.4,"18,757",1M Long Cable. Usb 2.0 (Type A)|Toughened Join...,"AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PT...","Birendra ku Dash,Aditya Gupta,Abdulla A N,Deep...","R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1...","Good product,using this product 8months It is ...","I like it 👍👍,Best charging power . I used this...",https://m.media-amazon.com/images/I/31gaP7qpBN...,https://www.amazon.in/Mi-Braided-USB-Type-C-Ca...
365,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,0LOD70SC,Pilot v7 liquid ink roller ball pen (2 blue + ...,Officeproducts|officepaperproducts|paper|stati...,799.0,210.0,15%,4.3,"2,450",Unique 3 dimple tip technology from Japan for ...,"AG3G7G2DUJKN5YMCOYZNCADKKJUQ,AH44B2X6AT45J37MH...","Madhusmita singh,Sandeep Singh,Jay OG,Asim,Vik...","R1AY8EXPHPWDDR,R24503W0UJGTMU,R27P97SD5T4MUX,R...","It's good,Good,One of the few items on amazon ...",Everything is fine but it's bit dark and stick...,https://m.media-amazon.com/images/I/31pJvN8OkS...,https://www.amazon.in/Pilot-Liquid-Roller-Ball...
401,8VS3YLRK,Portronics adapto 20 type c 20w fast pd/type c...,Electronics|mobiles&accessories|mobileaccessor...,529.0,NaN,65%,4.1,"8,599",[20W HIGH-SPEED CHARGING] : The Adapto 20 is a...,"AE5X7F5K6HASKKQZGUJEF3VZFRRQ,AEKVSWRDHUU76ES43...","pawhnai,Santosh Kumar,Dhruv Shah,Rajeev K.,Dev...","RLCW4ACH6TGM7,RS7QQ6IPVH0ZK,R1DN62U7XKE8ZR,R2O...","Durability,Best one,Quality Product,Trustworth...",Good charging speed as expected but heat up fa...,https://m.media-amazon.com/images/I/31wqydqbA9...,https://www.amazon.in/Portronics-Adapto-Adapte...
419,994GFWBH,Lapster 1.5 mtr usb 2.0 type a male to usb a m...,Computers&accessories|accessories&peripherals|...,139.0,NaN,86%,4.0,"1,313",Plug & Play|Stable & Reliable Connectivity.|Sp...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","pruthvi natraj,Phani,Amazon Customer,TechDevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/I/310WOJIrwj...,https://www.amazon.in/Lapster-Type-Cable-compu...
539,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,B5CGTBKV,"Boat wave call smart watch, smart talk with ad...",NaN,1999.0,NaN,75%,3.8,"17,833",Bluetooth Calling- Wave Call comes with a prem...,"AHPYDFW6Y3FIQGD2RJPBFF5QNVRQ,AG7DTVYZDY2NWU6V2...","AV,Mathan kumar,Amol Manjrekar,Suraj_nirmalkar...","R3EKLFGQGV02SG,R23WEMNZK46UV3,R1G2C7XV8CAM7W,R...","Not Polished Enough. (Improving with updates),...",[Update: Sept 29] boAt seems to have heard the...,https://m.media-amazon.com/images/I/4141l8ZBWX...,https://www.amazon.in/boAt-Wave-Call-Dedicated...
583,7YL54NVJ,"Brand conquer 6 in 1 with otg, sd card reader,...",Computers&accessories|externaldevices&datastor...,549.0,0.0,45,4.3,"7,758",More connectivity: Equipped with USB 3.0 Type ...,"AHFX3A6IT3PFKH3WJU3BRCMOAOIA,AE57P6GZXORH2I7GE...","SRI RAGAV,Sachin R.,Ritvik,Ebbie Thomas,Siva k...","R2WYKIWLGH956S,RK46ZE8SQLQTZ,R2K7BE9W9WKQ8R,R1...","Worth Buying,It's a very good product at these...",I'm really liked the product more than expecte...,https://m.media-amazon.com/images/I/31R4HANvX2...,https://www.amazon.in/Brand-Conquer-Reader-Ada...
704,9NL4DCXK,Flix (beetel) bolt 2.4 12w dual usb smart char...,Electronics|mobiles&accessories|mobileaccessor...,799.0,599.0,58%,3.9,"2,147","With The Intelligent Chip Inside, Dual Usb Wal...","AGNJW4JB3SQZZEVJCOR6EXOTNMOQ,AFTBDE5KEINLXCQI2...","Bristidev Burman,P VENKATESH,D.Dutta,Swapnil P...","R2XF84DPH68G5Y,R272LVPQ9OGM0S,RBQF76FUWS8PH,RU...","good till now,Good,An additional charger same ...",i use it for powering my bluetooth speaker and...,https://m.media-amazon.com/images/I/31efS1bi1v...,https://www.amazon.in/Charger-Certified-Chargi...
753,75ZTJ9XR,Amazonbasics high-speed braided hdmi cable - 3...,"Electronics|hometheater,tv&video|accessories|c...",269.0,0.0,59%,4.4,"35,877",Nylon-braided HDMI cable (A Male to A Male): s...,"AEWC3QIWDPNHJSLVO6MS62ERGB3Q,AGHUOIOWEX6YXURWD...","SUSHANT,SANJEEV,R. chatterjee,P.Krishna,Avi Ra...","R3V4QKSGSKWY6Z,R2YVK4E6L5KZUB,R1CFPUFKST9QUV,R...","Satisfactory,Superb88,Good hdmi cable for 1080...","Good,Good quality product,Affordable hdmi cabl...",m.media-amazon.com/images/I/41SxrTzMivL._SX300...,https://www.amazon.in/AmazonBasics-Braided-HDM...
761,B5ZF3NRK,"Cedo 65w oneplus dash warp charge cable, usb a...",Computers&accessories|accessories&peripherals|...,349.0,NaN,42%,4.1,210,FAST AND STABLE CHARGING: Flexible USB type c ...,"AGE6O2NLNA3NUGORPU4SDK2S23QQ,AEXZDEFVFQ3LW6DKH...","Satyanarayana,mohd irfan,Pankaj,Shirish Shivar...","R27HJ954EMEOQK,R2EPGPZGPWXR4I,R1KUXERHI948E7,R...","Good.,Good product,Ultimate product,Good Produ...",Working well and fast Charing as claimed. Pice...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/CEDO-OnePlus-Charging-Co...
809,6XR9PR5X,"Amazon basics hdmi coupler,black",Electronics|homeaudio|accessories|adapters,209.0,NaN,65%,4.4,"18,872",Note: Product only works as an extender adapte...,"AESNQRQGPFRFF3MIKZ6HWY3Z5XPQ,AGPYTMWCOQQUTOWXL...","Bharanidharan,Roshan k jose,fabeel,RS,Jasper,A...","R1PU0LE5YRKY3Y,R2L5EHOA77MWQP,R1GOM8MCTLY767,R...","Good Quality Product,Good Product,Good,Perfect...","Working as expected,Good product, Perfectly wo...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/AmazonBasics-AZHDAD01-HD...
832,7Y1RCCW5,Zigma winotek winotek sun instant water geyser...,NaN,1190.0,NaN,53%,-1,"1,181",NOTE- In this order you will receive10 geysers...,"AGLUPY33OM375F64CHDCQW3KF64Q,AHL6DKFWYVLNGVHHQ...","Aashishnautiyal,Telangana venkatesh,Abbas Tiru...","R1O343U978W7T3,RTT7TYSICUSK7,RNJ28HCJAVS7P,R65...","Water heating not good as per standard,నాకు ప్...","Na,గ్యారంటీ,Good use for getting instant heat ...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/WinoteK-Instant-Portable...
871,1M69WCZ6,Allin exporters j66 ultrasonic humidifier cool...,NaN,2249.0,NaN,37%,4,"3,973",Improve air condition: this cool mist ultrason...,"AEJS5FT3PUYMZ27UQBFICD2YXDQA,AFFHWVYKVSRM37YO4...","Anshuk Pani,Sujit,Neeraj,M Sajan,Gabs,Kishore ...","R3JY7DEIB727Q4,RERB22NNP18BZ,RE6LIDZ65EW5G,R1Y...","So far so good,Good product.,good quality prod...","Apart from it leaving a watermark on table, it...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Allin-Exporters-Ultrason...
947,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,0ZRBWPA0,Eveready red 1012 aaa batteries - pack of 10,Electronics|generalpurposebatteries&batterycha...,799.0,180.0,12%,4.3,989,Think Battery - Think Eveready - Eveready Red ...,"AGY65IJP7XREWO3GUDT46474CYKA,AGU43SQ6PXZIL5F5R...","Amazon Customer,Cijo George,Mallikarjuna Ukkad...","R1VCGAPSS4LWYQ,R3DS8EL4VV5LS6,R28MH1Y6O92EOP,R...","Nice .,very good batteries received,Longtevity...","Nive,very good batteries received,Like,Good pr...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eveready-Alkaline-Batter...
1020,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1079,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1088,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1125,B2CWRDB1,Shakti technology s5 high pressure car washer ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",5999.0,NaN,40%,4.2,170,"Power:1900W, Pressure:125 Bar, Flowing:10L/min...","AFS6NM2UFY5M77EWX5YT2KBMWBVQ,AEBC5L4UVUOB45BUS...","Ravinder kumar,Ashok,tejas,seema,HARSHVARDHAN,...","RWSKUEMV0AS0P,R2YZOJVWTFMYAH,R17E9QT7OVVJVX,R3...","It is very good,Good product,Just go for it,Go...","Product works very well, easy to use i recomme...",https://m.media-amazon.com/images/I/51RQbF6ZuL...,https://www.amazon.in/Shakti-Technology-S5-Pre...
1130,86Q3QMFS,"Classmate drawing book - unruled, 40 pages, 21...",Officeproducts|officepaperproducts|paper|stati...,799.0,NaN,0%,4.5,"4,951",The cover design of the notebook is subject to...,"AENWPLS2BHDMH4O6DD7EYV5DOGHQ,AGWEZX7ZMZNEDPVTP...","a.john,Sonika sharma,Umadevi,tarun,venkatesh k...","RSVV6T480YK7W,R22DHM4LC4189N,RS51GZQV4URIF,R3K...","Good product for beginners,Wonderful,Good,Rate...",Good for learning drawing for kids. MRP of pro...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Drawing-Book-U...
1133,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1146,B9LDCX89,Striff mpad mouse mat 230x190x3mm gaming mouse...,Computers&accessories|accessories&peripherals|...,129.0,NaN,87%,4.2,491,9.4 Inches X 7.9 Inches) 240mm x 200mm x 2mm S...,"AGASWLGAJEYSNHPWSR74GSDXU5JQ,AGFT22PQSW5ZDJLFL...","muhamad s.,Aruna V,Ankush Jindal,SJ,Ronak,Deve...","R3ET8JTEIDTNU0,R1FAH4M3BSL55F,R3I8GGSZJCEUGV,R...","Decent quality,Good for the price,Value buy,It...",Mousepad is sturdy enough doesn't move around ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/STRIFF-230X190X3mm-Water...
1187,747VDH9L,"Inalsa hand blender 1000 watt with chopper, wh...",Home&kitchen|kitchen&homeappliances|smallkitch...,2742.0,0.0,31%,4.4,"11,148","HANDHELD BLENDING POWER-> With power of 1000W,...","AF7QK5FHWPIIYYCVERDUJEZYTSXQ,AERRAASKR2QOMQ2YN...","Angel👼,Neha Faizee,Amazon Customer,vipin v.,Ka...","RF9Y5B4XM5YZ6,R24N6TZUI4NUAR,RMMHFQPA8C5FJ,RTE...","Heats up,I just bought this product and my rev...",It's very easy to use. And easy to clean. It d...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Inalsa-Robot-1000-800-Wa...
1213,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231,8PV1X771,Samsung 80 cm (32 inches) wondertainment serie...,"Electronics|hometheater,tv&video|televisions|s...",15490.0,0.0,26%,4.3,"16,299",Resolution: HD Ready (1366x768) | Refresh Rate...,"AHEVO4Q5NM4YXMG2HDDXC5XMBGRQ,AFZPH7ZAWX5VDY3HO...","Rahman Ali,MARIYA DASS,Md Aftab,roshan s.,Moha...","R1SN0D4DFBKAZI,R1SX5L77L2CD6V,R1NAZ6M4QBUJMK,R...","Good,Sound is very low another brand comparing...","Overall good.,TV picture ok smart betterSound ...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Samsung-inches-Wondertai...
1237,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1239,97XJQZ8H,"Cookwell bullet mixer grinder (5 jars, 3 blade...",Home&kitchen|kitchen&homeappliances|smallkitch...,2464.0,NaN,59%,4.1,"8,866",Compact and consumes less space as compared to...,"AFJVAVYH2K6VUCTNLA5HZ45VQFKA,AGGWXZI3DYEKKDM4B...","gowtham saran,Nanu prinu,Roopali tiwari,Vipul ...","R2CCAIITXBUWWK,R34WQMRY9WM6SZ,RMO1CT02OKUNJ,R2...","Worth for money and best customer service.,Goo...",We ordered this product after many research an...,https://m.media-amazon.com/images/I/41nBjnlp-M...,www.amazon.in/Cookwell-Bullet-Mixer-Grinder-Si...
1243,BBLHTRM9,Ionix tap filter multilayer | activated carbon...,Home&kitchen|kitchen&homeappliances|waterpurif...,199.0,NaN,72%,2.9,159,Faucet Water Filter: Built-in layered filter c...,"AF6LRVDRKYWPTZXZLQERZ3LXCWDA,AG7FU75LA5ONPMNEV...","Anmol Khanna,G.l.sudhakar,Amazon Customer,mano...","R9GL8284FSYUG,R1Q6Z3DZDJMDPN,R25CLTZM7X33KC,R3...","Stop working after few days,Ok. Changing every...","Stop working after few days,Ok,It doesn't fit ...",https://m.media-amazon.com/images/I/41n90w1dlJ...,https://www.amazon.in/IONIX-Tap-Multilayer-Fil...
1256,B59K1C8F,Wolpin 1 lint roller with 60 sheets remove clo...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",179.0,NaN,78%,3.6,101,Strong Adhesion: Wolpin lint roller is a very ...,"AHWLTHKYKXVQESLJVESM5URXROEA,AFEFEZTZWJLYZGIVR...","Vineeth,Gunjan garg,Gemini,Aleena Antony,Anim...","R2XFD3J4A5TGZF,RX5FGOO2VEM95,R1TUD04IXLDRMV,R1...","Not so Worth it,It is only for one use so as p...","Average product,As per use its costly,This pro...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wolpin-Roller-Sheets-Rem...
1313,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1325,NaN,NaN,NaN,799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3647]:
df.loc[df['actual_price'] <= 0] = np.nan

In [3648]:
df['actual_price'] = df['actual_price'].fillna(df['actual_price'].median())

In [3649]:
df['actual_price'].dtype

dtype('float64')

In [3650]:
df.loc[~(df['actual_price'].abs() >= df['Discounted_Price (INR)'])]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
100,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,94JB13XL,"Noise colorfit ultra smart watch with 1.75"" hd...",Electronics|wearabletechnology|smartwatches,2499.0,1650.0,58%,4.1,"38,879","1.75” TruViewTM display: See the clear, bigger...","AEZH7UN4SKV7VKJ3NYH7D7CBHA4A,AEEMDECLMB6ZOYW4M...","shiv,Pankaj Bhatt,Dipanshu Kr Biswas,Jeet Jang...","R1JO87DOGUEQHC,R1UQ0AYNB30CZS,R34O4E591I5RJN,R...","Budget friendly watch,Good product at this pri...","I liked the watch, the battery of this watch i...",https://m.media-amazon.com/images/I/41YBVJ+UTx...,https://www.amazon.in/Noise-ColorFit-Bezel-Les...
331,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,0LOD70SC,Pilot v7 liquid ink roller ball pen (2 blue + ...,Officeproducts|officepaperproducts|paper|stati...,799.0,210.0,15%,4.3,"2,450",Unique 3 dimple tip technology from Japan for ...,"AG3G7G2DUJKN5YMCOYZNCADKKJUQ,AH44B2X6AT45J37MH...","Madhusmita singh,Sandeep Singh,Jay OG,Asim,Vik...","R1AY8EXPHPWDDR,R24503W0UJGTMU,R27P97SD5T4MUX,R...","It's good,Good,One of the few items on amazon ...",Everything is fine but it's bit dark and stick...,https://m.media-amazon.com/images/I/31pJvN8OkS...,https://www.amazon.in/Pilot-Liquid-Roller-Ball...
543,B5CGTBKV,"Boat wave call smart watch, smart talk with ad...",NaN,1999.0,1650.0,75%,3.8,"17,833",Bluetooth Calling- Wave Call comes with a prem...,"AHPYDFW6Y3FIQGD2RJPBFF5QNVRQ,AG7DTVYZDY2NWU6V2...","AV,Mathan kumar,Amol Manjrekar,Suraj_nirmalkar...","R3EKLFGQGV02SG,R23WEMNZK46UV3,R1G2C7XV8CAM7W,R...","Not Polished Enough. (Improving with updates),...",[Update: Sept 29] boAt seems to have heard the...,https://m.media-amazon.com/images/I/4141l8ZBWX...,https://www.amazon.in/boAt-Wave-Call-Dedicated...
583,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
704,9NL4DCXK,Flix (beetel) bolt 2.4 12w dual usb smart char...,Electronics|mobiles&accessories|mobileaccessor...,799.0,599.0,58%,3.9,"2,147","With The Intelligent Chip Inside, Dual Usb Wal...","AGNJW4JB3SQZZEVJCOR6EXOTNMOQ,AFTBDE5KEINLXCQI2...","Bristidev Burman,P VENKATESH,D.Dutta,Swapnil P...","R2XF84DPH68G5Y,R272LVPQ9OGM0S,RBQF76FUWS8PH,RU...","good till now,Good,An additional charger same ...",i use it for powering my bluetooth speaker and...,https://m.media-amazon.com/images/I/31efS1bi1v...,https://www.amazon.in/Charger-Certified-Chargi...
753,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,1M69WCZ6,Allin exporters j66 ultrasonic humidifier cool...,NaN,2249.0,1650.0,37%,4,"3,973",Improve air condition: this cool mist ultrason...,"AEJS5FT3PUYMZ27UQBFICD2YXDQA,AFFHWVYKVSRM37YO4...","Anshuk Pani,Sujit,Neeraj,M Sajan,Gabs,Kishore ...","R3JY7DEIB727Q4,RERB22NNP18BZ,RE6LIDZ65EW5G,R1Y...","So far so good,Good product.,good quality prod...","Apart from it leaving a watermark on table, it...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Allin-Exporters-Ultrason...
893,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,0ZRBWPA0,Eveready red 1012 aaa batteries - pack of 10,Electronics|generalpurposebatteries&batterycha...,799.0,180.0,12%,4.3,989,Think Battery - Think Eveready - Eveready Red ...,"AGY65IJP7XREWO3GUDT46474CYKA,AGU43SQ6PXZIL5F5R...","Amazon Customer,Cijo George,Mallikarjuna Ukkad...","R1VCGAPSS4LWYQ,R3DS8EL4VV5LS6,R28MH1Y6O92EOP,R...","Nice .,very good batteries received,Longtevity...","Nive,very good batteries received,Like,Good pr...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eveready-Alkaline-Batter...
1046,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1125,B2CWRDB1,Shakti technology s5 high pressure car washer ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",5999.0,1650.0,40%,4.2,170,"Power:1900W, Pressure:125 Bar, Flowing:10L/min...","AFS6NM2UFY5M77EWX5YT2KBMWBVQ,AEBC5L4UVUOB45BUS...","Ravinder kumar,Ashok,tejas,seema,HARSHVARDHAN,...","RWSKUEMV0AS0P,R2YZOJVWTFMYAH,R17E9QT7OVVJVX,R3...","It is very good,Good product,Just go for it,Go...","Product works very well, easy to use i recomme...",https://m.media-amazon.com/images/I/51RQbF6ZuL...,https://www.amazon.in/Shakti-Technology-S5-Pre...
1187,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1239,97XJQZ8H,"Cookwell bullet mixer grinder (5 jars, 3 blade...",Home&kitchen|kitchen&homeappliances|smallkitch...,2464.0,1650.0,59%,4.1,"8,866",Compact and consumes less space as compared to...,"AFJVAVYH2K6VUCTNLA5HZ45VQFKA,AGGWXZI3DYEKKDM4B...","gowtham saran,Nanu prinu,Roopali tiwari,Vipul ...","R2CCAIITXBUWWK,R34WQMRY9WM6SZ,RMO1CT02OKUNJ,R2...","Worth for money and best customer service.,Goo...",We ordered this product after many research an...,https://m.media-amazon.com/images/I/41nBjnlp-M...,www.amazon.in/Cookwell-Bullet-Mixer-Grinder-Si...
1309,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1335,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1361,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1448,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3651]:
df['Discounted_Price (INR)'].isna().sum()

np.int64(13)

In [3652]:
df.duplicated().sum()
df = df.drop_duplicates()

In [3653]:
df.loc[~(df['actual_price'].abs() >= df['Discounted_Price (INR)'])]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
100,NaN,NaN,NaN,NaN,1650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,94JB13XL,"Noise colorfit ultra smart watch with 1.75"" hd...",Electronics|wearabletechnology|smartwatches,2499.0,1650.0,58%,4.1,"38,879","1.75” TruViewTM display: See the clear, bigger...","AEZH7UN4SKV7VKJ3NYH7D7CBHA4A,AEEMDECLMB6ZOYW4M...","shiv,Pankaj Bhatt,Dipanshu Kr Biswas,Jeet Jang...","R1JO87DOGUEQHC,R1UQ0AYNB30CZS,R34O4E591I5RJN,R...","Budget friendly watch,Good product at this pri...","I liked the watch, the battery of this watch i...",https://m.media-amazon.com/images/I/41YBVJ+UTx...,https://www.amazon.in/Noise-ColorFit-Bezel-Les...
396,0LOD70SC,Pilot v7 liquid ink roller ball pen (2 blue + ...,Officeproducts|officepaperproducts|paper|stati...,799.0,210.0,15%,4.3,"2,450",Unique 3 dimple tip technology from Japan for ...,"AG3G7G2DUJKN5YMCOYZNCADKKJUQ,AH44B2X6AT45J37MH...","Madhusmita singh,Sandeep Singh,Jay OG,Asim,Vik...","R1AY8EXPHPWDDR,R24503W0UJGTMU,R27P97SD5T4MUX,R...","It's good,Good,One of the few items on amazon ...",Everything is fine but it's bit dark and stick...,https://m.media-amazon.com/images/I/31pJvN8OkS...,https://www.amazon.in/Pilot-Liquid-Roller-Ball...
543,B5CGTBKV,"Boat wave call smart watch, smart talk with ad...",NaN,1999.0,1650.0,75%,3.8,"17,833",Bluetooth Calling- Wave Call comes with a prem...,"AHPYDFW6Y3FIQGD2RJPBFF5QNVRQ,AG7DTVYZDY2NWU6V2...","AV,Mathan kumar,Amol Manjrekar,Suraj_nirmalkar...","R3EKLFGQGV02SG,R23WEMNZK46UV3,R1G2C7XV8CAM7W,R...","Not Polished Enough. (Improving with updates),...",[Update: Sept 29] boAt seems to have heard the...,https://m.media-amazon.com/images/I/4141l8ZBWX...,https://www.amazon.in/boAt-Wave-Call-Dedicated...
704,9NL4DCXK,Flix (beetel) bolt 2.4 12w dual usb smart char...,Electronics|mobiles&accessories|mobileaccessor...,799.0,599.0,58%,3.9,"2,147","With The Intelligent Chip Inside, Dual Usb Wal...","AGNJW4JB3SQZZEVJCOR6EXOTNMOQ,AFTBDE5KEINLXCQI2...","Bristidev Burman,P VENKATESH,D.Dutta,Swapnil P...","R2XF84DPH68G5Y,R272LVPQ9OGM0S,RBQF76FUWS8PH,RU...","good till now,Good,An additional charger same ...",i use it for powering my bluetooth speaker and...,https://m.media-amazon.com/images/I/31efS1bi1v...,https://www.amazon.in/Charger-Certified-Chargi...
871,1M69WCZ6,Allin exporters j66 ultrasonic humidifier cool...,NaN,2249.0,1650.0,37%,4,"3,973",Improve air condition: this cool mist ultrason...,"AEJS5FT3PUYMZ27UQBFICD2YXDQA,AFFHWVYKVSRM37YO4...","Anshuk Pani,Sujit,Neeraj,M Sajan,Gabs,Kishore ...","R3JY7DEIB727Q4,RERB22NNP18BZ,RE6LIDZ65EW5G,R1Y...","So far so good,Good product.,good quality prod...","Apart from it leaving a watermark on table, it...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Allin-Exporters-Ultrason...
957,0ZRBWPA0,Eveready red 1012 aaa batteries - pack of 10,Electronics|generalpurposebatteries&batterycha...,799.0,180.0,12%,4.3,989,Think Battery - Think Eveready - Eveready Red ...,"AGY65IJP7XREWO3GUDT46474CYKA,AGU43SQ6PXZIL5F5R...","Amazon Customer,Cijo George,Mallikarjuna Ukkad...","R1VCGAPSS4LWYQ,R3DS8EL4VV5LS6,R28MH1Y6O92EOP,R...","Nice .,very good batteries received,Longtevity...","Nive,very good batteries received,Like,Good pr...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eveready-Alkaline-Batter...
1125,B2CWRDB1,Shakti technology s5 high pressure car washer ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",5999.0,1650.0,40%,4.2,170,"Power:1900W, Pressure:125 Bar, Flowing:10L/min...","AFS6NM2UFY5M77EWX5YT2KBMWBVQ,AEBC5L4UVUOB45BUS...","Ravinder kumar,Ashok,tejas,seema,HARSHVARDHAN,...","RWSKUEMV0AS0P,R2YZOJVWTFMYAH,R17E9QT7OVVJVX,R3...","It is very good,Good product,Just go for it,Go...","Product works very well, easy to use i recomme...",https://m.media-amazon.com/images/I/51RQbF6ZuL...,https://www.amazon.in/Shakti-Technology-S5-Pre...
1239,97XJQZ8H,"Cookwell bullet mixer grinder (5 jars, 3 blade...",Home&kitchen|kitchen&homeappliances|smallkitch...,2464.0,1650.0,59%,4.1,"8,866",Compact and consumes less space as compared to...,"AFJVAVYH2K6VUCTNLA5HZ45VQFKA,AGGWXZI3DYEKKDM4B...","gowtham saran,Nanu prinu,Roopali tiwari,Vipul ...","R2CCAIITXBUWWK,R34WQMRY9WM6SZ,RMO1CT02OKUNJ,R2...","Worth for money and best customer service.,Goo...",We ordered this product after many research an...,https://m.media-amazon.com/images/I/41nBjnlp-M...,www.amazon.in/Cookwell-Bullet-Mixer-Grinder-Si...


discount_percentage : Remove % symbol, convert data type to Float, all values should be > 0 and < 100.

In [3654]:
df[~df['discount_percentage'].str.contains('%' , regex=True , na=False)]
df['discount_percentage'] = df['discount_percentage'].str.replace('%','',)
df['discount_percentage'] = df['discount_percentage'].astype('float')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1704742589.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_percentage'] = df['discount_percentage'].str.replace('%','',)
/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1704742589.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_percentage'] = df['discount_percentage'].astype('float')

In [3655]:
df['discount_percentage'].dtype

dtype('float64')

In [3656]:
df.loc[df['discount_percentage'] <= 0]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
33,0URH5E34,Inventis 5v 1.2w portable flexible usb led lig...,Computers&accessories|accessories&peripherals|...,39.0,39.0,0.0,3.6,"13,572",The side the LED light falls on will depend on...,"AGA4V2SLJ744MITK2FWWGPXOFB7A,AHDOHVS266NLKERWU...","Dhruv Sharma,Durairaj B,Ved Katyayan,Shailendr...","R1NAJ7CT76Z9SF,R17L9205IYOD,R2GAKH6NBQPCFV,R12...","it worked properly for almost one year,ok,USB ...","very good product, very bright, easy to use, i...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Inventis-Portable-Flexib...
57,7VV37FT4,Classmate octane neon- 25 blue gel pens | smoo...,Officeproducts|officepaperproducts|paper|stati...,250.0,250.0,0.0,4.2,"2,628",5 vibrant Neon body color|Smooth and fast writ...,"AFE7R5FCWMXW42O5UTZ7YEAWGF7A,AHZMXBBTAGNP5FSXC...","Karthick KJV,Ruchi,Amazon Customer,Harishankar...","R199HA6OB5QGOH,R2EXF5TBUFMEKO,R138UM3OBL4EGD,R...","Good product,Best gel pens,👍👍👍,Decent,Feels ch...",Impression of the pen were good... Handling gr...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Octane-Pen-Neo...
62,71vnhmx2,Philips daily collection hd2582/00 830-watt 2-...,Home&kitchen|kitchen&homeappliances|smallkitch...,2095.0,2095.0,0.0,4.5,"7,949",NaN,"AHX5COLYUD4DO3WUMFCOQ47NPJFQ,AFZZF7APWEI5WIVAL...","Joydeep Bhattacharjee,Harsha,Arun,Monotosh Sah...","R18OC1M5ERXJ0,R2VDUDAU7MGHVM,RVLRZGC6D01FK,R1Z...","Good toaster,Seamless. Undoubtedly the best,Go...",Works as said. Browns bread evenly. Pop up wor...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Philips-Collection-HD258...
71,B4PPD89B,Kitchenwell 18pc plastic food snack bag pouch ...,Home&kitchen|kitchen&homeappliances|smallkitch...,79.0,79.0,0.0,4,97,Made in India !|Perfect for tightly sealing an...,"AHO6AWGPNKTSTMNPWGZB4WHA2U2Q,AHVONN4NTBA3GJ36P...","Naitik Parekh,Nerthi,RDP,Anu Chandra,HHJB,KANI...","R2YLDT44YPDA2G,R39360RU5VF8V5,R17JJCUW7LT3JK,R...","Good clips.,Second quality,Value for money.,No...",I bought it for ₹79. Don't think that because ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Kitchenwell-Plastic-Keep...
94,B3CPQ5PF,"Oneplus nord 2t 5g (jade fog, 8gb ram, 128gb s...",Electronics|mobiles&accessories|smartphones&ba...,28999.0,28999.0,0.0,4.3,17.4K,Camera: 50MP Main Camera with Sony IMX766 and ...,"AEREO7C5GLYYYV6YXK7X4UCCQTJQ,AHWISRUJUCJG6UH4F...","ASR,Amazon user,Rama Rao,Vinay,ANIKET,NAGA SHA...","R128LZ0DN2NZBZ,R3LFQ7EDHZ6DKM,RUSJFUV64DPWM,RH...","Really a Good Buy in this price range in 2022,...",Verdict : A Solid buy for this price segment i...,https://m.media-amazon.com/images/I/41iEc0hf6T...,https://www.amazon.in/OnePlus-Nord-Jade-128GB-...
98,0E9G8KOY,Hul pureit germkill kit for classic 23 l water...,Home&kitchen|kitchen&homeappliances|waterpurif...,600.0,600.0,0.0,4.1,"10,907",Compatible only for Pureit Classic 23 Liter wa...,"AGJOLQCEFNEKB33FOCJ2YIEVT5DA,AG7ZK27I2UYNSV56C...","Abha Rani,V SRIKANTH,Bhagwan Khobragade,Suman ...","R3E4HUJ56AF24X,R3SEMQ02KZ7NN5,R3JNI0V7L0UEHY,R...","Wrong battery,It's working,Good,Ordinary produ...","The battery was not fitting,This time the filt...",https://m.media-amazon.com/images/I/41OxPvBpwY...,https://www.amazon.in/HUL-Pureit-Germkill-Clas...
101,8TDJNM3G,E-cosmos 5v 1.2w portable flexible usb led lig...,Computers&accessories|accessories&peripherals|...,59.0,59.0,0.0,3.8,"5,958","Portable, easy to use|LED lights for maximum i...","AEJGZNKM5ZGH6UY2YX537NWNWYDQ,AGZGGK6OUCCSLXO34...","Ravi Kumar s/o Devraj,anil-kumar,Soumith,Drew ...","R3CEIRJ8YFRONO,R3ICE0RT3T14TH,R17764XIRZDB5H,R...","Good,Product as described,Good for the price,V...","Good,Product is as described, good we can use ...",https://m.media-amazon.com/images/I/413phG1P5U...,https://www.amazon.in/COSMOS-Portable-Flexible...
229,0K32PEW4,Casio mj-120d 150 steps check and correct desk...,Officeproducts|officeelectronics|calculators|f...,535.0,535.0,0.0,4.4,4.4K,Dedicated Tax keys for calculation of price pl...,"AGJ2FUFEZ6Y65C3CZA6XJ4J74NFA,AEOMLWH4R5GQ2PAEY...","Certified customer,deepak,Sanjiv Suhas gogate,...","R1JB53IQ0AXIHW,RPKOAVSXXPSKU,R3AIW6ZYB8OS8W,R1...","Utilitarian,Excellent product,Good features,Go...",Standard calculator. What you expect from a 12...,https://m.media-amazon.com/images/I/51yFKniMhc...,https://www.amazon.in/Casio-MJ-120D-Electronic...
237,0DJ5N9VK,Faber-castell connector pen set - pack of 25 (...,Toys&games|arts&crafts|drawing&paintingsupplie...,150.0,150.0,0.0,4.3,"15,867",Simply draw and color or clip these pens toget...,"AE5D3EMPETKIA4VU4SZU5UIHXKQA,AFF76KWKCMR6GNPUX...","Aradhna Aadhya,sonali ghosh,Sam,VGRK,Surfer007...","R39PYNXMLNEIYW,R3AMNR0LJWNAUU,R2P5M80U8OL9OQ,R...",As this was my 2nd order for same product.2nd ...,Torn packing.dekhne me product used lg rha tha...,https://m.media-amazon.com/images/I/41rJGx-w9i...,https://www.amazon.in/Faber-Castell-Connector-...
258,0YQLG7GK,"Philips hl1655/00 hand blender, white jar 250w",Home&kitchen|kitchen&homeappliances|smallkitch...,1695.0,1695.0,0.0,4.2,"14,290","Steel rod, rust proof metal rod for hot/cold b...","AHMV7CFP5QJKQVZUWZJHE4HZ2ICA,AFZST4HYDBQ6XVQAC...","Swathi,Amazon Customer,Chethan KP,Anu Tri,Rava...","R1D9RWNUO50OL2,R3UBUQT5L25WJV,R41I3GR7DNRBK,R3...","Heats up after less time of usage.,Its is fine...",Works well. Good Design. It's heavy.You can't ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Philips-Collection-HL165...
274,8HQL67D6,Ofixo multi-purpose laptop table/study table/b...,Computers&accessories|accessories&peripherals|...,599.0,599.0,0.0,4.0,"26,423",【MULTI-PURPOSE LAPTOP DESK】- OFIXO Laptop bed ...,"AHTBDJ3J72O3A3NQNV2OUTOXP36A,AFPYH3UF3GB4RNX3M...","Sonubhai,Sujili v,Mohammad Maqsood,Mohammed Ja...","R3O03EUB6UY68T,R1FMMOPHEXIHKO,R23PAXUWIYVJ2W,R...","Value for money,Good,Everything is good but pr...","its value for money , its good for students an...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/OFIXO-Multi-Purpose-Fold...
281,95X38CJS,Brustro copytinta coloured craft paper a4 size...,Officeproducts|officepaperproducts|paper|copy&...,99.0,99.0,0.0,4.3,388,Made at the renowned Fabriano paper mill in It...,"AG7MI6MZP3GMUTO65QNUR25VP7VA,AHBZCVGYU7BO7DCSN...","kashif,sezhian,Dinesh K.,Jenifer,Harsh,suresh,...","R2ETD6AVA4AFF1,R3CUOW1DUP8N92,R3NYD5UBRVJDWP,R...","Good,Heads up,Good product,Bright in color go...",Good value of money if u have students at home...,https://m.media-amazon.com/images/I/41WggyozHQ...,https://www.amazon.in/BRUSTRO-Copytinta-Colour...
341,0LY17RHI,Camlin elegante fountain pen - black/blue/red,Officeproducts|officepaperproducts|paper|stati...,225.0,225.0,0.0,4.1,"4,798",Handcrafted with Gold plated nib|Brass Cap Chr...,"AE6FSULFZEB65U7FWSETNHLBP5JQ,AGV3YW3GZJTWUP4FC...","Rayees Tigadi,ajay,Tathagata Chakraborty,Rajen...","R1KPESOANRAUT2,R2765UCQGUXR8Z,R1MIY4MLC7OEMH,R...","Good Pen at Low Cost,... have been reading abo...",First of All Delivery of Amazon: It was as spe...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Camlin-Elegante-Fountain...
342,0TI8E7BI,Philips hd9306/06 1.5-litre electric kettle (m...,Home&kitchen|kitchen&homeappliances|smallkitch...,2695.0,2695.0,0.0,4.4,"2,518","Food grade stainless steel, Frequency: 50 Hz. ...","AHYXOMUJUKZHBWHP43ZAB265EDGA,AG4C27NTZZ7HTG6W3...","AmazonCust,DD_Zen,Amazon Customer,VINISH THOMA...","R252H4TFMWK9L7,R3SAFGRVGD7GTV,R1FVCFYT4SGY76,R...","3,Sturdy and Works Flawlessly,Excellent 👍,Real...","Cord is small and sound while heating,Well bui...",https://m.media-amazon.com/images/I/41JyZuDzDg...,https://www.amazon.in/Philips-HD9306-06-1-5-Li...
416,0LM4X0KU,"Parker quink ink bottle, blue",Officeproducts|officepaperproducts|paper|stati...,100.0,100.0,0.0,4.3,"3,095",Blue colour is washable in nature.|30ml Bottle...,"AEWW4LJOVXD65UKE7QCBCHQZMG7A,AGVWB5YTQZC7GAIV4...","Kindle Customer,Aryan,pooja reddy,Amazon Custo...","R1T4TKPYU5EJCB,R1D38AX8G0RVNS,R1KHCRDEEREQG7,R...","Clearly makes a difference,Good,Value for mone...",I first used non-parker ink for my fountain pe...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Parker-Quink-Ink-Bottle-...
499,8F47T4X5,Vr 18 pcs - 3 different size plastic food snac...,Home&kitchen|kitchen&homeappliances|smallkitch...,89.0,89.0,0.0,4.2,"19,621",MULTI-PURPOSE: Can be used to seal all types o...,"AEWWWALRID3B4CQQK7PMSARCRM7Q,AF2QBWT5Z74JZHE3S...","Prathiba R,Aishwarya,Jeevan Raj,Madhur,Vimal t...","R37CHVALZ1PLJG,R2DLNWVOG65T2N,R1OXPNJF31B34Y,R...","Very nice,Works as it should,Not the best but ...","Product is good and color full, completely liv...",https://m.media-amazon.com/images/I/51swXR+r2x...,https://www.amazon.in/VR-Pcs-Different-Multi-C...
561,71VMP1Z4,Lripl compatible sony bravia lcd/led remote wo...,"Electronics|hometheater,tv&video|accessories|r...",399.0,399.0,0.0,3.9,"1,951",Before Order Please Match Your Remote With Ima...,"AELO5I776X3QUOQZ7AEEFC565CYA,AEJNUCP6WR35MUUPR...","Vishal Nagpal,sharmila,Amazon Customer,Ashish ...","R17PVKPPX1FJYC,R34PJA3123VAT3,R1AYZQXNSM6U7F,R...","Works like Charm,Useful,Good,Very nice,Doesn't...",The remote looks very similar to the original ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/LRIPL-Compatible-Bravia-...
568,12ELCYUG,Preethi mga-502 0.4-litre grind and store jar ...,Home&kitchen|kitchen&homeappliances|smallkitch...,635.0,635.0,0.0,4.3,"4,570","Country of Origin: India|Capacity: 0.4 liters,...","AGC3Z3473ZVXYFMWYSAUE2T7V3MA,AEDXKCO2L3ULRQJ5I...","Sunil Khandagale,Shamim,HARI.M,Malini,Kusal Sr...","RN9VBZPCHG67H,RSK3T9GASN96L,RPWBSG3KWA82A,RWGY...","Good,Goos product which you can trust,Good,Cos...","You can buy a good product.,Purchased this spa...",https://m.media-amazon.com/images/I/414iVhwacb...,https://www.amazon.in/Preethi-MGA-502-0-4-Litr...
587,84872DQY,Mi 80 cm (32 inches) hd ready android smart le...,"Electronics|hometheater,tv&video|televisions|s...",14999.0,14999.0,0.0,4.3,"27,508",Resolution: HD Ready Android TV (1366x768) | R...,"AG2CJB47VQE4AVBUYWE7TYPVMYHQ,AF22S3IGZ42YVFNOU...","MUNIYANDI. D,Rathod Ganesh.,Pankaj,Arulkumar M...","R1OHBRJRE6GHDZ,R24I7EFZQG9TE6,R3G0UPCD2KN4F7,R...","Nice tv,Good product,Average,No operation butt...","Good quality,Good product,Average,No operation...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Mi-inches-Ready-Android-...
614,0KIE28X0,"Camel artist acrylic color box - 9ml tubes, 12...",Home&kitchen|craftmaterials|paintingmaterials|...,310.0,310.0,0.0,4.5,"5,882",Set of 12 assorted Shades in 9 ml tubes,"AEF5YBIELXGHKIQUBYBHTEPHHAHA,AETP2GEWPZZBFPYME...","Daisy daniel,POONAM A.,T.GIFTSON,ANIRBAN SAHA,...","R37O1AOVLZR8TU,RUYL5687EN2BX,R8U5WNK0AIG7Y,R3H...","Noice,Love these.!,Good,Nice product,Good item...",https://m.media-amazon.com/images/I/715D5RP3RI...,https://m.media-amazon.com/images/I/51UTH-oHa9...,https://www.amazon.in/Camel-Camlin-Kokuyo-Acry...
678,073QGKAS,Bajaj atx 4 750-watt pop-up toaster (white),Home&kitchen|kitchen&homeappliances|smallkitch...,1499.0,1499.0,0.0,4.3,"9,331",2 slice pop-up toaster|Variable browning setti...,"AESRBPLU5VWDLZIS34S4MGRGXOHA,AFJBNICX3G744YBO6...","Aisha,Gourav,Riya Halder,Karishma Sharma,Sridh...","R1HBS1IAS9P3EK,R3B3INPXIQLFGO,R3U26KEWXGCBX2,R...",NaN,"Good and easy to use,Very good,Good.,Overall a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-ATX-750-Watt-Pop-u...
717,8BQ947H3,"Liramark webcam cover slide, ultra thin laptop...",Computers&accessories|accessories&peripherals|...,149.0,149.0,0.0,6.0,"10,833",Cool Gadget: Protection against possible video...,"AFF3MID2VKCRG3UPIGY4OPDLKNBQ,AGYZOVT6JVQNGFJ2W...","Vishal Bhardwaj,Parvathi M.K,swaraj,Simi","R18D9LZAYX9JSY,R2TD56H4WD69RD,R3022ERQVPT7PV,R...","Merges with the device, Ultra Thin, Smooth Sli...",PRODUCTLIRAMARK Webcam Cover SlideEVENTS DATES...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/LIRAMARK-Webcam-Blocker-...
764,08FWZGSG,Samsung original type c to c cable - 3.28 feet...,Computers&accessories|accessories&peripherals|...,599.0,599.0,0.0,4.3,355,USB Type-C to Type-C cable with universal comp...,"AEQWVGESA7TDGK7KZ4DAJQGYH32A,AECGAMNNIMW5QOPOB...","Verified Buyer,Avishek Majumdar,Drowna roy,mah...","R2Z9ENI1BK4EAB,R2JTBG4GO7WPMG,R3GKCN4UH999M8,R...","Good,Genuine product,Not first charge this cab...","Buy it,Received in good condition and is worki...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Samsung-Original-Type-Ca...
790,7FXLC2G2,"Tata swach bulb 6000-litre cartridge, 1 piece,...",Home&kitchen|kitchen&homeappliances|waterpurif...,698.0,699.0,0.0,4.2,"3,160",Pure Power Indicator: Indicated purifying powe...,"AHDISL5G65X3FMRD2D2ARNXONYEQ,AFYN7CPGKOFGIEEDC...","Mahesh Thakur,NAGESWARA RAO BONKURU,Premlata S...","R3EJ8Q3TMPSQR3,R1LN1C5CM8PCGA,R3KY2YEIO4VRG3,R...","Good,FITTING,Sealing of the product is faulty,...",Everything was good. Just issue I found with t...,https://m.media-amazon.com/images/I/31N5vx+L1K...,https://www.amazon.in/Tata-Swach-Bulb-6000-Lit...
791,0LY12TH6,Camel oil pastel with reusable plastic box - 5...,Home&kitchen|craftmaterials|paintingmaterials,230.0,230.0,0.0,4.5,"9,427",50 assorted shades + 1 scraping tool|Confirms ...,"AF2RABP57DKRSINAD3R2DKITOV7Q,AEGE3H7UIM7FCTYQK...","Jayanta,Himanshu kumar,Saima,Vivek kumar,Raka,...","R1XLI27TRADFPX,R7BJF3442UAD5,R3G24OOLVH7NPF,R1...","Good product,Decent,Highly recommended,Kids lo...","Good product, can go for it,https://m.media-am...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Camel-Oil-Pastel-Reusabl...
801,7LFQLKFZ,Parker moments vector timecheck gold trim roll...,Officeproducts|officepaperproducts|paper|stati...,420.0,420.0,0.0,4.2,"1,926",Mode: Roller ball pen|Pen opening mechanism: C...,"AG23N2Z5CVKFJZ6ZLIYU4NQTDKFA,AG2T5VLGSYCC4K6VI...","Amit Kumar Chaudhary,Ankita Kakkar,Neelam Cho...","R2CZ99K13VTGRS,R34J3428JVACPO,R2F41WQEBTUTFF,R...","Nice but few Cons (*that you must read*),Smoot...",",Writes smoothly,Nice,The look and feel of the...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Parker-Moments-Vector-Ti...
820,99S26HWG,Classmate pulse 1 subject notebook - 240mm x 1...,Officeproducts|officepaperproducts|paper|stati...,300.0,300.0,0.0,4.2,419,The cover design of the notebook is subject to...,"AFXZNVON4LZKKL23DAL7IPT5ZJUA,AFSZKLP7O5V7SHFKR...","Ayush pandey,Puneet Sharma,Lakshay,Vala 18,Jel...","R3I568NWPF5187,R19KS9NAHZME09,R384JBLG7VAYNP,R...","Pages size is small but good quality,Okay,Qual...","Pages are small,Okay okay,Best product but siz...",https://m.media-amazon.com/images/I/51h6eqwfeP...,https://www.amazon.in/Classmate-Pulse-Subject-...
831,752LL57V,Casio mj-12d 150 steps check and correct deskt...,Officeproducts|officeelectronics|calculators|b...,440.0,440.0,0.0,4.5,"8,610","Regular keys like %, square root and Memory|De...","AFCKVOFM46DHVEVU7M4ABUCXDLLQ,AH6ROKDEOWF5LFGRK...","Dipu,Kayumuddin,Ankit salunke AS,Ramachandran ...","R3S29FN21O2CMZ,R11MO8HH0GUD1M,R3TQJKN7EJKGXO,R...","Very easy to use,Easy to use .,Best calculator...","Very good,Nice product,https://m.media-amazon....",https://m.media-amazon.com/images/I/41cRLg+wdI...,https://www.amazon.in/Casio-MJ-12D-Desktop-Cal...
834,8BQ947H3,"Liramark webcam cover slide, ultra thin laptop...",Computers&accessories|accessories&peripherals|...,149.0,149.0,0.0,4.3,"10,833",Cool Gadget: Protection against possible video...,"AFF3MID2VKCRG3UPIGY4OPDLKNBQ,AGYZOVT6JVQNGFJ2W...","Vishal Bhardwaj,Parvathi M.K,swaraj,Simi","R18D9LZAYX9JSY,R2TD56H4WD69RD,R3022ERQVPT7PV,R...","Merges with the device, Ultra Thin, Smooth Sli...",PRODUCTLIRAMARK Webcam Cover SlideEVENTS DATES...,https://m.media-amazon.com/images/I/41PeQz-jDS...,https://www.amazon.in/LIRAMARK-Webcam-Blocker-...
902,846D5CBP,Casio fx-991es plus-2nd edition scientific cal...,Officeproducts|officeelectronics|calculators|s...,799.0,1295.0,0.0,4.5,"5,760",Redesigned ES PLUS series calculators featurin...,"AFES6HMBN5CAV5HWKASX5HS743BA,AE2SYKBDNNE4PVOOY...","Vajrala s.,Goutham.G.A.,Abhishek Kumar Sharma,...","R2MYHLYRBQ49CU,R1ZYG8KT7IKN0F,R1CPM2M1SFJD0Q,R...","Nice,Good and light calculator,Cheap buttons,G...","It is very easy to use.,Good and easy to use.,...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Casio-FX-991ES-Plus-2nd-...
941,75DB1F13,"Panasonic eneloop bq-cc55n advanced, smart and...",Electronics|generalpurposebatteries&batterycha...,1500.0,1500.0,0.0,4.4,"25,996",Panasonic advanced Ni-MH battery charger has a...,"AEOZN7QHTHMBMPZ44PLKH7ML2GFA,AHBZTGUKAUVUWWRIX...","Sreelal S,Abe Ralte,Abe Ralte,sridharan,Anuj M...","R1JNM12EEHAKDU,R3D30LR1EYBE2P,R30L9O9HJ5UAK7,R...","Good rechargeable battery,Seems to be good,Nic...",A good battery set for use with cordless phone...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Panasonic-Eneloop-BQ-CC5...
943,0LP9RFSU,Eureka forbes aquasure amrit twin cartridge (p...,Home&kitchen|kitchen&homeappliances|waterpurif...,825.0,825.0,0.0,4,"3,246",Color: White|Specially designed for AquaSure s...,"AHFGOH4GBUXQQ45BNRBY7MHPN4NQ,AHY6F4BLYRDJCSKQS...","dr. sunil,Fayaz Ahmed,Rajesh A. Dhok,Sham s.,S...","R2UVKVQN13D4BP,ROIDOHU6ZPBY6,RVYETD2GBOPL1,R35...","Pack of two but only one compatible,Using the ...","Though I bought a pack of two, after seeing th...",https://m.media-amazon.com/images/I/41WfA7FDnz...,https://www.amazon.in/Eureka-Forbes-Amrit-Twin...
967,B4SJKRDF,Kitchenwell multipurpose portable electronic d...,Home&kitchen|kitchen&homeappliances|smallkitch...,239.0,239.0,0.0,4.3,7,Package : 1 Weighing Scale|Easy To Use|Durable...,"AGP5YURZQ6W2GKYILORIGKB3NDUQ,AEPAZYTLJQKDOZBSN...","Dinesh,Rajesh Thakur,Kiran chaudhary,Shyam Kot...","R1UQOSA7I0B6CT,R1JP6NH8K5NZU5,R2I5H53LBQO3LU,R...","Good quality scale but I got defective piece,N...",This weighing scale is made of good quality ma...,https://m.media-amazon.com/images/I/319gn5l2NS...,https://www.amazon.in/Kitchenwell-Multipurpose...
990,7SBGFDX9,"Pentonic multicolor ball point pen, pack of 10",Officeproducts|officepaperproducts|paper|stati...,120.0,120.0,0.0,4.1,"4,308","0.7 mm tip size|Black Body, Multicolor Ink(Bla...","AGK76H5VGHDWFQD7JTHVKZNQ5BHA,AHWXK2FU23OBRZZUA...","Parul S.,Prateek Tiwari,kateriki,golla ramesh,...","R1FXYA8WISUWTK,R2C5SUFAIFCKV9,RD87PA0KNH3GQ,R1...","Average,I like the 'Pentonic' pens,which is wh...","It's good, but they give 2 different shades of...",https://m.media-amazon.com/images/I/410DCX0vt4...,https://www.amazon.in/Linc-Ball-Point-Pentonic...
1039,7KCMR8D6,Classmate octane neon- blue gel pens(pack of 5...,Officeproducts|officepaperproducts|paper|stati...,50.0,50.0,0.0,4.3,"5,792",5 vibrant Neon body color|Smooth and fast writ...,"AEVPRYZLGHNMEZA5BYGIX36LYZXA,AEZPOZQEEBFFXZ2EQ...","Gatij saini,Biswajit Kundu,Altaf Khan,Agam Sar...","RZAAQFY7BDSWC,R3604ZO2AA4PK5,R3C8K6Z6W9MDTQ,R3...","Nice ball pen,Good product,Average,Nice Pen,It...","Very nice ball pen,Thank you Amazon,Easy to ho...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Octane-Neon-Pa...
1077,B3CQBRB4,"Oneplus nord 2t 5g (gray shadow, 8gb ram, 128g...",electronics|mobiles&accessories|smartphones&ba...,28999.0,28999.0,0.0,4.3,"17,415",Camera: 50MP Main Camera with Sony IMX766 and ...,"AEREO7C5GLYYYV6YXK7X4UCCQTJQ,AHWISRUJUCJG6UH4F...","ASR,Amazon user,Rama Rao,Vinay,ANIKET,NAGA SHA...","R128LZ0DN2NZBZ,R3LFQ7EDHZ6DKM,RUSJFUV64DPWM,RH...","Really a Good Buy in this price range in 2022,...",Verdict : A Solid buy for this price segment i...,https://m.media-amazon.com/images/I/41qLZhKF5Z...,https://www.amazon.in/OnePlus-Nord-Shadow-128G...

In [3657]:
df.loc[df['discount_percentage'] <= 0] = 0

In [3658]:
df.loc[df['discount_percentage'] <= 0]

# it is better to go Zero rather compute median on this discount_percentage as it might create outlier
# we only see one negative values

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
33,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
57,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
62,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
71,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
94,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
101,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
229,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
237,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
258,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
274,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
281,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
341,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
342,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
416,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
499,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
561,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
568,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
587,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
614,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
678,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
717,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
764,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
790,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
791,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
801,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
820,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
831,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
834,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
902,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
941,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
943,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
967,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
990,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1039,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1077,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1095,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1130,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1132,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1142,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1145,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1194,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1300,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1370,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1380,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1420,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1457,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1486,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0

In [3659]:
df.loc[df['discount_percentage'] >= 100]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
476,7WDK3ZS6,"Iqoo z6 lite 5g by vivo (mystic night, 6gb ram...",Electronics|mobiles&accessories|smartphones&ba...,15499.0,18999.0,120.0,4.1,"19,252","World's First Snapdragon 4 Gen 1 Processor, th...","AHWRZWPCTG6ICA7WTNLNNZXWFI5Q,AF2AASVYVSROFD7FX...","siddharth patnaik,Dr Sunilkumar H,Krishna,K. S...","R27MK332LTT5KS,R2TN6LNGD4FLYB,RVZJOLWLG5JZ9,R3...","Above average phone,Worth For The Money 💰,Okie...",I purchased the 6/128gb variant.To sum it up ...,https://m.media-amazon.com/images/I/41Yylo75u7...,https://www.amazon.in/iQOO-Storage-Snapdragon-...
647,96MSW6CT,Sounce fast phone charging cable & data sync u...,Computers&accessories|accessories&peripherals|...,199.0,1899.0,120.0,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
766,97r25dp7,Noise colorfit pulse smartwatch with 3.56 cm (...,Electronics|wearabletechnology|smartwatches,1599.0,4999.0,120.0,4.0,"67,950",[10-day battery]: With a battery backup of 10 ...,"AHECNVXSW6REC5TOGBH6OJXIBL4A,AFWAX2O5B5I36ESHP...","Ankita Dwivedi,Malathi Alunkar,Shubham♎,Oishi ...","R1NARG7VJ59AD3,R6BEKBJDZAEX5,R36J5LRZNMMZXL,R2...","Noise smartwatch,The product is good overall,G...","Good fit, nice smart watch in this price range...",https://m.media-amazon.com/images/I/41XH-IpxCQ...,https://www.amazon.in/Noise-ColorFit-Smartwatc...
779,819ZZK5K,Sandisk ultra dual drive go usb type c pendriv...,Computers&accessories|externaldevices&datastor...,1109.0,2800.0,120.0,4.3,"53,464",The 2-in-1 flash drive with a reversible USB T...,"AEZPNXZLF5U7XEX6TOW3J56C3XDA,AGG3ECGCIKNPZJEVJ...","Amita,Ganesh,zhiv,Sarasij Pal,ज्ञानेंद्र सिंह,...","R3PB00C7ZEBAMG,RVUGXND7SHFW8,R9LR8JP82ED2X,R32...","Fast, but heats up and throttles...,Its a Usef...",The sequential read speeds for a 8gb video fil...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/SanDisk-Ultra-Drive-Pend...
807,BM4KTNL1,"Figment handheld milk frother rechargeable, 3-...",Home&kitchen|kitchen&homeappliances|smallkitch...,699.0,1599.0,120.0,4.7,"1,729",【Rechargeable Multi-Function Milk Frother】The ...,"AGMHHTX7GPWHZAUTEYQOFEEDFMDQ,AEJJGJQCIEPL3ZBNU...","123MovieTime,Ravneet S.,Akash,Mohd Amaan,Panka...","R1YXOQ6ZZI33LZ,R17FVMZGPYPOYZ,R23NCERA0R891T,R...","Nice product,Not as effective as claimed, just...","Value for money,Not as effective as claimed, j...",https://m.media-amazon.com/images/I/51oN+8Zs5Y...,https://www.amazon.in/FIGMENT-Rechargeable-Dec...
996,85DTN6R2,Portronics konnect cl 20w por-1067 type-c to 8...,Computers&accessories|accessories&peripherals|...,350.0,899.0,150.0,4.2,"2,263",[20W PD FAST CHARGING]-It’s supports 20W PD qu...,"AGUAYQHARAKR2VZTRP276KAGETKQ,AFKTST2773VUOKUHE...","Priya,Mansi,Plaban,Vivek,Taufique Ahmed,Pravee...","R1QETDIPRCX4S0,RARQYQ8POOFA9,R952F931MCOR5,R3L...","Works,Nice Product,Fast Charging as original,G...",Definitely isn’t as good as the original cord ...,https://m.media-amazon.com/images/I/31J6qGhAL9...,https://www.amazon.in/Portronics-Konnect-Deliv...
1227,7J2NGB69,"Lenovo 400 wireless mouse, 1200dpi optical sen...",Computers&accessories|accessories&peripherals|...,629.0,1390.0,150.0,4.4,"6,301","Take out the mouse, insert the USB, and click ...","AG3P4IMSW644U3FQ2765XNZFNC3Q,AGDKW4WQN3ZJJ4CVY...","abhilash n.,Tk,Mayur,Ajay,himanshu kumar,Harik...","R3WA8CHZXMRJR,R22MH6ZS821G9A,R1FIRMYTZRF479,R1...","Not to the mark.,Ok.,Good Product,Good but lac...",Had zero expectations when bought it. Neither ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lenovo-GY50R91293-Wirele...

In [3660]:
df[df['discount_percentage'] >= 100] = np.nan

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/488467112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['discount_percentage'] >= 100] = np.nan

In [3661]:
df['discount_percentage'] = df['discount_percentage'].fillna(df['discount_percentage'].median())

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/3809434304.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_percentage'] = df['discount_percentage'].fillna(df['discount_percentage'].median())

In [3662]:
df[df['discount_percentage'] > 0]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,Boat stone 250 portable wireless speaker with ...,Electronics|homeaudio|speakers|bluetoothspeakers,1199.00,3990.0,70.0,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,Eureka forbes euroclean paper vacuum cleaner d...,"home&kitchen|kitchen&homeappliances|vacuum,cle...",253.00,500.0,49.0,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,Milton smart egg boiler 360-watts (transparent...,Home&kitchen|kitchen&homeappliances|smallkitch...,1099.00,1899.0,42.0,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech m331 silent plus wireless mouse, 2.4g...",Computers&accessories|accessories&peripherals|...,799.00,1645.0,21.0,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells instanio 10 litre storage water heater...,NaN,6990.00,14290.0,51.0,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,756K5DYZ,Prestige iris 750 watt mixer grinder with 3 st...,Home&kitchen|kitchen&homeappliances|smallkitch...,3249.00,6295.0,48.0,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello eliza plastic laundry bag/basket, 50 lit...",Home&kitchen|homestorage&organization|laundryo...,998.06,1282.0,22.0,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult audio bassbuds oak in-ear wired earphone...,"Electronics|headphones,earbuds&accessories|hea...",499.00,1299.0,62.0,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,Ngi store 2 pieces pet hair removers for your ...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",199.00,999.0,80.0,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen mart stainless steel south indian filt...,"Home&kitchen|kitchen&homeappliances|coffee,tea...",292.00,499.0,41.0,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3663]:
df['discount_percentage'].isna().sum()

np.int64(0)

rating : Missing values, convert data type to Float, rating should be between 1 and 5.

In [3664]:
df['rating']
df['rating'].isna().sum()

np.int64(27)

In [3665]:
df['rating']

0       4.2
1       4.3
2       4.3
3       4.6
4       4.4
       ...
1490    3.9
1491    4.2
1492    3.9
1493    3.1
1494    4.1
Name: rating, Length: 1455, dtype: object

In [3666]:
df['rating'] = pd.to_numeric(df['rating'],errors='coerce')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1055126195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = pd.to_numeric(df['rating'],errors='coerce')

In [3667]:
df['rating'].dtype

dtype('float64')

In [3668]:


df['rating']

0       4.2
1       4.3
2       4.3
3       4.6
4       4.4
       ...
1490    3.9
1491    4.2
1492    3.9
1493    3.1
1494    4.1
Name: rating, Length: 1455, dtype: float64

In [3669]:
df.loc[(df['rating'] < 1)| (df['rating'] > 5 ),"rating"]= np.nan

In [3670]:
df[df['rating'] < 1]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3671]:
df['rating'] = df['rating'].fillna(df['rating'].median())

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/3809259488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].fillna(df['rating'].median())

In [3672]:
df['rating'].isna().sum()

np.int64(0)

In [3673]:
df['rating']

0       4.2
1       4.3
2       4.3
3       4.6
4       4.4
       ...
1490    3.9
1491    4.2
1492    3.9
1493    3.1
1494    4.1
Name: rating, Length: 1455, dtype: float64

Rating Count : Remove commas, convert data type to Int, all values should be ≥ 0.

In [3674]:
df['Rating Count'] = df['Rating Count'].str.replace(',' ,'')
df['Rating Count'] = df['Rating Count'].str.replace('k' ,'')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1936346042.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating Count'] = df['Rating Count'].str.replace(',' ,'')
/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1936346042.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating Count'] = df['Rating Count'].str.replace('k' ,'')

In [3675]:
df['Rating Count'] = pd.to_numeric(df['Rating Count'],errors='coerce')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/3507775953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating Count'] = pd.to_numeric(df['Rating Count'],errors='coerce')

In [3676]:
df['Rating Count'].dtype

dtype('float64')

In [3677]:
df['Rating Count']

0        2908.0
1        2664.0
2        1811.0
3       12375.0
4        1771.0
         ...
1490    43070.0
1491     7274.0
1492     1173.0
1493        2.0
1494     4238.0
Name: Rating Count, Length: 1455, dtype: float64

In [3678]:
df[df['Rating Count'] <= 0]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3679]:
df['Rating Count'] = df['Rating Count'].fillna(df['Rating Count'].median())

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1116523847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating Count'] = df['Rating Count'].fillna(df['Rating Count'].median())

In [3680]:
df['Rating Count'].isna().sum()

np.int64(0)

about_product : 30 missing values, remove extra spaces and unwanted special characters.

In [3681]:
df['about_product']
df['about_product'] = df['about_product'].fillna('Unknown')
df['about_product'].isna().sum()

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1738414845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['about_product'] = df['about_product'].fillna('Unknown')

np.int64(0)

In [3682]:
df['about_product'] = df['about_product'].str.capitalize()

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1220541739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['about_product'] = df['about_product'].str.capitalize()

In [3683]:
df[df['about_product'] == df['about_product'].str.upper()]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3684]:
df['about_product']

0       Power- get ready to be enthralled by the 5w rm...
1       Special anti-microbial(biocide treated) paper ...
2       3 boiling modes - the advanced appliance from ...
3       Quieter click: logitech’s silenttouch technolo...
4       Suitable for high-rise buildings and pressure ...
                              ...
1490    Motor warranty: 2; product warranty: 2;|operat...
1491    Material: plastic, color: light grey100% food ...
1492    In-line controls: answer/reject/ calls, play/p...
1493    Versatile, protects your clothes: movecatcher ...
1494    Material: food grade stainless steel; make aut...
Name: about_product, Length: 1455, dtype: object

In [3685]:
df['about_product'] = df['about_product'].str.replace(r'[^\w\s]',' ',regex=True)

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/2621928525.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['about_product'] = df['about_product'].str.replace(r'[^\w\s]',' ',regex=True)

In [3686]:
df['about_product']

0       Power  get ready to be enthralled by the 5w rm...
1       Special anti microbial biocide treated  paper ...
2       3 boiling modes   the advanced appliance from ...
3       Quieter click  logitech s silenttouch technolo...
4       Suitable for high rise buildings and pressure ...
                              ...
1490    Motor warranty  2  product warranty  2  operat...
1491    Material  plastic  color  light grey100  food ...
1492    In line controls  answer reject  calls  play p...
1493    Versatile  protects your clothes  movecatcher ...
1494    Material  food grade stainless steel  make aut...
Name: about_product, Length: 1455, dtype: object

In [3687]:
df['about_product'] = df['about_product'].str.strip()

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/2681377319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['about_product'] = df['about_product'].str.strip()

user_id : 30 missing values, ensure proper formatting and remove extra spaces.

In [3688]:
df['user_id'].unique()

array(['AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOYEGCMHZRI22A,AF3CWTDKJKG76CDV3IL6X72ZC6EA,AF73CGOZKN7MGOT7NZBIJFV35UQA,AF4CMSAMBV4RKGO4LWDE4LY5K2QQ,AGVG3B4ICKXGMOKDYKEOWIAO7LSA,AFVLASKUEKD7ILQRPFL4TAUJAUUA,AH2Z5DXERV53SFHROV27HKERTZPA',
       'AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU5RSBKSQMIVA,AHFQXP2EQZOT7NTNHK5TMB6QA5QQ,AGLL6YL7RHHSDDGKWQO7ZIG3TXDQ,AGT4T2NBHXL5XVSRRCKSIGW7LDJA,AEAZZCC5KRGSGXGTGBRNK2O6IDAQ,AGBESE5F5QORNV2B6HE4UL4AMZ7Q,AE7QJ5FKTIU6K26GFQWGMXKO2MGQ',
       ' AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK442JABEE5CWLQ,AEAT6CQT34IWYKUHXFMFGRNU7Q2A,AGZ3OTE7V74KVKLKR3PS2YSCM5QQ,AHURSRZTOF3NCYIB5RPFTXSHAEQQ,AFJ4QE5S3Y4YQR2FV36TS7QDG2KQ,AFWGKSA7JKANXBJVXLCPW7NR6ICQ,AHZYN7O73FJWRPUQGZM5BEAZ3A4A  ',
       ...,
       'AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4CH5GEKNUWAIQ,AHU3G6JL2C765DSFVXYNANCGFATA,AEF7R2XPRQEBGHMMUTQRQNQ7CHLQ,AHMWV64SEF7KPL6YJUVNNIAIEHJA,AHBVHPQ4W6276E6FKYIQHJQ4BMRQ,AH6ZGBUYPQH5WWPNBBMYQMYOOYTA,AH4XKLZAXDJGMB74RNSTAQD6T33Q',
       'AFPKVN5KLHB4MHSYDS25Q5MIWWKQ',
       'AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNOV2YCEKMBTXA,AEEGIQ6LMHJWRZ3YS37ACZD6HYCA,AE4FTPFQLHBP4IG2JCSRSKXM4VFA,AEUOCCUL5KHPEVXARZLU4U42WV2A,AGBSJ7VFUFPUQO6FH2ZJXY267A5Q,AGJ52I42NLYWGYET5BK5SJWMP6HQ,AEUWACJRUOGKOVFW2FOW3RSI3SIA'],
      dtype=object)

In [3689]:
df['user_id'].isna().sum()

np.int64(10)

In [3690]:
df['user_id'] = df['user_id'].fillna('Unknown')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/461750104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_id'] = df['user_id'].fillna('Unknown')

In [3691]:
df.loc[(df['user_id'] != df['user_id'].str.upper()) & (df['user_id'] != 'Unknown')]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
33,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
57,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
62,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
71,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
94,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
98,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
101,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
229,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
237,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
258,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
274,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
281,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
341,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
342,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
416,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
499,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
561,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
568,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
587,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
614,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
678,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
717,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
764,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
790,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
791,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
801,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
820,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
831,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
834,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
902,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
941,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
943,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
967,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
990,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1039,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1077,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1095,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1130,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1132,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1142,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1145,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1194,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1300,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1370,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1380,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1420,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1457,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0
1486,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,0,0,0,0,0,0,0

In [3692]:
df[df['user_id'] == 'Unknown']

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
329,Unknown,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
476,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
647,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
766,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
779,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
1227,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [3693]:
df['user_id'].isnull().sum()

np.int64(0)

In [3694]:
df['user_id'] = df['user_id'].replace([0, '0'], 'Unknown')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1378890299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_id'] = df['user_id'].replace([0, '0'], 'Unknown')

In [3695]:
df[df['user_id'] == 'Unknown']

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
33,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
57,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
62,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
71,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
94,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
98,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
100,NaN,NaN,NaN,NaN,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
101,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
229,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
237,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
258,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
274,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
281,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
329,Unknown,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
341,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
342,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
416,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
476,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
499,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
561,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
568,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
587,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
614,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
647,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
678,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
717,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
764,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
766,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
779,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
790,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
791,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
801,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
807,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
820,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
831,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
834,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
902,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
941,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
943,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
967,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
990,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
996,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
1039,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1077,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1095,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1130,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1132,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1142,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1145,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1194,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1227,NaN,NaN,NaN,NaN,NaN,50.0,4.1,5137.0,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
1300,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1370,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1380,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1420,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1457,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0
1486,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,0,0,0,0,0,0

In [3696]:
df['user_id'] = df['user_id'].str.strip()

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/2023772855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_id'] = df['user_id'].str.strip()

user_name : 30 missing values, convert into Proper Case and remove extra spaces.

In [3697]:
df['user_name']

0       Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...
1       Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...
2       Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...
3       Awesome Shopper,Suresh madaka,Amazon Customer,...
4       Amazon Customer,Gaurav,khalil shaikh,Aman Seti...
                              ...
1490    Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...
1491    Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...
1492    Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...
1493                                            Kunal Sen
1494    Amazon Customer,meena polkam,Amazon Customer,N...
Name: user_name, Length: 1455, dtype: object

In [3698]:
df['user_name'].isna().sum()
df['user_name'] = df['user_name'].fillna('Unknown')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/990351884.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_name'] = df['user_name'].fillna('Unknown')

In [3699]:
df['user_name'].isna().sum()

np.int64(0)

In [3700]:
df[df['user_name'] == df['user_name'].str.lower()]
df['user_name'] = df['user_name'].str.title()

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1525934292.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_name'] = df['user_name'].str.title()

In [3701]:
df[df['user_name'] == df['user_name'].str.lower()]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3702]:
df.loc[df['user_name'].str.contains(r'[^A-Za-z0-9,.\s]',na= False),'user_name']
df['user_name']= df['user_name'].str.replace(r'[^A-Za-z0-9,.\s]', "",regex= True)

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/618519441.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_name']= df['user_name'].str.replace(r'[^A-Za-z0-9,.\s]', "",regex= True)

In [3703]:
df[df['user_name'].isna()]
df['user_name']  = df['user_name'].fillna('Unknown')

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/240582187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_name']  = df['user_name'].fillna('Unknown')

In [3704]:
df[df['user_name'].isna()]

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

review_id : Check duplicate values and ensure all Review IDs are unique.

In [3705]:
df['review_id'].nunique()

1131

In [3706]:
df['review_id'].isna().sum()

np.int64(10)

In [3707]:
df['review_id'].duplicated().sum()

np.int64(323)

In [3708]:
df.loc[df['review_id'].duplicated(keep=False),['review_id']].value_counts()

review_id
0                                                                                                                          48
R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,RDVX50PD4CTFE,R3H6WKG0TA5CGU,R3Q3L1KP5QWPV3,RU0LU2PAIIME,R20FTANBPFA653       10
R2K5OD0MEEBTDL,RS1N6TNO33BOK,R6KWBGOKI1N9Y,R30SKUMYLSXXDN,R1EOYHZWCRSV7B,R13JBDK4SAAYFT,RJOU5K9ECNW7Y,R2APPRANV6IERZ        8
RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU       7
R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1CLH2ULIVG5U3,R2DMKIBGFKBD6R,RC89B5IAJUTR5,R3B3DDON5FH8DS,R13WAEJDI5RS36       7
                                                                                                                           ..
R2PNR69G0BQG2F,R31A0WWDEYMKEW,R2C4XEWFLVU7JV,RYWES5AT5FQO6,R1PGWAY5TEWLT4,R32542OPR0QC4I,R2JDJEVZ2G7EEK,R36EHHPAQNSSOF      2
R2PF9QV9JEQO9K,R2NEN86P63G4ES,R302B7X6H0GIC0,R3H9O8F9LUY5N9,R1RGSA8QU78640,R2B3DRF8V2A9QI,R1KF9HPUVJTM0I,R3OCQ19TZWHSN5     2
R2NO4JULWOQQ5N,R1RJ8AHYBK38PD,R3PU1G9HCGIUHP,R15GKRKHWQUWZ2,R39UZTTR3JREOM,R2BQX0C2NBBJEX,R24WP5GTU5ZFG5,R18BPTXYIORQ2D     2
R223OIZPTZ994S,RATMJ847EPDQX,RHWJXUIB7QJY4,RKKX7CGMNCZLA,RL8AFQ3JO8B1N,R152XS08W2OG38,R2RS0DMJ29X2W6,RLLQ8T7VXWR65          2
R2KA10FTGOHQYB,REYTAGJ74749P,R2K1HT3L3AA6YD,R2QPRH31E0VIXG,RB7KRXWWEVCNK,R21JTGL4FLUYFT,RCYHGGNFDK4S3,R28YJ8VEV2B2GS        2
Name: count, Length: 148, dtype: int64

In [3709]:
df['review_id'] = df['review_id'].replace(0 , np.nan)

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_33456/1155926740.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review_id'] = df['review_id'].replace(0 , np.nan)

In [3710]:
df.loc[df['review_id'].duplicated(keep=False)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
6,B4F1YC3J,"Samsung galaxy m13 5g (aqua green, 6gb, 128gb ...",Electronics|mobiles&accessories|smartphones&ba...,13999.0,19499.0,28.0,4.1,18998.0,Upto 12gb ram with ram plus 128gb internal m...,"AGAELRYPMTG5SADZPDYB343EASAA,AGFN4JODOM2NTFCJQ...","Satheesh Kadiam,Pritom Chakraborty,Vishwa,Simr...","R2K5OD0MEEBTDL,RS1N6TNO33BOK,R6KWBGOKI1N9Y,R30...","Phone, camera, heating - works for me, may not...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Samsung-Midnight-Storage...
8,BBN3WF7V,"Redmi a1 (light green, 2gb ram 32gb rom) | seg...",Electronics|mobiles&accessories|smartphones&ba...,6499.0,8999.0,28.0,4.0,7807.0,Display 16 56cm hd scratch resistant display...,"AHIBP55ZTOTM3MNBFPQKJIX4TONQ,AGU6ZC6U27UDCAPG7...","Vaishnavi,Rahul Meja,Talo Mosuom,Subodh Kumar,...","RKU0JLLNRC05S,RIQJOO5ZR8L0X,R300Z83BCAV2UK,R13...",If you leave it only to make calls or receive ...,I have been using this phone for two months. A...,https://m.media-amazon.com/images/I/41JM3Ra+ti...,https://www.amazon.in/Redmi-Segment-5000mAh-Ba...
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN
14,B86CDHL1,Oraimo 65w type c to c fast charging cable usb...,Computers&accessories|accessories&peripherals|...,349.0,899.0,61.0,4.5,149.0,kindly note before you purchase this is a usb...,"AEOIHOJD3O5MYSVWZOBDUJGYWZGQ,AF6LAYTAGSTBKL2QU...","Ravi Shankar,Prakash Luhariya,Bhavesh Sabalpar...","RDFETF8YFDP96,R3604ERFM30Q4D,R1CB3GDRVBHAIG,R2...",It worked well for some days later it is not w...,It worked well for some days later it is not w...,https://m.media-amazon.com/images/I/41gztmbiIg...,https://www.amazon.in/oraimo-Charging-Syncing-...
16,0P93X2H6,Classmate pulse spiral notebook - 240 mm x 180...,Officeproducts|officepaperproducts|paper|stati...,67.0,75.0,11.0,4.1,1269.0,The cover design of the notebook is subject to...,"AH6NK74TCKWVMLPVFEC44ZLT546Q,AEUNLUIL7UEDSBOHD...","Nafisa Nehar,Narinder K.,Mayank,Harsh Raj,Dr.G...","R3QLOAFS794JE2,R3N8H6JX73IGQM,RR2G573NOMISE,R1...","it's nice. simple and easy.,It's good but I or...",I liked because it was aesthetically pleasing....,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Pulse-Spiral-N...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,bdrvfdkp,"Sandisk ultra® microsdxc™ uhs-i card, 64gb, 14...",Electronics|accessories|memorycards|microsd,569.0,1000.0,43.0,4.4,67259.0,Ideal storage for android smartphones and tabl...,"AG44HJB2AMIVHAGQZ2WGWONERKCA,AHL2FABQV6XAHZN54...","Prashant,Sumesh Sundararajan,Vijay Baitha,S.K ...","R2A7MIUNOW8DOE,R2FXP703540FR1,R37E7QJET0BYE8,R...","Fake Product,Costly but excellent quality,Stor...",128GB SD Card is showing 134GBDon't buy this p...,https://m.media-amazon.com/images/I/41ML8ZbPii...,https://www.amazon.in/SanDisk-Ultra%C2%AE-micr...
1478,B1YY6JJL,Acer 109 cm (43 inches) i series 4k ultra hd a...,"Electronics|hometheater,tv&video|televisions|s...",23999.0,34990.0,31.0,4.3,4703.0,Resolution 4k ultra hd 3840x2160 refresh...,"AFSMISGEYDYIP3Z42UTQU4AKOYZQ,AF5ILQY4KFDTO5XHH...","Ayush,Rohit A.,Kedar,Haran,Santosh Ghante,Kris...","R1EBS3566VCSCG,R24MB66WRPSN2A,R25UU2M1B9BO5X,R...",Wonderful TV and Awful installation service fr...,About the TV - Wonderful----------------------...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Acer-inches-Ultra-Androi...
1482,92BJMT8Q,Samsung 108 cm (43 inches) crystal 4k series u...,"Electronics|hometheater,tv&video|televisions|s...",30990.0,52900.0,41.0,4.3,5137.0,Resolution crystal 4k uhd 3840x2160 resolu...,"AHDIDVECFGA6OQRNUBPUO6366UGQ,AFSII6HTAHTHGXERU...","Binu,Sabjan,Ramkapil,User,Amazon Customer,Gane...","R3RUBB6REUGTT,R281851EB9L5G6,R4ATJJVUY9JO6,R18...","Best(Branded) Budget TV,A high-quality 4k Smar...","Before finalizing the AUE60 55"", I visited Cro...",https://m.media-amazon.com/images/I/41RVzq6GiI...,https://www.amazon.in/Samsung-inches-Crystal-U...
1483,8Y5QJXSR,Atomberg renesa 1200mm bldc motor with remote ...,"Home&kitchen|heating,cooling&airquality|fans|c...",3569.0,5190.0,31.0,4.3,28629.0,Super energy efficient bldc motor consumes on...,"AENFBKCVXFCSNELMZME3E3W7WNOA,AH2NF4GWIFI5TVCUT...","Vayun,Vidhate Jitendra Gangadhar,Sambasiva Rao...","R2IIQ5X1KFC218,R3GC9FMTX9ZRBD,R1KTDK3ZQXXKD1,R...",They will charge you an additional ₹300/- for ...,"They have not mentioned it here, or atleast I ...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Atomberg-Renesa-Motor-Re...
1486,0,0,0,0.0,0.0,0.0,4.1,5137.0,NaN,Unknown,Unknown,NaN,0,0,0,0

In [3711]:
df.loc[
    df['review_id'].isin(
        df['review_id'].value_counts().loc[lambda x: x > 1].index
    )
].sort_values('review_id')

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
696,7GVGTSLN,Wayona usb type c fast charger cable fast char...,Computers&accessories|accessories&peripherals|...,325.0,1299.0,75.0,4.2,10576.0,Fast charge data sync fast charge data tra...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/I/41J6oGU8w5...,https://www.amazon.in/Wayona-Cable-Braided-Cha...
774,7GVGTSLN,Wayona usb type c fast charger cable fast char...,Computers&accessories|accessories&peripherals|...,325.0,1299.0,75.0,4.2,10576.0,Fast charge data sync fast charge data tra...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Cable-Braided-Cha...
196,7F1P8KNV,Wayona nylon braided usb type c 3ft 1m 3a fast...,Computers&accessories|accessories&peripherals|...,325.0,1099.0,70.0,4.2,10576.0,Usb c to usb a data charging cable fully comp...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Charger-Samsung-G...
70,B5LVS732,Noise pulse go buzz smart watch bluetooth call...,Electronics|wearabletechnology|smartwatches,1898.0,4999.0,62.0,4.1,10689.0,Sharp and bright display the 1 69 tft displ...,"AFGHRQK34D54OXQCRGX5K3XTR66Q,AHNRGHNIKN4JHV2RV...","Sumit Nath,Aneesh Mohan,Yogesh Badekar,Manisha...","R10I6UIAQIP9TN,R2XEWWLV1LH7KX,R3J0MEY15WI71Z,R...","Sumit Nath,For the price, it is a good purchas...",Touch screen functions well .step counting is ...,https://m.media-amazon.com/images/I/41Peg4pz7f...,https://www.amazon.in/Noise-Bluetooth-Calling-...
613,B5LVS732,Noise pulse go buzz smart watch bluetooth call...,Electronics|wearabletechnology|smartwatches,1999.0,4999.0,60.0,4.1,10689.0,Sharp and bright display the 1 69 tft displ...,"AFGHRQK34D54OXQCRGX5K3XTR66Q,AHNRGHNIKN4JHV2RV...","Sumit Nath,Aneesh Mohan,Yogesh Badekar,Manisha...","R10I6UIAQIP9TN,R2XEWWLV1LH7KX,R3J0MEY15WI71Z,R...","Sumit Nath,For the price, it is a good purchas...",Touch screen functions well .step counting is ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Noise-Bluetooth-Calling-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,B53QLB9H,Ptron newly launched force x10 bluetooth calli...,Electronics|wearabletechnology|smartwatches,1299.0,5999.0,78.0,3.3,5137.0,Bluetooth calling smartwatch make receive a...,"AH7LW3BCJBLCZTMWBOFL33UGIRBQ,AFSJYBGBY2U6KAAUR...","Anurag,Nirmal Singh,Vikas Keshavrao Vanave,K. ...","RZ7HZPPMZP6NJ,R3UU1TR7386E57,R3IX0H9MIZUJNR,R1...",just a watch not smart one... all features are...,just a watch not smart one... all features are...,https://m.media-amazon.com/images/I/41GXZy6dLI...,https://www.amazon.in/PTron-Force-Bluetooth-Sm...
1276,B53QFZPY,Ptron newly launched force x10 bluetooth calli...,Electronics|wearabletechnology|smartwatches,1299.0,5999.0,78.0,3.3,4415.0,Bluetooth calling smartwatch make receive a...,"AH7LW3BCJBLCZTMWBOFL33UGIRBQ,AFSJYBGBY2U6KAAUR...","Anurag,Nirmal Singh,Vikas Keshavrao Vanave,K. ...","RZ7HZPPMZP6NJ,R3UU1TR7386E57,R3IX0H9MIZUJNR,R1...",just a watch not smart one... all features are...,just a watch not smart one... all features are...,https://m.media-amazon.com/images/I/41k-VlGbYn...,https://www.amazon.in/PTron-Force-Bluetooth-Sm...
808,B4G2MWSB,"Lapster 5 pin mini usb cable, usb b cable,came...",Computers&accessories|accessories&peripherals|...,149.0,999.0,85.0,4.0,1313.0,mini usb cable is easy to plug and play connec...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lapster-camera-usb2-0-Ex...
419,994GFWBH,Lapster 1.5 mtr usb 2.0 type a male to usb a m...,Computers&accessories|accessories&peripherals|...,139.0,1650.0,86.0,4.0,1313.0,Plug play stable reliable connectivity sp...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/I/310WOJIrwj...,https://www.amazon.in/Lapster-Type-Cable-compu...
798,994GFWBH,Lapster 1.5 mtr usb 2.0 type a male to usb a m...,Computers&accessories|accessories&peripherals|...,139.0,999.0,86.0,4.0,1313.0,Plug play stable reliable connectivity sp...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/I/310WOJIrwj...,https://www.amazon.in/Lapster-Type-Cable-compu...

In [3712]:
df.duplicated().sum()

np.int64(54)

In [3713]:
df = df.drop_duplicates()

In [3714]:
df.loc[
    df['review_id'].isin(
        df['review_id'].value_counts().loc[lambda x: x > 1].index
    )
].sort_values('review_id')

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
774,7GVGTSLN,Wayona usb type c fast charger cable fast char...,Computers&accessories|accessories&peripherals|...,325.0,1299.0,75.0,4.2,10576.0,Fast charge data sync fast charge data tra...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Cable-Braided-Cha...
196,7F1P8KNV,Wayona nylon braided usb type c 3ft 1m 3a fast...,Computers&accessories|accessories&peripherals|...,325.0,1099.0,70.0,4.2,10576.0,Usb c to usb a data charging cable fully comp...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Charger-Samsung-G...
696,7GVGTSLN,Wayona usb type c fast charger cable fast char...,Computers&accessories|accessories&peripherals|...,325.0,1299.0,75.0,4.2,10576.0,Fast charge data sync fast charge data tra...,"AEXK37TSBFHSP2TYE63YPKETWQ7Q,AEKMVX2VDNNX4ZFXI...","Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sh...","R10365HEDURWI9,R5RP542IMC4OI,RX2HFWXTTQDTS,R26...","Nice product .,Good quality Braided cable, VFM...","Sturdy packing, good product!,Have used this b...",https://m.media-amazon.com/images/I/41J6oGU8w5...,https://www.amazon.in/Wayona-Cable-Braided-Cha...
613,B5LVS732,Noise pulse go buzz smart watch bluetooth call...,Electronics|wearabletechnology|smartwatches,1999.0,4999.0,60.0,4.1,10689.0,Sharp and bright display the 1 69 tft displ...,"AFGHRQK34D54OXQCRGX5K3XTR66Q,AHNRGHNIKN4JHV2RV...","Sumit Nath,Aneesh Mohan,Yogesh Badekar,Manisha...","R10I6UIAQIP9TN,R2XEWWLV1LH7KX,R3J0MEY15WI71Z,R...","Sumit Nath,For the price, it is a good purchas...",Touch screen functions well .step counting is ...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Noise-Bluetooth-Calling-...
70,B5LVS732,Noise pulse go buzz smart watch bluetooth call...,Electronics|wearabletechnology|smartwatches,1898.0,4999.0,62.0,4.1,10689.0,Sharp and bright display the 1 69 tft displ...,"AFGHRQK34D54OXQCRGX5K3XTR66Q,AHNRGHNIKN4JHV2RV...","Sumit Nath,Aneesh Mohan,Yogesh Badekar,Manisha...","R10I6UIAQIP9TN,R2XEWWLV1LH7KX,R3J0MEY15WI71Z,R...","Sumit Nath,For the price, it is a good purchas...",Touch screen functions well .step counting is ...,https://m.media-amazon.com/images/I/41Peg4pz7f...,https://www.amazon.in/Noise-Bluetooth-Calling-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,B53QLB9H,Ptron newly launched force x10 bluetooth calli...,Electronics|wearabletechnology|smartwatches,1299.0,5999.0,78.0,3.3,5137.0,Bluetooth calling smartwatch make receive a...,"AH7LW3BCJBLCZTMWBOFL33UGIRBQ,AFSJYBGBY2U6KAAUR...","Anurag,Nirmal Singh,Vikas Keshavrao Vanave,K. ...","RZ7HZPPMZP6NJ,R3UU1TR7386E57,R3IX0H9MIZUJNR,R1...",just a watch not smart one... all features are...,just a watch not smart one... all features are...,https://m.media-amazon.com/images/I/41GXZy6dLI...,https://www.amazon.in/PTron-Force-Bluetooth-Sm...
1276,B53QFZPY,Ptron newly launched force x10 bluetooth calli...,Electronics|wearabletechnology|smartwatches,1299.0,5999.0,78.0,3.3,4415.0,Bluetooth calling smartwatch make receive a...,"AH7LW3BCJBLCZTMWBOFL33UGIRBQ,AFSJYBGBY2U6KAAUR...","Anurag,Nirmal Singh,Vikas Keshavrao Vanave,K. ...","RZ7HZPPMZP6NJ,R3UU1TR7386E57,R3IX0H9MIZUJNR,R1...",just a watch not smart one... all features are...,just a watch not smart one... all features are...,https://m.media-amazon.com/images/I/41k-VlGbYn...,https://www.amazon.in/PTron-Force-Bluetooth-Sm...
798,994GFWBH,Lapster 1.5 mtr usb 2.0 type a male to usb a m...,Computers&accessories|accessories&peripherals|...,139.0,999.0,86.0,4.0,1313.0,Plug play stable reliable connectivity sp...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/I/310WOJIrwj...,https://www.amazon.in/Lapster-Type-Cable-compu...
419,994GFWBH,Lapster 1.5 mtr usb 2.0 type a male to usb a m...,Computers&accessories|accessories&peripherals|...,139.0,1650.0,86.0,4.0,1313.0,Plug play stable reliable connectivity sp...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/I/310WOJIrwj...,https://www.amazon.in/Lapster-Type-Cable-compu...
808,B4G2MWSB,"Lapster 5 pin mini usb cable, usb b cable,came...",Computers&accessories|accessories&peripherals|...,149.0,999.0,85.0,4.0,1313.0,mini usb cable is easy to plug and play connec...,"AF42EMTPEJAL4LNEPPX77TN77UHA,AHBMZRY43T2GTYDVN...","Pruthvi Natraj,Phani,Amazon Customer,Techdevot...","RZJR37WFGXR9B,R39X6O18GM16TM,R18ZQ09EKVWZ9R,R3...","A well-priced product.,Lenthy cord.,Product is...","i am writing this review after 2 months, the f...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Lapster-camera-usb2-0-Ex...

In [3715]:
df.duplicated().sum()

np.int64(0)

In [3716]:
df['review_id'].value_counts().loc[lambda x: x > 1]

review_id
R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,RDVX50PD4CTFE,R3H6WKG0TA5CGU,R3Q3L1KP5QWPV3,RU0LU2PAIIME,R20FTANBPFA653     10
R2K5OD0MEEBTDL,RS1N6TNO33BOK,R6KWBGOKI1N9Y,R30SKUMYLSXXDN,R1EOYHZWCRSV7B,R13JBDK4SAAYFT,RJOU5K9ECNW7Y,R2APPRANV6IERZ      8
RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU     7
R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I     7
R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1CLH2ULIVG5U3,R2DMKIBGFKBD6R,RC89B5IAJUTR5,R3B3DDON5FH8DS,R13WAEJDI5RS36     7
                                                                                                                         ..
R2ACU430AWSQ15,RZFPMZJQG4VEF,R2P7VTDLLMDOA3,R1B9M17A3N27E2,R4LNZP9RCX3H3,R3TL5BYHCMQSB3,R1B2BRD05LJZX4,R2WQKUAV6WUQ06     2
R27C4TPKHXYBRU,R1WGISGIIXAU1B,R2WFSJJW04UWJ8,R2QYC49E7WPALL,R1URJDO4NTW2ML,R3D6T949ZTO02J,RL8X7H598LEE4,RB0LBG619UMSN     2
R10KEMT1N336ZD,RL01KZO95GX4F,R1Q721FI3A7XLK,R34MTIAB8IHAI,R1LG1DNA516T7L,RFH8DR3A2O8BG,RFA922H587JFN,R10BFD806POSOX       2
R73A6T8MRDZIC,R2JEX8R7VL6Y0W,R11E62NE328JVS,R3A3FOYWKUNHMM,RIQXPCOM8RRPS,R3VCIW3UM7QMO0,R1KGLT77FP3X13,R375ZRISQJ6XN5     2
R3C219XKJW9GI2,R7KGIU29C0TLL,R3S0UMZSM6FNWM,R3MODCWX8MEIFI,RGLPAU9M85OBG,RBOERVXC2919N,R1EYK2W81FR1YN,R2QUFMWF2JX8KR      2
Name: count, Length: 146, dtype: int64

In [3717]:
df.drop(
df[df['review_id'] == 'R2K5OD0MEEBTDL,RS1N6TNO33BOK,R6KWBGOKI1N9Y,R30SKUMYLSXXDN,R1EOYHZWCRSV7B,R13JBDK4SAAYFT,RJOU5K9ECNW7Y,R2APPRANV6IERZ'].index,inplace= True
)

In [3718]:
df['review_id'].duplicated().sum()

np.int64(263)

In [3719]:
df[df['review_id'] == 'R2K5OD0MEEBTDL,RS1N6TNO33BOK,R6KWBGOKI1N9Y,R30SKUMYLSXXDN,R1EOYHZWCRSV7B,R13JBDK4SAAYFT,RJOU5K9ECNW7Y,R2APPRANV6IERZ']

Empty DataFrame
Columns: [product_id, product_name, category, Discounted_Price (INR), actual_price, discount_percentage, rating, Rating Count, about_product, user_id, user_name, review_id, review_title, review_content, IMG_LINK , product_link]
Index: []

In [3720]:
df = df.drop_duplicates(subset='review_id',keep='first')

In [3721]:
df['review_id'].value_counts().loc[lambda x: x > 1]

Series([], Name: count, dtype: int64)

In [3722]:
df.shape

(1130, 16)

In [3723]:
data.shape

(1495, 16)

In [3724]:
df['review_id'].isna().sum()

np.int64(1)

review_title : 30 missing values, remove extra spaces and unwanted symbols.

In [3725]:
df['review_title'].isna().sum()

np.int64(4)

In [3728]:
df[df['review_title'].str.contains(r'[^A-Za-z0-9,.\s]' , na=False) ]
df['review_title']=df['review_title'].str.replace(r'[^A-Za-z0-9,\s]','',regex=True)
df['review_title']

0       Strudy, Awesome connectivitybut bass is NOT up...
1       Bigger size,Superb,Vacuum Bag,Price is reasona...
2       Nice good,Easy to use,Good , however little co...
3       Good but the scroll is now damaged,Nice,Noisel...
4       Good product but attention needed in packing a...
                              ...
1490    Juicer is not effective,Ok good,Products quali...
1491    Nice product,Ok,The lid could be more sturdier...
1492    Does its job for the price,Not for music but c...
1493                                              Useless
1494    Coffee Filter,Just go for it,Happy with the pr...
Name: review_title, Length: 1130, dtype: object

In [3729]:
df['review_title'].isna().sum()

np.int64(4)

In [3730]:
df['review_title'] = df['review_title'].fillna('Unknown')

In [3731]:
df['review_title'].isna().sum()

np.int64(0)

In [3732]:
df['review_title'] = df['review_title'].str.strip()

review_content : 30 missing values, clean unwanted spaces, special characters and blank text.

In [3733]:
df['review_content']

0       The LED light is vibrant with multiple form se...
1       These are the biggest one their models use and...
2       Like it,Awesome product 😊,Follow the instructi...
3       - excellent piece of wireless mouse- reasonabl...
4       For this price range product design, look, spe...
                              ...
1490    Juicer is not effective,Ok good,https://m.medi...
1491    It's a good product for strong daily laundry c...
1492    A peculiar product in the market. Good sound q...
1493    Does not work as advertised at all. The pieces...
1494    Coffee Filter is just the right size for a sma...
Name: review_content, Length: 1130, dtype: object

In [3742]:
df.loc[df['review_content'].str.contains(r'[^A-Za-z0-9,.\s]', na=False) , ['review_content']]
df['review_content']= df['review_content'].str.replace(r'[^A-Za-z0-9,.\s]',"" ,regex=True)
df['review_content']

0       The LED light is vibrant with multiple form se...
1       These are the biggest one their models use and...
2       Like it,Awesome product ,Follow the instructio...
3       excellent piece of wireless mouse reasonable p...
4       For this price range product design, look, spe...
                              ...
1490    Juicer is not effective,Ok good,httpsm.mediaam...
1491    Its a good product for strong daily laundry cl...
1492    A peculiar product in the market. Good sound q...
1493    Does not work as advertised at all. The pieces...
1494    Coffee Filter is just the right size for a sma...
Name: review_content, Length: 1130, dtype: object

In [3739]:
df['review_content'].isna().sum()

np.int64(2)

In [3740]:
df['review_content'] = df['review_content'].fillna('Unknown')

In [3741]:
df['review_content'] = df['review_content'].str.strip()

IMG_LINK : 30 missing values, ensure all links are valid and start with https://.

In [3744]:
df['IMG_LINK ']

0       https://m.media-amazon.com/images/I/51J45Dcgkt...
1       https://m.media-amazon.com/images/W/WEBP_40237...
2       https://m.media-amazon.com/images/I/41yrqUum9E...
3       https://m.media-amazon.com/images/W/WEBP_40237...
4       https://m.media-amazon.com/images/I/31-XtyZy0I...
                              ...
1490    https://m.media-amazon.com/images/W/WEBP_40237...
1491    https://m.media-amazon.com/images/I/51CyJ9dUiW...
1492    https://m.media-amazon.com/images/W/WEBP_40237...
1493    https://m.media-amazon.com/images/W/WEBP_40237...
1494                                                  NaN
Name: IMG_LINK , Length: 1130, dtype: object

In [3745]:
df['IMG_LINK '].isna().sum()

np.int64(8)

In [3755]:
df.loc[~df['IMG_LINK '].str.contains('https:',na= False)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.00,1650.0,50.0,4.1,5137.0,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,NaN,NaN
83,8LHTJTBB,Dyazo 6 angles adjustable aluminum ergonomic f...,Computers&accessories|accessories&peripherals|...,599.00,1999.0,70.0,4.4,4736.0,Dyazo height adjusting laptop stand or laptop ...,"AGQNPJPVAIIWZMD7X5LKPA7WMQDQ,AGPJ54XLGYPWACFVE...","Sharon Murmoo,Kuldeep Sadhu,Harshavardhan B Bh...","R2VX3WP87K1FJ7,R1S6VK3U765LYF,R11EG1L6YLD853,R...","Price wise the best in Category,Laptop is not ...","Ive just started using it, i cant say much abo...",NaN,https://www.amazon.in/Dyazo-Computer-Adjustabl...
224,7Y9PY6Y1,"Sujata powermatic plus, juicer mixer grinder w...",Home&kitchen|kitchen&homeappliances|smallkitch...,6525.00,8820.0,26.0,4.5,5137.0,Warranty 1 year warranty provided by the manu...,"AHXQPNDQMOD2RJE2S6KG3CM6QRXA,AHEDAEYXIZIPVLI6H...","Arjun A,Shwetha Murthy,Rahul,Jubaida H.,Hemali...","R3MKON00OQCF7T,RACP11DCWDX8H,R2AFW2I68NL7DV,R2...","Best mixer juicer,Nice,Best product in this pr...",One of the best juicer mixer I have ever used ...,m.media-amazon.com/images/I/41yPeG8kXxL._SX300...,https://www.amazon.in/Plastic-Powermatic-Jar-J...
302,BBFJ9M3X,"Redmi 11 prime 5g (meadow green, 4gb ram 64gb ...",Electronics|mobiles&accessories|smartphones&ba...,13999.00,15999.0,13.0,3.9,2180.0,Processor mediatek dimensity 700 with 5g 7nm...,"AEJHP62NHRVRCWIMXUODSZLSBNUA,AF3U4PQTRSBX3JB6N...","Dhruvi,Sujal Negi,Nagarajan,Sreenath,Placehold...","R3KJZVGMCEDPKA,R1EU6W1X8DZQN1,R3L27Z1PJ76EKV,R...","Nice phone,15 day review,Extent,Awesome phone,...",Overall it is nice phone at this price go for...,m.media-amazon.com/images/I/41gQbaGlXrL._SX300...,https://www.amazon.in/Redmi-Meadow-Design-Dime...
321,BMGB2TPR,"Samsung galaxy m04 light green, 4gb ram, 64gb ...",Electronics|mobiles&accessories|smartphones&ba...,9499.00,11999.0,21.0,4.2,284.0,Powerful mediatek helio p35 octa core 2 3ghz w...,"AGOWF5LLDDKUJTPYF4WOO5RKT4JA,AGIJWXZQV3F5BX3NC...","Vishnu Vp,P S Agarwal,Rajesh Kumar,Rama,Vaibha...","R2RDC6R09NZ0TZ,R16LV4RNJLN09N,R3RKDGFWWFXK6U,R...","Get it with bundled discounts,Heating Touch s...",Its original price is not worth any praise so ...,m.media-amazon.com/images/I/41IcuNkyrdL._SX300...,https://www.amazon.in/Samsung-Galaxy-Storage-M...
367,7WDKLDRX,"Iqoo neo 6 5g (dark nova, 8gb ram, 128gb stora...",Electronics|mobiles&accessories|smartphones&ba...,28999.00,34999.0,17.0,4.4,20311.0,Snapdragon 870 5g mobile platform which is a 7...,"AFLMOZFV4PMKSM3JHJ7ITUT6OVBA,AE2TS2DBYLAJ5WY6F...","Goutham Giridhar Kamath,Antara M.","R1X7186WUECR3,RIXG2KYOQHKVB","Lets bust some myth,IQOO Neo 6 5G A midrange ...",I ordered this phone based on specs it was pro...,m.media-amazon.com/images/I/51DLLa8HNWL._SX300...,https://www.amazon.in/iQOO-128GB-Storage-Snapd...
378,9Z7YGV3R,Anjaney enterprise smart multipurpose foldable...,Computers&accessories|accessories&peripherals|...,269.00,699.0,62.0,4.0,93.0,Large stable portable folding table the fol...,"AGSPAJCL6J6YDXIAPE76RI7HR5AA,AFU6BZRZSMJBHGEYA...","Varshini Mani,Giri Babu,Priyanka Singh,Geethan...","R3VZ6Z283J13QS,R1A8F37C7OKF8,R2RQS98AMZ4NJG,R1...","Honest review,Cushion grip is coming out,Mast ...",Yeah here is the honest review.... Looking goo...,m.media-amazon.com/images/I/51ucu0nCeSL._SX300...,https://www.amazon.in/Anjaney-Enterprise-Multi...
541,7GLSKXS1,Kent 16026 electric kettle stainless steel 1.8...,Home&kitchen|kitchen&homeappliances|smallkitch...,1199.00,1950.0,39.0,3.9,2832.0,1 8l kent electric kettle ss is an ideal pick ...,"AEDOY7QSF22AYSFDSBF32NURIY3A,AE4GETIZXRFI5D7IX...","Rattan Lal Narula,Dibyalochan Dutta,Amazon Cus...","R3JRCWMWKXH9IB,R3G026EMLP0VS7,R24JJEFAXZH2J6,R...",The base unit is rather flimsy could have been...,The base Unit is rather flimsy Could have been...,m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Kent-16026-1-8-Liter-Ele...
599,09P2LK08,Bajaj minor 1000 watts radiant room heater (st...,"Home&kitchen|heating,cooling&airquality|roomhe...",749.00,1129.0,34.0,4.0,2446.0,Radiant warmth ideal for use in in small room...,"AHQKNH5JPOQWCNN2ZCUK34VEJAKQ,AEFYKJA3MREFE47PS...","Anil. Kumar,Rohit Y.,Amazon Customer,Chandra S...","R2Z21OHZH69ASO,R3SYP2PI42JEC,R2YFP1LKOMNN5J,R3...","Poor packaging,Nice products,Good,Spr,Worth to...",2 ...,m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Bajaj-Minor-1000-Watt-Ro...
733,9Z28BQZT,Amazon basics multipurpose foldable laptop tab...,Computers&accessories|accessories&peripherals|...,599.00,3999.0,85.0,3.9,1087.0,You can use the table as a study table breakf...,"AFJXIJRSFMMNTYMOGJK7EE5XNRAA,AHPNKUIAW65N46LJ6...","Arun J,Sebonti Banerjee,Srikar,Mayu,Neeraj Jos...","R1IF6OX5EMCHRA,R11D9Q1R128JAS,RYHX3VX289G1,R19...","Good product but little costly,Very sturdy and...",If you are using a seperate mouse go without c...,m.media-amazon.com/images/I/315g5ipEPAL._SY300...,https://www.amazon.in/Amazon-Basics-Multipurpo...
754,7RX14W1Q,Amazon basics 10.2 gbps high-speed 4k hdmi cab...,"Electronics|hometheater,tv&video|accessories|c...",499.00,900.0,45.0,4.4,2165.0,1 82 m high speed premium hdmi cable for trans...,"AGT2U62GEVEA2CAXYALEPKOKBLAQ,AHQ5G6EGXY74B4KQM...","Willgo Green,Chittibabu,Deepak Dhummansure,Ama...","R2BR9VTFE775OW,R3V8S6MZGP7QAL,R1OQW9NGBM2EHB,R...","Sturdy,Super,Working good,Always go for qualit...",Works well. Sturdy built and good quality. Onl...,NaN,https://www.amazon.in/AmazonBasics-High-Speed-...
822,BBW521YC,Lapster 12pcs spiral cable protectors for char...,Electronics|mobiles&accessories|mobileaccessor...,99.00,999.0,90.0,4.4,305.0,Spiral tube charging cable protector are desig...,"AEJSMM2J65DGILOOHC24C74VWPBA,AFC4X5UHL2LN4PBS2...","Mihir Deshpande,Sejal Ghuge,Sm,Pavan,Mallikarj...","R173QPQASTIM5E,R2RU5623DZ9ZWI,R16QI7DHVXJVCI,R...","Its OK,Useful product,All peices arrived,Good ...","Doesnt always stay at the neck of the cable, b...",m.media-amazon.com/images/I/41WYWN1pdvL._SX300...,https://www.amazon.in/LAPSTER-Protectors-Charg...
845,77T3BG5L,Zebronics zeb-km2100 multimedia usb keyboard c...,Computers&accessories|accessories&peripherals|...,329.00,399.0,18.0,3.6,33735.0,Superior built quality the keyboard has a sup...,"AHJRPRAXBOIRLYMCRQ4HCACPXDVQ,AH5G5ENXXWLJAEJMD...","Sagarjit,Balvant Ghanekar,Rohit,Natesa Pillai ...","R3I9ZZITI5NO9G,R2AO8Y28HYFSGN,RVJ7OESUFXN6U,R1...","Keys got hard after 2 months usage,Temporary b...",The product is very good. Keya are ergonomic. ...,m.media-amazon.com/images/I/41XQP3N-SdL._SX300...,https://www.amazon.in/Zebronics-Km2100-Multime...
898,75S9FVRY,"Sujata supermix, mixer grinder, 900 watts, 3 j...",Home&kitchen|kitchen&homeappliances|smallkitch...,5490.00,7200.0,24.0,4.5,1408.0,Warranty 2 year warranty provided by the manu...,"AEZWAAKKFCXMULYUT7J5ZD3RGU5A,AFFU3N2R3CXUIL4HQ...","Ramaan Singh,Rajesh Sharma,Chandra Bhushan,Afr...","R1CZUTGXQ7ZX2T,R2D6O5GY374HUI,R3MEVKMG43JO84,R...","Nanis choice is still valid,Good,Value for mon...",I have been listening about Sujata mixer grind...,m.media-amazon.com/images/I/41wCglxg9qL._SX300...,https://www.amazon.in/Sujata-Supermix-AM-007-W...
950,83RC4WFJ,Prettykrafts laundry bag / basket for dirty cl...,Home&kitchen|homestorage&organization|laundryo...,320.00,799.0,60.0,4.2,3846.0,Made in india prettykrafts laundry bin is ligh...,"AHYKYPQWG6D57RWV5BGGMKG6D6WA,AG4HU2P24AVEA5DIV...","Nidha,Prakasha T K,Hitesh Jangra,Shreeja,Isha ...","R1BE774NJ5R2DX,R1U4G4C65P8D4G,R2WMQC1KWG94P7,R...","Good for the price,Good product,Good Deal,Defe...","Good one for usability,Its value for money. Co...",NaN,https://www.amazon.in/PrettyKrafts-Canvas-Laun...
958,7RD611Z8,Ambrane 20000mah power bank with 20w fast char...,Electronics|mobiles&accessories|mobileaccessor...,1799.00,2499.0,28.0,4.1,18678.0,Massive 20000mah lithium polymer capacity allo...,"AFAKEZV7KMVT2SGF4KYWXGQRIW4A,AE33MAZWYRVAAICGN...","Vikrant,Ganesh Gholap, Pushpendra Singh Patel ...","R3C219XKJW9GI2,R7KGIU29C0TLL,R3S0UMZSM6FNWM,R3...","Decent Product at about right price,Seems good...",I bought this powerbank to use during my vacat...,m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Ambrane-20000mAh-Lithium...
1122,B31FR4Y2,"Boult audio omega with 30db anc+ enc, 32h play...","Electronics|headphones,earbuds&accessories|hea...",1999.00,9999.0,80.0,3.7,1986.0,Note if the size of the earbud tips does not...,"AF5VUXGXGK7JT2XRO7HGTFDQY5OA,AEIXBTPYBR47FGHAX...","Anand Kadu,Toney Abraham,Subhajit Kansa Banik,...","R2IMML4LPCQ5C0,R24NQRDGFWSFO8,R2ONXP5WQXARB6,R...","Fits well in ears,Controls Performance backu...",Audio quality is good for this price range. Th...,m.media-amazon.com/images/I/41sEmULXfAL._SX300...,https://www.amazon.in/Boult-Audio-Equalizer-Ca...
1162,0SH18114,Ikea 903.391.72 polypropylene plastic solid be...,Home&kitchen|kitchen&homeappliances|smallkitch...,160.00,299.0,46.0,4.6,2781.0,30 units perfect to seal food snack keep food ...,"AE7M7M6QTDYEHQKAKXIWO2OVMBXQ,AESSDAJQCU3XKBAGY...","Dr. Balasubramanian Pechimuthu,Abdul Rehman,S...","R1NAAWWJ35RMQR,R3S2CEY1ZBAKJJ,R38NYOW9S7HMO0,R...","It is Okay,Amazing product and fast shipping,S...","It is Okay so far.,This product was amazing an...",m.media-amazon.com/images/I/41k+HQz9JbL._SX300...,https://www.amazon.in/Ikea-903-391-72-Sealing-...
1223,7JF9B592,Maono au-400 lavalier auxiliary omnidirectiona...,Musicalinstruments|microphones|condenser,478.00,699.0,32.0,3.8,20218.0,4 pole jack is compatible for laptop which has...,"AHQ4Q75NBEWOM4OWOXUZW7V247NQ,AEQCAMSZJTMNIKXAP...","82 ,Manish Rautela,Sai Kiran,Dinesh S,Uttam,Sh...","RKBKQKSEET7CC,RQM34GWJC0DPJ,R1PJNXT9PME2I1,R2V...","loud clear,Avrage in budget range,Best for be...",at Rs.319 its a great deal. I use it for mobil...,m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Maono-AU-400-Lavalier-Mi...
1230,8Y57TPDM,"Duracell cr2016 3v lithium coin battery, 5 pcs...",Electronics|generalpurposebatteries&batterycha...,116.00,200.0,42.0,4.3,485.0,Duracell 2016 lithium coin batteries are suita...,"AG6WNF3AQBACEWDTRW6UM2MALT2A,AGDX3YMAIQMEVYPEJ...","Suraj,Nilesh,Pawan,Deepak Singh,Nikhil Chaudha...","RKDNXHI6GT6UZ,R2665SN6A29V01,R2J30R8O3UHZRI,R3...","Good product ,5 bati,Charge seems to be very l...",",1 bati , 5 bati,Voltage and performance is no...",m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Duracell-Chhota-Power-Co...
1250,9J2SCVQT,Nutripro juicer mixer grinder - smoothie maker...,Home&kitchen|kitchen&homeappliances|smallkitch...,1969.00,5000.0,61.0,4.1,4927.0,Make smoothies and juices within seconds also...,"AFBHLRTSYYAZ2IGMVF2BNV6ZPG3A,AEVRNHFUTYUHFVYZI...","Dharshnaselvan,Saiashwanth.M,Dr. Arshi Siddiqu...","R1B9F9IRGMO01I,R1RO3J9EEFFHMF,RLXVHHR81VC4Q,R2...","Used almost for a month,User friendly product ...",ProsCan use for preparing pure and small porti...,NaN,https://www.amazon.in/NutriPro-Bullet-Juicer-G...
1396,0EDJJ7FS,Philips viva collection hd4928/01 2100-watt in...,Home&kitchen|kitchen&homeappliances|smallkitch...,3229.00,5295.0,39.0,4.2,39724.0,Philips domestic appliances is asia s most tru...,"AFVKRRAFQOO6G7UIAK6H44N3AHUQ,AEDG2D2EUJBTRXOTX...","Icu,Pavish,Krrish Kumar,Vit Bernatik,Sanjay 62...","R20RA7F53RKEWU,RX5JXI5MY648T,R1P43OQ1EQ8EIT,R1...","Product as describe,Good product,Good product ...",I recvd product within 3 dys while owing to ru...,NaN,https://www.amazon.in/Philips-Collection-HD492...
1415,0GGGOYEK,Storite usb 2.0 a to mini 5 pin b cable for ex...,Computers&accessories|accessories&peripherals|...,259.00,699.0,63.0,3.8,2399.0,Make plug and play connections with mobile pho...,"AFHX6LN2EGRSLCIKZERTK236KJWA,AGM6VKOVQWLVZW5NX...","Angsuman Dutta,Amjath Sp,Amazon Customer,Utpal...","R7CW64V48YJHE,R185CPLU005RPS,R2R70NKW75DZAS,R3...","Useful but the length is a bit short,This prod...",Product is good but the length of the wire is ...,m.media-amazon.com/images/W/WEBP_402378-T2/ima...,https://www.amazon.in/Storite%C2%AE-USB-2-0-Mi...
1442,9V12K8NT,"Boat wave lite smartwatch with 1.69"" hd displa...",Electronics|wearabletechnology|smartwatches,1499.00,6990.0,79.0,4.1,21797.0,Screen size the 1 69 inch hd full touch displ...,"AFHFQB5UN57HBBYIGBV4YYZDXSZQ,AGPBZBEFPFL64PWRZ...","Aby Jimson,Prasad Pavithran,Mahesh Chandra K M...","R19QUEKHANF087,R2CU03OULJTK2A,R1SHVTKMHHOREL,R...","Overall good except connectivity,Ideal Product...",The watch works fine. Good touch screen and ov...,NaN,https://www.amazon.in/boAt-Wave-Lite-Smartwatc...
1453,0GHL8VP2,Usha 1212 ptc with adjustable thermostat fan h...,"Home&kitchen|heating,cooling&airquality|roomhe...",3487.77,4990.0,30.0,4.1,5137.0,Meant for spot heating room size upto 15 sq f...,"AECFYIUCHSZXDLACTYPEUSM5DIKA,AF546S43YKYCJWRD7...","Manoj Kumar,Arun Thottakathu Prasannakumar,Son...","R1T19FVDX8Z7T2,R1E1AMYN17K7HJ,R20AXB80IQO0DK,R...","I like this product,Simple easy to use, but no...",",Cost effective. This is good for heating your...",m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Usha-1212-PTC-Adjustable...
1470,746N6WML,Parker vector camouflage gift set - roller bal...,Officeproducts|officepaperproducts|paper|stati...,341.00,450.0,24.0,4.3,2493.0,This charming looking pen is made up of abs pl...,"AFVTO4K2IG5AYWZPOAEA2QGPZZ4A,AHWTCTHLUKPJP2IUI...","Good,Aayush,Nupur Gupta,Gunjan Sengupta,Syed T...","R37OWPWWYU7L3G,R2AQ3J8DYODY55,RA0RPO7G5XXOL,R1...","Good,Made for special ones,Good Product,Awesom...","Good,Amazing,Nice pen and keychain,I just live...",m.media-amazon.com/images/W/WEBP_402378-T1/ima...,https://www.amazon.in/Parker-Vector-Camouflage...
1476,0GZLB57U,Quantum rj45 ethernet patch cable/lan router c...,Computers&accessories|accessories&peripherals|...,238.00,699.0,66.0,4.4,8372.0,Quantum cat5 ethernet patch cord rj45 lan stra...,"AEMEBARDKUUI7MQSY2HXMC2DCT4A,AH36CGQ26U2XBH5AO...","Parenky Amaresha Adhikari,Hiren Panchal,Amol,G...","R1ORJ2TKW4MHLY,R1ENNLA4ML94UZ,R2BTEV9E0OA1I7,R...","Good product,4 star overall,Good, nice worth i...","Using since last two weeks .,Good,Good, nice...",m.media-amazon.com/images/W/WEBP_402378-T2/ima...,https://www.amazon.in/Quantum-Ethernet-Patch-S...
1494,0PVT30YI,Kitchen mart stainless steel south indian filt...,"Home&kitchen|kitchen&homeappliances|coffee,tea...",292.00,499.0,41.0,4.1,4238.0,Material food grade stainless steel make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,Meena Polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it,Happy with the pr...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3748]:
df['IMG_LINK '].shape

(1130,)

In [3760]:
mask = df['IMG_LINK '].notna() & ~df['IMG_LINK '].str.startswith('https://',na=False)
df.loc[mask,'IMG_LINK '] = 'https://' + df.loc[mask , 'IMG_LINK ']

In [3761]:
df.loc[~df['IMG_LINK '].str.contains('https:',na= False)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,NaN,NaN
83,8LHTJTBB,Dyazo 6 angles adjustable aluminum ergonomic f...,Computers&accessories|accessories&peripherals|...,599.0,1999.0,70.0,4.4,4736.0,Dyazo height adjusting laptop stand or laptop ...,"AGQNPJPVAIIWZMD7X5LKPA7WMQDQ,AGPJ54XLGYPWACFVE...","Sharon Murmoo,Kuldeep Sadhu,Harshavardhan B Bh...","R2VX3WP87K1FJ7,R1S6VK3U765LYF,R11EG1L6YLD853,R...","Price wise the best in Category,Laptop is not ...","Ive just started using it, i cant say much abo...",NaN,https://www.amazon.in/Dyazo-Computer-Adjustabl...
754,7RX14W1Q,Amazon basics 10.2 gbps high-speed 4k hdmi cab...,"Electronics|hometheater,tv&video|accessories|c...",499.0,900.0,45.0,4.4,2165.0,1 82 m high speed premium hdmi cable for trans...,"AGT2U62GEVEA2CAXYALEPKOKBLAQ,AHQ5G6EGXY74B4KQM...","Willgo Green,Chittibabu,Deepak Dhummansure,Ama...","R2BR9VTFE775OW,R3V8S6MZGP7QAL,R1OQW9NGBM2EHB,R...","Sturdy,Super,Working good,Always go for qualit...",Works well. Sturdy built and good quality. Onl...,NaN,https://www.amazon.in/AmazonBasics-High-Speed-...
950,83RC4WFJ,Prettykrafts laundry bag / basket for dirty cl...,Home&kitchen|homestorage&organization|laundryo...,320.0,799.0,60.0,4.2,3846.0,Made in india prettykrafts laundry bin is ligh...,"AHYKYPQWG6D57RWV5BGGMKG6D6WA,AG4HU2P24AVEA5DIV...","Nidha,Prakasha T K,Hitesh Jangra,Shreeja,Isha ...","R1BE774NJ5R2DX,R1U4G4C65P8D4G,R2WMQC1KWG94P7,R...","Good for the price,Good product,Good Deal,Defe...","Good one for usability,Its value for money. Co...",NaN,https://www.amazon.in/PrettyKrafts-Canvas-Laun...
1250,9J2SCVQT,Nutripro juicer mixer grinder - smoothie maker...,Home&kitchen|kitchen&homeappliances|smallkitch...,1969.0,5000.0,61.0,4.1,4927.0,Make smoothies and juices within seconds also...,"AFBHLRTSYYAZ2IGMVF2BNV6ZPG3A,AEVRNHFUTYUHFVYZI...","Dharshnaselvan,Saiashwanth.M,Dr. Arshi Siddiqu...","R1B9F9IRGMO01I,R1RO3J9EEFFHMF,RLXVHHR81VC4Q,R2...","Used almost for a month,User friendly product ...",ProsCan use for preparing pure and small porti...,NaN,https://www.amazon.in/NutriPro-Bullet-Juicer-G...
1396,0EDJJ7FS,Philips viva collection hd4928/01 2100-watt in...,Home&kitchen|kitchen&homeappliances|smallkitch...,3229.0,5295.0,39.0,4.2,39724.0,Philips domestic appliances is asia s most tru...,"AFVKRRAFQOO6G7UIAK6H44N3AHUQ,AEDG2D2EUJBTRXOTX...","Icu,Pavish,Krrish Kumar,Vit Bernatik,Sanjay 62...","R20RA7F53RKEWU,RX5JXI5MY648T,R1P43OQ1EQ8EIT,R1...","Product as describe,Good product,Good product ...",I recvd product within 3 dys while owing to ru...,NaN,https://www.amazon.in/Philips-Collection-HD492...
1442,9V12K8NT,"Boat wave lite smartwatch with 1.69"" hd displa...",Electronics|wearabletechnology|smartwatches,1499.0,6990.0,79.0,4.1,21797.0,Screen size the 1 69 inch hd full touch displ...,"AFHFQB5UN57HBBYIGBV4YYZDXSZQ,AGPBZBEFPFL64PWRZ...","Aby Jimson,Prasad Pavithran,Mahesh Chandra K M...","R19QUEKHANF087,R2CU03OULJTK2A,R1SHVTKMHHOREL,R...","Overall good except connectivity,Ideal Product...",The watch works fine. Good touch screen and ov...,NaN,https://www.amazon.in/boAt-Wave-Lite-Smartwatc...
1494,0PVT30YI,Kitchen mart stainless steel south indian filt...,"Home&kitchen|kitchen&homeappliances|coffee,tea...",292.0,499.0,41.0,4.1,4238.0,Material food grade stainless steel make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,Meena Polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it,Happy with the pr...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [3764]:
df['IMG_LINK '] = df['IMG_LINK '].fillna('Unknown')

In [3765]:
df['IMG_LINK '].isna().sum()

np.int64(0)

In [3766]:
df['IMG_LINK '].dtype

dtype('O')

In [3768]:
df['IMG_LINK '].str.contains('https:').sum()

np.int64(1122)

In [3769]:
df['IMG_LINK '].shape

(1130,)

product_link : 30 missing values, ensure all links are valid and remove broken URLs.

In [3781]:
df['product_link']
df['product_link'].str.contains('https:').sum()

1097

In [3776]:
df.loc[~df['product_link'].str.contains('https:',na=False)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
11,7YNTJ8ZM,Zebronics zeb-county 3w wireless bluetooth por...,Electronics|homeaudio|speakers|bluetoothspeakers,549.0,999.0,45.0,3.9,64705.0,Zeb county is a compact and handy portable spe...,"AFQ44B5ISCXUWKFHZL7HTRTYWZKA,AF3IECP2JCTQZRF55...","Bhuwaneshwar Kathlane,Jainit Mukeshbhai Chauha...","R2SK5PPC2ZKCL5,RD7IHEAUK0KA6,R32GOT9K2GCKQG,R2...","To good,Build material,Super,Good product,Budg...",Bahut hi achha product hai badhiya saund and b...,https://m.media-amazon.com/images/I/41goRo3UXh...,www.amazon.in/Zebronics-Zeb-County-Bluetooth-S...
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,NaN
17,9TWHTBKQ,"Samsung galaxy m33 5g (mystique green, 8gb, 12...",Electronics|mobiles&accessories|smartphones&ba...,18499.0,25999.0,29.0,4.1,22318.0,Exynos 1280 octa core 2 4ghz 5nm processor wit...,"AHJJY3GFDJFTDTX5536IMIXVNCNQ,AEYIVONPYGGVCE7K4...","Atulya Sinha,Sujayz","R36UIGIQWYOKT,RISUCL5YV9EZN","THE PERFECT PHONE FOR MY REQUIREMENTS,Galaxy ...",I would not consider buying an iphone simply b...,https://m.media-amazon.com/images/I/41t61osAZH...,www.amazon.in/Samsung-Mystique-Storage-Purchas...
18,B84KSH3X,Wipro vesta 1200 watt gd203 heavyweight automa...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",1049.0,1950.0,46.0,3.8,250.0,Heavy performance dry iron 1200 watt to back...,"AH7OT4IUCAKFYCPJ3SVLAHV7E2YA,AGONNWZMRQZR2JDLN...","S.Saravanan,Mukesh,Sanjay Kumar,Khadar Badha,M...","R2HFE6XNQS0UP8,R2BSCK1PAXQ5NH,RZPZS0APQWNRT,R1...","Good,Seems to be good,Good,Fake replacementthe...","New atavanc,Seems to be reasonable hot and hea...",https://m.media-amazon.com/images/I/41+HYuF5To...,NaN
63,B9XN9S3W,Acer 80 cm (32 inches) n series hd ready tv ar...,"Electronics|hometheater,tv&video|televisions|s...",7999.0,14990.0,47.0,4.3,457.0,Resolution hd ready 1366 x 768 refresh ra...,"AFXQSBDW6232K22UMJWF5PMYX5RQ,AG4IENR3HNMEINBTJ...","Arun Kumar A V,Ankesh Kumar Pandit,Pradeep,Lim...","R3FTW5HNPCX66C,RM7IFDV9KNC2O,RK9JKA9U9LZ49,R15...","Value for Money,Good product,Great excellent p...",Regarding rate I liked very much and reasonabl...,https://m.media-amazon.com/images/I/51FicDnawa...,www.amazon.in/Acer-inches-Ready-AR32NSV53HD-Bl...
74,96YCN3SD,Lifelong llek15 electric kettle 1.5l with stai...,Home&kitchen|kitchen&homeappliances|smallkitch...,549.0,1000.0,45.0,3.6,1074.0,Stainless steel body concealed element and si...,"AHM4ZOXDCO5UNP4WQUXKP4NWX64A,AGHJ3BRARYIXJRGPK...","Kiran Jot,Salman Ahmad,Neelam Rawat,Nawaz Akht...","R2QR5PM0ELMWD3,RZFX345XRS4V2,R352PKGSDAV1AW,R1...","Well over all iits nice, make sure the lid of ...","Well over all iits nice, make sure the lid of ...",https://m.media-amazon.com/images/W/WEBP_40237...,NaN
150,8MV82R99,bajaj waterproof 1500 watts immersion rod heater,"Home&kitchen|heating,cooling&airquality|waterh...",653.0,1020.0,36.0,4.1,3366.0,Power 1500 watts warranty 2 year warranty on...,"AGIVW6YDF6G7356WR2KBPADPKE7A,AEOVPFUZZRU7EA3ZJ...","Vivek Koushik,Dilavar Dn,Soumya,Prosenjit Dutt...","R2J2IOT0TNI4A3,R1QZAKLANOSUFY,R14AS7M62D2KQM,R...","Highly time consumption,Slowly,Its good,The co...","Road Heater 20 . , 5...",https://m.media-amazon.com/images/I/31XMh-zc1I...,www.amazon.in/Bajaj-Waterproof-Watts-Immersion...
163,82T6GVLJ,Amazon basics new release nylon usb-a to light...,Computers&accessories|accessories&peripherals|...,849.0,1809.0,53.0,4.3,6547.0,Added protection an additional layer of prote...,"AGD3F3J523RVZPEJGZE7WPFJXONA,AFAKUEWJWYAKREBPX...","Ananya S.,Anirban Pramanick,Aashuthosh,Savita,...","R19CZW6DWGE2WH,R23RHEY0ZRAT67,R14H0NECRS2LAV,R...","Exchange of the cable,Go for it ,It works and ...",I wanted a long cable but this is short just w...,https://m.media-amazon.com/images/I/31kw1RgU5y...,www.amazon.in/AmazonBasics-Nylon-Braided-Light...
191,B5GJRTHB,Wecool moonwalk m1 enc true wireless in ear ea...,"Electronics|headphones,earbuds&accessories|hea...",889.0,1999.0,56.0,4.2,2284.0,We have designed the enc earbuds to provide ex...,"AGMD2UVAWOKO3W37KGZWAPI3ZB6A,AG7BC5ADBMW6EMTNH...","Siddhesh S.,Karthik,Vikram Kanth,Dhanesh,Rani,...","R1R1JK1E1KZYX8,R2XZC0TY29XVLD,R10HYVIHZWKK1K,R...","Great Customer care experience,Best in budget ...",I ordered this product 1 week ago on Amazon bu...,https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Moonwalk-Wireless-Titanium-Exper...
207,7QCWY5XV,Mobilife bluetooth extendable selfie stick wit...,Electronics|mobiles&accessories|mobileaccessor...,599.0,1399.0,57.0,4.1,14560.0,hate it when carry a heavy selfie stick yep ...,"AHYXJP46LXOTLZ5FXX53OWHFNWXA,AGJH265WIJJRU5CH6...","Harshwardhan Shinde,Amit,Aamtech2,Apurv G.,Ram...","R3EUHZXX3UEYSH,R1UYMUD8SY2H9V,R1BQTJ4030NWYZ,R...","Best selfie stick,Decent product with one draw...","I really appreciate the build quality,Over all...",https://m.media-amazon.com/images/I/41vCOAeGvS...,www.amazon.in/Hoteon-Mobilife-Bluetooth-Extend...
239,14SZO90Y,"Duracell ultra alkaline aa battery, 8 pcs",Electronics|generalpurposebatteries&batterycha...,266.0,315.0,16.0,4.5,28030.0,Lasts up to 100 longer longevity performan...,"AF37SWB5BJAXD6F2Q74M6HJIHADA,AFP7XI3X4GGJVQCYY...","Gopinathan,Punaram Chutia,Amazon Customer,Sree...","R31X4I2TGYDUN8,R27PTCIK04AE46,R23U630I51IZTI,R...","Thats a nice one,Best services,V good less pri...","Nice one, tried on remote mouse and found work...",https://m.media-amazon.com/images/W/WEBP_40237...,NaN
240,9RWQ7YR6,Mi 138.8 cm (55 inches) 5x series 4k ultra hd ...,"Electronics|hometheater,tv&video|televisions|s...",46999.0,69999.0,33.0,4.3,21252.0,Note the brands mi and xiaomi are part of ...,"AGTBGMKWQPUZJ2GA2XPICHD2VTKQ,AF3TVTF3FVMHGLCA2...","Amazon Customer,Rampratap Singh,Arjun Vaidya,A...","R19JWR6NN6DMRW,R3NNMZRL819Q5I,R27MVISBFA27B0,R...","Its super,Value of money ,Display and build,Go...","Its very good peace what I read.,Institutions ...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/138-8-inches-Ultra-Android-L55M6...
361,9GFLXVH9,"Redmi 9a sport (coral green, 2gb ram, 32gb sto...",Electronics|mobiles&accessories|smartphones&ba...,6499.0,8499.0,24.0,4.1,313836.0,Processor mediatek helio g25 octa core up to...,"AF7B5AJJZP2WKRD74Z45L7YDOEHA,AGEYI2JEUE752XDEX...","Roshan Renji Cherian,Sivavaraprasadpv,Kranthi,...","RCP907FSHW2CI,R2XSNFIDSF8IL4,R2JB9PO5MV9LER,R1...","Best phone for below normal use,Good mobile fo...",If you want a smart phone for just the use of ...,https://m.media-amazon.com/images/I/41i7LM0pGw...,www.amazon.in/Redmi-9A-Sport-Octa-core-Process...
397,756KCV5K,Prestige pic 15.0+ 1900-watt induction cooktop...,Home&kitchen|kitchen&homeappliances|smallkitch...,3180.0,5295.0,40.0,4.2,6919.0,Concealed and feather touch buttons anti magne...,"AHSGCVKHDAXRUG4R7V3RB6WYLZCQ,AHFTHBS5KCQWNQIYB...","Ashfak Khan,Uday,Amazon Customer,Birendra Rai,...","R2QMIAMI841PRB,R13ESBS8Z3WZG0,RZ8HXGE2HU1O,R39...","Bad servisec,a bit costly,Favourite,Thankyou a...",Work nahi kar raha sahi karwane ke liye call n...,https://m.media-amazon.com/images/I/41jv4fqU1E...,www.amazon.in/Prestige-PIC-15-0-1900-Watt-Indu...
466,9VGKFM7Y,Amazon basics 2 amp usb wall charger & micro u...,Electronics|mobiles&accessories|mobileaccessor...,219.0,499.0,56.0,4.4,14.0,Durable wall charger with fast charging abilit...,"AFQ7AUYJOIE2HH63KIUQK45ENQ2A,AHT7TTZ5JOTUL7CYS...","Prabhanjan,Chittiprolu Ramya,Litu Prasada Mahanty","R33M2Q7OES3GBK,R125QF7WMZW3NW,RMDVRDSEK73L8","Quality product,Excellent, its fast charging,A...",Product works well and charges the devices in ...,https://m.media-amazon.com/images/I/31poWDDorO...,NaN
471,9GYBZPHF,"Lifelong llmg93 500 watt duos mixer grinder, 2...",Home&kitchen|kitchen&homeappliances|smallkitch...,1149.0,2499.0,54.0,3.8,4383.0,2 jars liquidizing jar 1 25 litres and chutn...,"AEMDF6YAXYO7WQUIAFGEULA7NWWQ,AE44R623GFX6JWJVR...","Ruhi A.,Kashish Vardhan,Shankar Majumdar,Amazo...","R3LQ2TPKG42KG8,R1MWKBSQIK2J04,RWB0U0JJ3NG4J,R3...","Good onei liked it,Very rare noise,Very easy t...","i am a student, I needed it to carry abroad. I...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Lifelong-LLMG93-Stainless-Liquid...
738,13B2WGT6,Healthsense chef-mate ks 33 digital kitchen we...,Home&kitchen|kitchen&homeappliances|smallkitch...,1099.0,1899.0,42.0,4.3,5137.0,Multiple units the chef mate ks 33 kitchen sc...,"AE5LEWHQDGISBMSHQ3QRHVAO5ROQ,AHFZEHT2WQTE2ZR4S...","Aditi,Minnaz Rehman,Sourabh Karambelkar,Dhruv ...","R3W4R95XAZYMHH,R2YRO4XIULCK99,R1ZVNKQLPAUPBF,R...",Very light weight Almost accurate measurements...,It has a option of extended warranty for 6 mon...,https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Health-Sense-Chef-Mate-Digital-S...
778,0SMFPJG0,"Kent gold, optima, gold+ spare kit",Home&kitchen|kitchen&homeappliances|waterpurif...,649.0,670.0,3.0,4.1,7786.0,Color white for gold gold kool star and o...,"AH6L4HL7SHZ5FT3XJRTBG4VRQDDQ,AHM3BEM5TLDWOMRDA...","Shivraj,Subham,Yedukondalu,Mohd Mohsin,Jagdish...","R3K3LMO7VBZ15E,RIMQ7KGAFAY45,R1KDTPUO1RHWGT,RN...","Good quality, plz add 1 syringe with this kit,...","Quality very good, but 1 injection syringe mus...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Kent-Gold-Optima-Spare-Kit/dp/B0...
789,8SKZ2RMG,Demokrazy new nova lint cum fuzz remover for a...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",475.0,999.0,52.0,4.1,1021.0,Quick and efficient switch to turn it on and g...,"AE7RG5GRVSLRP2HGPKIF2JJ7BAHQ,AFCDHTYGHMNLNK2S3...","Vipin,Bhavana Rangarajan,Raj,Dimple Aggarwal,J...","R2TBG87E7UU7IT,R8OA8PY28PACZ,R3PAX3XE02N0SU,R1...","Good,Its a good product Go for it,Easy to use,...",Plastic is not of very good quality thought bu...,https://m.media-amazon.com/images/W/WEBP_40237...,NaN
836,7VZYMQNZ,"Borosil rio 1.5 l electric kettle, stainless s...",Home&kitchen|kitchen&homeappliances|smallkitch...,1180.0,1440.0,18.0,4.2,1527.0,Concealed heating element for easy cleaning do...,"AFQWELRSJ2U4E2GUXWDKEGNYOGJA,AEHD5BWCDLH2JHNRT...","P C Joshi,Amazon Customer,Pranav,Shashi Bala,P...","R3BXPMFHV4SWWY,R38TTJ6VHIUZWV,RWDME913KW45B,R1...","Excellent product,Great Quality,Good,V good pr...","Usefull for hostal,Borosil Omni kettle is of g...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Borosil-Rio-1-5L-Electric-Kettle...
870,162LYSFS,"Boat ltg 500 apple mfi certified for iphone, i...",Computers&accessories|accessories&peripherals|...,799.0,1749.0,54.0,4.1,5626.0,Spaceship grade aluminium cable casing ensures...,"AFM3PEUDKST5I4ABCDADACT6UJCQ,AHIWDTUXZ2KUNE2BA...","Harihara,Manish Singh,Parmar K.,Sibi Kumar,Man...","R39DB3OJGB156P,R3SS4A3ZPHNIS3,R35PA44HZ71501,R...","Worst product wornout after 2 months,Good prod...","Product is not working after 2 months,Boat,Nic...",https://m.media-amazon.com/images/I/41VKU5Lkg3...,www.amazon.in/LTG-500-2Mtr-Cable-Metallic-Silv...
928,91V8HK8Z,Milton go electro 2.0 stainless steel electric...,Home&kitchen|kitchen&homeappliances|smallkitch...,1345.0,1750.0,23.0,3.8,2466.0,Electric kettle is a handy appliance that make...,"AHA3JEZZDQPHSAYB2HWK5HNPXHIA,AEC4LE3IVY4QZXX2Z...","Raunak Kumar,Shubham Oli,Paresh Ahire,Suryansh...","R2WPRTHSHZCDS5,R2W0ORTQOGIIZF,RIBJBDPVX394D,R3...","Good at this budget,Good product,Cord length,C...",httpsm.mediaamazon.comimagesWWEBP402378T2image...,https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Milton-Electric-Stainless-Kettle...
944,9PNR6F8Q,Realme 10w fast charging micro-usb cable (brai...,Computers&accessories|accessories&peripherals|...,249.0,399.0,38.0,4.0,5137.0,Realme s 10w micro usb cable is compatible wit...,"AHPG3AAPVL7HKSID4IPJ5MDAMAJA,AFBWMQUWPLCXK5D4A...","Ajinkya M K,Iggi,Sivajit Barman,Sarath Radhakr...","RK4CS8ATPVMJ2,R3NEW792RTB2MX,R19EPBUZLA6R67,R2...","Great to use, serves the purpose,Good Quality,...","Quality is good, strong build, supports fast c...",https://m.media-amazon.com/images/I/31Kt+OO7C6...,www.amazon.in/realme-Charging-Micro-USB-Cable-...
993,04IO5BMQ,"Logitech m235 wireless mouse, 1000 dpi optical...",Computers&accessories|accessories&peripherals|...,699.0,995.0,30.0,4.5,54405.0,You can surf the web with more comfort and eas...,"AGIOL4B6EPMZ63RZQFWZWI33O2EA,AG33OJYQIXPPS7CON...","Chandrashekar Sk,Mohammed Ashfaque,Arif Hussai...","R28ZB0YUM6FKKB,RNB44LXBJIPTL,RVSWATRY0CJIV,R3I...","Good silent mouse,Too small to hold,Reviewing ...",Its little small for big hands. But best avail...,https://m.media-amazon.com/images/I/31CtVvtFt+...,NaN
1036,0NNQMYNE,Aircase rugged hard drive case for 2.5-inch we...,Computers&accessories|accessories&peripherals|...,299.0,499.0,40.0,4.5,21010.0,Made of thick tough ballistic nylon hard she...,"AGK3NNXG44TLWHYTJ2OAY4JMD3VA,AGKSHSI672DMOJKNV...","Souradip,Narendran D,Mandar Barve,P Nagar,Amaz...","R3CX62IV0TSF01,R2K650XLDC67WC,RIL3X4K17UXMZ,RS...","Super,Excellent structural rigidity,Durable an...","Still using,Dealing with Amazon was a pleasant...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/AirCase-External-Drive-2-5-Inch-...
1049,78JT7LTD,"Sujata dynamix, mixer grinder, 900 watts, 3 ja...",Home&kitchen|kitchen&homeappliances|smallkitch...,6120.0,8073.0,24.0,4.6,2751.0,Warranty 2 year warranty provided by the manu...,"AGS4ODHNPY3TQGAIJFDY4I33URHA,AFFSSRKP2H3OGXCIJ...","Tengop,Jeevan Gaikwad,Gunashekar,Vibha K.,Amaz...","R1LBKT3YDVVW86,R2PNLSWFYW5QEF,R2I6NKZE7JWNY6,R...","Good product,Quality is great but chuteney jar...",Got it with intact packaging open it up the mo...,https://m.media-amazon.com/images/I/415634DtKf...,www.amazon.in/Sujata-Dynamix-900W-900-Watt-Mix...
1160,78KRFWQB,"Havells cista room heater, white, 2000 watts","Home&kitchen|heating,cooling&airquality|roomhe...",2499.0,3945.0,37.0,3.8,2732.0,Cool touch body with one year warranty warrant...,"AE7ZYKK6AN7B2Y7ACR7JHJW236LA,AESOWISQWBKYJDU52...","Vipin Arora,Tkr Singapore,Amazon Customer,Sati...","R2CQXUNYCW3XME,R2KAKW6DIB247K,R2JS1CRHA1ZVXX,R...","Products review,Good easy to use,Good and por...",Value for moneyHeat power goodOne loss point t...,https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Havells-Cista-room-Heater/dp/B07...
1239,97XJQZ8H,"Cookwell bullet mixer grinder (5 jars, 3 blade...",Home&kitchen|kitchen&homeappliances|smallkitch...,2464.0,1650.0,59.0,4.1,8866.0,Compact and consumes less space as compared to...,"AFJVAVYH2K6VUCTNLA5HZ45VQFKA,AGGWXZI3DYEKKDM4B...","Gowtham Saran,Nanu Prinu,Roopali Tiwari,Vipul ...","R2CCAIITXBUWWK,R34WQMRY9WM6SZ,RMO1CT02OKUNJ,R2...","Worth for money and best customer service,Good...",We ordered this product after many research an...,https://m.media-amazon.com/images/I/41nBjnlp-M...,www.amazon.in/Cookwell-Bullet-Mixer-Grinder-Si...
1261,BB3CBFBM,Vu 138 cm (55 inches) premium series 4k ultra ...,"Electronics|hometheater,tv&video|televisions|s...",29990.0,65000.0,54.0,4.1,211.0,Resolution 4k 3840x2160 refresh rate 60 ...,"AEH3MURR76DG3TEX3NXIJVJTKBLA,AGGEFVVI6ZRLVEJHV...","Ch Venkatesh,Nihar Mendon,Ip Trading Solutions...","RG3VFGY4HM38X,R957RND66RVWX,R1YR2TZI534FFY,R3V...","Valume for money,Cant turn off HDR in webOS wh...",Vu UHD SMART 43 web os version good tv 202...,https://m.media-amazon.com/images/I/41HhmJpfjN...,NaN
1262,8WRBG3XW,"Boat type c a325 tangle-free, sturdy type c ca...",Computers&accessories|accessories&peripherals|...,199.0,499.0,60.0,4.1,13045.0,Type c a 325 cable is designed with a perfect ...,"AFB5KJR4Q5FICAHBOPDPUTB3O7QQ,AHW3QBHDOUMXODZ4E...","Rohan Narkar,Jagwinder Singh,Gursewak Singh,Av...","R2BP8Y5OJXKJLF,R218813TNRHNSY,R3VIKEVJ5DBF5G,R...","Good for charging and Data transfer,,Good Qual...","Check for offera before buying,18w charging ca...",https://m.media-amazon.com/images/I/41xwPQLxTM...,www.amazon.in/boAt-A325-Tangle-Free-Charging-T...
1287,BBMGLQDW,"Tuarso 8k hdmi 2.1 cable 48gbps , 1.5 meter hi...","Electronics|hometheater,tv&video|accessories|c...",599.0,1999.0,70.0,4.2,47.0,Unknown,"AH34W5DLRK5DLTLP73YKFLTTKWAQ,AE7KUNNQKS6JSHH7Q...","Jitu,Shan Raj,Brajmohan Gaur,Shiv,Shameer,Deba...","R1S57TIOL6E20F,RIL69DS3C4JGC,R2GWGCF8S3OWCN,R1...","Good Product,Nice,Customer service support inf...","As mention in description, its awesome.,Nice,G...",https://m.media-amazon.com/images/I/41+BBk2fGc...,www.amazon.in/Tuarso-High-Speed-Compatible-Tel...
1332,14SZPBM4,"Duracell ultra alkaline d battery, 2 pcs",Electronics|generalpurposebatteries&batterycha...,380.0,400.0,5.0,4.4,2111.0,Long lasting power guaranteed our best battery...,"AEGQJH2NIAS54T7WKAHKVEO4B67A,AFDH4NWAAHAVKPQVB...","Md Asif Akhter,Kiran T,Hanuman Sarda,Pranav Ch...","R1RXFMVZ8EKN3Q,R2YX4PL3F59OHC,RUDJ9ISAQDD3B,R3...","Battery,Good buy,Bigger than expected,Best Bat...","Duracell never disappoint you,Good,httpsm.medi...",https://m.media-amazon.com/images/I/51BGUyveMf...,www.amazon.in/Duracell-Alkaline-Battery-Duralo...
1434,9R1YFL6S,Candes blowhot all in one silent blower fan ro...,"Home&kitchen|heating,cooling&airquality|roomhe...",1090.0,2999.0,64.0,3.5,57.0,Efficient warmth ideal for use in small and m...,"AHAXZDBQKLBWPQN5BFPSURNHWECA,AEGH2WM5MITQZBEZM...","Akash Yadav,Philip Chacko,Sudheer Kumar Maurya...","RNDYBQHMT47QL,R279Z47TD2BTW0,R1KIQPBI7LXLZY,R1...","Best performance, Best in such that cost,Nice,...","Best performance, I buy it twice...Really best...",https://m.media-amazon.com/images/W/WEBP_40237...,www.amazon.in/Candes-BlowHot-Silent-Blower-Hea...

In [3785]:
count_product = df['product_link'].notna() & ~df['product_link'].str.startswith('https://',na= False)
df.loc[count_product,'product_link'] = 'https://' + df.loc[count_product,'product_link']

In [3786]:
df.loc[~df['product_link'].str.contains('https:',na=False)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
13,NaN,NaN,NaN,799.0,1650.0,50.0,4.1,5137.0,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,NaN
18,B84KSH3X,Wipro vesta 1200 watt gd203 heavyweight automa...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",1049.0,1950.0,46.0,3.8,250.0,Heavy performance dry iron 1200 watt to back...,"AH7OT4IUCAKFYCPJ3SVLAHV7E2YA,AGONNWZMRQZR2JDLN...","S.Saravanan,Mukesh,Sanjay Kumar,Khadar Badha,M...","R2HFE6XNQS0UP8,R2BSCK1PAXQ5NH,RZPZS0APQWNRT,R1...","Good,Seems to be good,Good,Fake replacementthe...","New atavanc,Seems to be reasonable hot and hea...",https://m.media-amazon.com/images/I/41+HYuF5To...,NaN
74,96YCN3SD,Lifelong llek15 electric kettle 1.5l with stai...,Home&kitchen|kitchen&homeappliances|smallkitch...,549.0,1000.0,45.0,3.6,1074.0,Stainless steel body concealed element and si...,"AHM4ZOXDCO5UNP4WQUXKP4NWX64A,AGHJ3BRARYIXJRGPK...","Kiran Jot,Salman Ahmad,Neelam Rawat,Nawaz Akht...","R2QR5PM0ELMWD3,RZFX345XRS4V2,R352PKGSDAV1AW,R1...","Well over all iits nice, make sure the lid of ...","Well over all iits nice, make sure the lid of ...",https://m.media-amazon.com/images/W/WEBP_40237...,NaN
239,14SZO90Y,"Duracell ultra alkaline aa battery, 8 pcs",Electronics|generalpurposebatteries&batterycha...,266.0,315.0,16.0,4.5,28030.0,Lasts up to 100 longer longevity performan...,"AF37SWB5BJAXD6F2Q74M6HJIHADA,AFP7XI3X4GGJVQCYY...","Gopinathan,Punaram Chutia,Amazon Customer,Sree...","R31X4I2TGYDUN8,R27PTCIK04AE46,R23U630I51IZTI,R...","Thats a nice one,Best services,V good less pri...","Nice one, tried on remote mouse and found work...",https://m.media-amazon.com/images/W/WEBP_40237...,NaN
466,9VGKFM7Y,Amazon basics 2 amp usb wall charger & micro u...,Electronics|mobiles&accessories|mobileaccessor...,219.0,499.0,56.0,4.4,14.0,Durable wall charger with fast charging abilit...,"AFQ7AUYJOIE2HH63KIUQK45ENQ2A,AHT7TTZ5JOTUL7CYS...","Prabhanjan,Chittiprolu Ramya,Litu Prasada Mahanty","R33M2Q7OES3GBK,R125QF7WMZW3NW,RMDVRDSEK73L8","Quality product,Excellent, its fast charging,A...",Product works well and charges the devices in ...,https://m.media-amazon.com/images/I/31poWDDorO...,NaN
789,8SKZ2RMG,Demokrazy new nova lint cum fuzz remover for a...,"Home&kitchen|kitchen&homeappliances|vacuum,cle...",475.0,999.0,52.0,4.1,1021.0,Quick and efficient switch to turn it on and g...,"AE7RG5GRVSLRP2HGPKIF2JJ7BAHQ,AFCDHTYGHMNLNK2S3...","Vipin,Bhavana Rangarajan,Raj,Dimple Aggarwal,J...","R2TBG87E7UU7IT,R8OA8PY28PACZ,R3PAX3XE02N0SU,R1...","Good,Its a good product Go for it,Easy to use,...",Plastic is not of very good quality thought bu...,https://m.media-amazon.com/images/W/WEBP_40237...,NaN
993,04IO5BMQ,"Logitech m235 wireless mouse, 1000 dpi optical...",Computers&accessories|accessories&peripherals|...,699.0,995.0,30.0,4.5,54405.0,You can surf the web with more comfort and eas...,"AGIOL4B6EPMZ63RZQFWZWI33O2EA,AG33OJYQIXPPS7CON...","Chandrashekar Sk,Mohammed Ashfaque,Arif Hussai...","R28ZB0YUM6FKKB,RNB44LXBJIPTL,RVSWATRY0CJIV,R3I...","Good silent mouse,Too small to hold,Reviewing ...",Its little small for big hands. But best avail...,https://m.media-amazon.com/images/I/31CtVvtFt+...,NaN
1261,BB3CBFBM,Vu 138 cm (55 inches) premium series 4k ultra ...,"Electronics|hometheater,tv&video|televisions|s...",29990.0,65000.0,54.0,4.1,211.0,Resolution 4k 3840x2160 refresh rate 60 ...,"AEH3MURR76DG3TEX3NXIJVJTKBLA,AGGEFVVI6ZRLVEJHV...","Ch Venkatesh,Nihar Mendon,Ip Trading Solutions...","RG3VFGY4HM38X,R957RND66RVWX,R1YR2TZI534FFY,R3V...","Valume for money,Cant turn off HDR in webOS wh...",Vu UHD SMART 43 web os version good tv 202...,https://m.media-amazon.com/images/I/41HhmJpfjN...,NaN

In [ ]:
df[df['product_id'] == 'B5GJRTHB']

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
191,B5GJRTHB,Wecool moonwalk m1 enc true wireless in ear ea...,"Electronics|headphones,earbuds&accessories|hea...",889.0,1999.0,56.0,4.2,2284.0,We have designed the enc earbuds to provide ex...,"AGMD2UVAWOKO3W37KGZWAPI3ZB6A,AG7BC5ADBMW6EMTNH...","Siddhesh S.,Karthik,Vikram Kanth,Dhanesh,Rani,...","R1R1JK1E1KZYX8,R2XZC0TY29XVLD,R10HYVIHZWKK1K,R...","Great Customer care experience,Best in budget ...",I ordered this product 1 week ago on Amazon bu...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Moonwalk-Wireless-Titani...

In [3789]:
df['product_link'] = df['product_link'].fillna('Unknown')

In [3790]:
df['product_link'].isna().sum()

np.int64(0)

In [3791]:
df.duplicated().sum()

np.int64(0)

Data Type : Convert all price, rating, discount and rating count columns into appropriate numeric data types.

In [3795]:
df.dtypes

product_id                 object
product_name               object
category                   object
Discounted_Price (INR)    float64
actual_price              float64
discount_percentage       float64
rating                    float64
Rating Count              float64
about_product              object
user_id                    object
user_name                  object
review_id                  object
review_title               object
review_content             object
IMG_LINK                   object
product_link               object
dtype: object

In [3796]:
df.duplicated().sum()

np.int64(0)

In [3797]:
df.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

In [3798]:
df.to_csv('cleaned_amazon_data.csv')