In [376]:
import pandas as pd

In [377]:
data = pd.read_csv('results.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Games        308408 non-null  object
 1   Event        308408 non-null  object
 2   Team         121714 non-null  object
 3   Pos          306583 non-null  object
 4   Medal        44139 non-null   object
 5   As           308408 non-null  object
 6   athlete_id   308408 non-null  int64
 7   NOC          308407 non-null  object
 8   Discipline   308407 non-null  object
 9   Nationality  81 non-null      object
 10  Unnamed: 7   0 non-null       float64
dtypes: float64(1), int64(1), object(9)
memory usage: 25.9+ MB

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_28105/1883128485.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('results.csv')

Things to do : 


* [x ] Check and remove duplicate rows
* [ ] Fix data types
* [ x] Split `Games` into `Game_Year` and `Game_Name`
* [ x] Extract `Gender` from `Event`
* [ x] Determine and extract `Event Size`
* [x ] Clean `athlete_id`
* [ x] Clean `Pos` (`=17` → `17`)
* [ ] Handle missing values
* [ ] Clean inconsistent text/categorical values
* [ ] Remove unwanted columns (e.g. `Unnamed: 7`)

In [378]:
data.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [379]:
df = data.copy()
df.columns

Index(['Games', 'Event', 'Team', 'Pos', 'Medal', 'As', 'athlete_id', 'NOC',
       'Discipline', 'Nationality', 'Unnamed: 7'],
      dtype='object')

In [380]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Games        308408 non-null  object
 1   Event        308408 non-null  object
 2   Team         121714 non-null  object
 3   Pos          306583 non-null  object
 4   Medal        44139 non-null   object
 5   As           308408 non-null  object
 6   athlete_id   308408 non-null  int64
 7   NOC          308407 non-null  object
 8   Discipline   308407 non-null  object
 9   Nationality  81 non-null      object
 10  Unnamed: 7   0 non-null       float64
dtypes: float64(1), int64(1), object(9)
memory usage: 25.9+ MB

In [381]:
(df['Nationality'] == df['NOC']).sum()

np.int64(4)

In [382]:
df.duplicated().sum()

np.int64(110)

In [383]:
df.drop_duplicates(inplace= True)

In [384]:
df.duplicated().sum()

np.int64(0)

In [385]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 308298 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Games        308298 non-null  object
 1   Event        308298 non-null  object
 2   Team         121684 non-null  object
 3   Pos          306473 non-null  object
 4   Medal        44125 non-null   object
 5   As           308298 non-null  object
 6   athlete_id   308298 non-null  int64
 7   NOC          308297 non-null  object
 8   Discipline   308297 non-null  object
 9   Nationality  81 non-null      object
 10  Unnamed: 7   0 non-null       float64
dtypes: float64(1), int64(1), object(9)
memory usage: 28.2+ MB

In [386]:
df.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [387]:
game_year = r'(\d{4})'
game_name = r'\d{4}\S*\s(.+)'
df['game_year'] = df['Games'].str.extract(game_year)
df['game_name'] = df['Games'].str.extract(game_name)
df[df['Games'].str.extract(game_name)[0].isna()]
df[df['Games'] == '1888-89 Zappas Olympic Games']

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name
121776,1888-89 Zappas Olympic Games,"Rope Climbing, Men ()",NaN,1,NaN,Sotirios Versis,55911,GRE,Artistic Gymnastics (Gymnastics),NaN,NaN,1888,Zappas Olympic Games

In [388]:
df.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics

In [389]:
df.columns

Index(['Games', 'Event', 'Team', 'Pos', 'Medal', 'As', 'athlete_id', 'NOC',
       'Discipline', 'Nationality', 'Unnamed: 7', 'game_year', 'game_name'],
      dtype='object')

In [390]:
df['Event'].unique()

array(['Singles, Men (Olympic)', 'Doubles, Men (Olympic)',
       'Doubles, Mixed (Olympic)', ..., 'Kumite, ≤61 kg, Women (Olympic)',
       'Kata, Men (Olympic)', 'Kata, Women (Olympic)'], dtype=object)

In [391]:
df[df['Event'].str.extract(r'(Men|Women|Mixed)',expand=False).isna()]['Event'].value_counts().head(30)
un_matched = df['Event'].str.extract(r'(Men|Women|Mixed)',expand=False).isna()
df[un_matched & df['Event'].str.match('Open', na=False)].shape[0]

89

In [392]:
un_matched = df['Event'].str.extract(r'(Men|Women|Mixed)',expand=False).isna()
df[un_matched]['Event'].value_counts().head(20)

Event
Individual, Open (Olympic)                                      2644
Team, Open (Olympic)                                            2328
Three Person Keelboat, Open (Olympic)                            927
Two Person Keelboat, Open (Olympic)                              650
Doubles, Open (Olympic)                                          595
One Person Dinghy, Open (Olympic)                                567
Two Person Heavyweight Dinghy, Open (Olympic)                    448
Skeet, Open (Olympic)                                            410
Cycling Track (Cycling)                                          377
Trap, Open (Olympic)                                             363
6 metres, Open (Olympic)                                         328
Small-Bore Rifle, Prone, 50 metres, Open (Olympic)               321
Multihull, Open (Olympic)                                        317
5.5 metres, Open (Olympic)                                       228
Small-Bore Rifle, Three Positions, 50 metres, Open (Olympic)     227
8 metres, Open (Olympic)                                         227
Four, Open (Olympic)                                             216
Free Pistol, 50 metres, Open (Olympic)                           208
Rapid-Fire Pistol, 25 metres, Open (Olympic)                     206
Nordic Combined (Skiing)                                         167
Name: count, dtype: int64

In [393]:
gender = r'(Men|Women|Mixed)'
df['Gender'] = df['Event'].str.extract(gender, expand= True)
df[df['Event'].str.contains(r'Men|Women|Mixed', na=False) &df['Gender'].isna()].shape[0]

0

In [394]:
df['Gender'].isna().sum()

np.int64(18538)

In [395]:
df

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name,Gender
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Mixed
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022 Winter Olympics,"Singles, Men (Olympic)",NaN,26.0,NaN,Marián Skupek,148983,SVK,Luge,NaN,NaN,2022,Winter Olympics,Men
308404,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,28.0,NaN,Elsa Fermbäck,148984,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women
308405,2022 Winter Olympics,"Team, Mixed (Olympic)",Sweden,13,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Mixed
308406,2022 Winter Olympics,"Giant Slalom, Women (Olympic)",NaN,DNF,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women
308407,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,24.0,NaN,Charlotta Säfvenberg,148986,NaN,NaN,NaN,NaN,2022,Winter Olympics,Women

In [396]:
first = df['Event'].str.split(',').str[0].value_counts()
first.value_counts().head(50)
df[df['Event'].str.startswith('1,', na=False)]['Event'].head(20)

571       1,200 metres Freestyle, Men (Olympic)
1523                1,500 metres, Men (Olympic)
23260    1,000 metres Time Trial, Men (Olympic)
23805    1,000 metres Time Trial, Men (Olympic)
23819    1,000 metres Time Trial, Men (Olympic)
23836    1,000 metres Time Trial, Men (Olympic)
23904    1,000 metres Time Trial, Men (Olympic)
23905    1,000 metres Time Trial, Men (Olympic)
23917    1,000 metres Time Trial, Men (Olympic)
23923    1,000 metres Time Trial, Men (Olympic)
23953    1,000 metres Time Trial, Men (Olympic)
23955    1,000 metres Time Trial, Men (Olympic)
23987    1,000 metres Time Trial, Men (Olympic)
24033    1,000 metres Time Trial, Men (Olympic)
24039    1,000 metres Time Trial, Men (Olympic)
24060    1,000 metres Time Trial, Men (Olympic)
24076    1,000 metres Time Trial, Men (Olympic)
24078    1,000 metres Time Trial, Men (Olympic)
24121    1,000 metres Time Trial, Men (Olympic)
24163    1,000 metres Time Trial, Men (Olympic)
Name: Event, dtype: object

In [397]:
df['Event_Type'] = df['Event'].str.split(',').str[0].str.strip()
df[
    ~df.apply(lambda row : row['Event_Type'] in row['Event'] , axis= 1)
    ]

Empty DataFrame
Columns: [Games, Event, Team, Pos, Medal, As, athlete_id, NOC, Discipline, Nationality, Unnamed: 7, game_year, game_name, Gender, Event_Type]
Index: []

In [398]:
df['Handicap'] = df['Event'].str.contains('Handicap',na=False)
df

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name,Gender,Event_Type,Handicap
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Singles,False
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Doubles,False
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Singles,False
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Mixed,Doubles,False
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Doubles,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022 Winter Olympics,"Singles, Men (Olympic)",NaN,26.0,NaN,Marián Skupek,148983,SVK,Luge,NaN,NaN,2022,Winter Olympics,Men,Singles,False
308404,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,28.0,NaN,Elsa Fermbäck,148984,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Slalom,False
308405,2022 Winter Olympics,"Team, Mixed (Olympic)",Sweden,13,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Mixed,Team,False
308406,2022 Winter Olympics,"Giant Slalom, Women (Olympic)",NaN,DNF,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Giant Slalom,False
308407,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,24.0,NaN,Charlotta Säfvenberg,148986,NaN,NaN,NaN,NaN,2022,Winter Olympics,Women,Slalom,False

In [399]:
df['Event'].str.contains('Handicap',na =False).sum()

np.int64(255)

In [400]:
df['Handicap'].sum()

np.int64(255)

In [401]:
df['athlete_id'].reset_index()

         index  athlete_id
0            0           1
1            1           1
2            2           1
3            3           1
4            4           1
...        ...         ...
308293  308403      148983
308294  308404      148984
308295  308405      148985
308296  308406      148985
308297  308407      148986

[308298 rows x 2 columns]

In [402]:
df

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name,Gender,Event_Type,Handicap
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Singles,False
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Doubles,False
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Singles,False
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Mixed,Doubles,False
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Doubles,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022 Winter Olympics,"Singles, Men (Olympic)",NaN,26.0,NaN,Marián Skupek,148983,SVK,Luge,NaN,NaN,2022,Winter Olympics,Men,Singles,False
308404,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,28.0,NaN,Elsa Fermbäck,148984,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Slalom,False
308405,2022 Winter Olympics,"Team, Mixed (Olympic)",Sweden,13,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Mixed,Team,False
308406,2022 Winter Olympics,"Giant Slalom, Women (Olympic)",NaN,DNF,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Giant Slalom,False
308407,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,24.0,NaN,Charlotta Säfvenberg,148986,NaN,NaN,NaN,NaN,2022,Winter Olympics,Women,Slalom,False

In [403]:
df['Name_of_player'] = df['As']

In [404]:
df

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,game_year,game_name,Gender,Event_Type,Handicap,Name_of_player
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Singles,False,Jean-François Blanchy
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer Olympics,Men,Doubles,False,Jean-François Blanchy
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Singles,False,Jean-François Blanchy
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Mixed,Doubles,False,Jean-François Blanchy
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer Olympics,Men,Doubles,False,Jean-François Blanchy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022 Winter Olympics,"Singles, Men (Olympic)",NaN,26.0,NaN,Marián Skupek,148983,SVK,Luge,NaN,NaN,2022,Winter Olympics,Men,Singles,False,Marián Skupek
308404,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,28.0,NaN,Elsa Fermbäck,148984,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Slalom,False,Elsa Fermbäck
308405,2022 Winter Olympics,"Team, Mixed (Olympic)",Sweden,13,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Mixed,Team,False,Hilma Lövblom
308406,2022 Winter Olympics,"Giant Slalom, Women (Olympic)",NaN,DNF,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter Olympics,Women,Giant Slalom,False,Hilma Lövblom
308407,2022 Winter Olympics,"Slalom, Women (Olympic)",NaN,24.0,NaN,Charlotta Säfvenberg,148986,NaN,NaN,NaN,NaN,2022,Winter Olympics,Women,Slalom,False,Charlotta Säfvenberg

In [405]:
pos_num = r'(\d+)'
df['place'] = df['Pos'].str.extract(pos_num)
df['place'].unique()

array(['17', nan, '32', '8', '4', '15', '3', '9', '2', '33', '49', '5',
       '1', '31', '14', '16', '7', '13', '29', '25', '21', '11', '48',
       '26', '41', '61', '6', '81', '75', '57', '19', '52', '12', '50',
       '35', '36', '55', '24', '63', '22', '40', '18', '23', '44', '53',
       '46', '43', '60', '58', '73', '20', '71', '80', '76', '62', '27',
       '30', '45', '34', '39', '51', '70', '37', '38', '47', '10', '74',
       '56', '64', '28', '42', '54', '59', '72', '77', '65', '69', '79',
       '66', '83', '82', '67', '68', '84', '78', '86', '106', '100',
       '117', '91', '89', '101', '98', '114', '88', '112', '102', '96',
       '103', '94', '109', '92', '104', '85', '87', '110', '113', '99',
       '90', '93', '108', '105', '107', '95', '116', '111', '97', '115',
       '120', '118', '121', '123', '124', '129', '122', '132', '119',
       '130', '125', '127', '128', '126', '131', '133', '134', '178',
       '151', '180', '177', '174', '159', '157', '161', '168', '144',
       '135', '166', '136', '182', '154', '162', '185', '184', '183',
       '148', '137', '179', '176', '141', '155', '164', '158', '173',
       '169', '181', '139', '140', '152', '147', '175', '170', '153',
       '150', '149', '146', '143', '156', '171', '172', '145', '165',
       '142', '138', '160', '167', '163'], dtype=object)

In [406]:
df['Team'].value_counts()
# df['Discipline'].value_counts()
# df['Medal'].value_counts()

Team
United States      6146
Italy              4062
France             3911
Great Britain      3634
Canada             3607
                   ...
Sakigake              1
Helios / Poland       1
Bandoura              1
5000                  1
Europe 1              1
Name: count, Length: 19413, dtype: int64

In [407]:
df['NOC'].nunique()

230

In [408]:
df['NOC'].value_counts().head(20)

NOC
USA    21321
FRA    14254
GBR    13169
ITA    12123
CAN    11453
GER    11238
JPN     9882
SWE     9303
AUS     8807
HUN     7388
SUI     7081
POL     6857
NED     6417
CHN     6368
FIN     6190
ESP     5942
AUT     5835
NOR     5818
URS     5787
RUS     5525
Name: count, dtype: int64

In [409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 308298 entries, 0 to 308407
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Games           308298 non-null  object
 1   Event           308298 non-null  object
 2   Team            121684 non-null  object
 3   Pos             306473 non-null  object
 4   Medal           44125 non-null   object
 5   As              308298 non-null  object
 6   athlete_id      308298 non-null  int64
 7   NOC             308297 non-null  object
 8   Discipline      308297 non-null  object
 9   Nationality     81 non-null      object
 10  Unnamed: 7      0 non-null       float64
 11  game_year       308298 non-null  object
 12  game_name       308298 non-null  object
 13  Gender          289760 non-null  object
 14  Event_Type      308298 non-null  object
 15  Handicap        308298 non-null  bool
 16  Name_of_player  308298 non-null  object
 17  place           283146 non-null  object
dtypes: bool(1), float64(1), int64(1), object(15)
memory usage: 42.6+ MB

In [410]:
df['Games'] = df['Games'].astype('string')
df['Medal'] = df['Medal'].astype('string')
df['Discipline'] = df['Discipline'].astype('string')
df['game_name'] = df['game_name'].astype('string')
df['Event_Type'] = df['Event_Type'].astype('string')
df['Gender'] = df['Gender'].astype('string')
df['Name_of_player'] = df['Name_of_player'].astype('string')
df['place'] = pd.to_numeric(df['place'])

In [411]:
df['Games'].dtype

string[python]

In [412]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 308298 entries, 0 to 308407
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Games           308298 non-null  string
 1   Event           308298 non-null  object
 2   Team            121684 non-null  object
 3   Pos             306473 non-null  object
 4   Medal           44125 non-null   string
 5   As              308298 non-null  object
 6   athlete_id      308298 non-null  int64
 7   NOC             308297 non-null  object
 8   Discipline      308297 non-null  string
 9   Nationality     81 non-null      object
 10  Unnamed: 7      0 non-null       float64
 11  game_year       308298 non-null  object
 12  game_name       308298 non-null  string
 13  Gender          289760 non-null  string
 14  Event_Type      308298 non-null  string
 15  Handicap        308298 non-null  bool
 16  Name_of_player  308298 non-null  string
 17  place           283146 non-null  float64
dtypes: bool(1), float64(2), int64(1), object(7), string(7)
memory usage: 42.6+ MB

In [413]:
df['game_year']
df['game_year'] = pd.to_numeric(df['game_year'])

In [414]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 308298 entries, 0 to 308407
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Games           308298 non-null  string
 1   Event           308298 non-null  object
 2   Team            121684 non-null  object
 3   Pos             306473 non-null  object
 4   Medal           44125 non-null   string
 5   As              308298 non-null  object
 6   athlete_id      308298 non-null  int64
 7   NOC             308297 non-null  object
 8   Discipline      308297 non-null  string
 9   Nationality     81 non-null      object
 10  Unnamed: 7      0 non-null       float64
 11  game_year       308298 non-null  int64
 12  game_name       308298 non-null  string
 13  Gender          289760 non-null  string
 14  Event_Type      308298 non-null  string
 15  Handicap        308298 non-null  bool
 16  Name_of_player  308298 non-null  string
 17  place           283146 non-null  float64
dtypes: bool(1), float64(2), int64(2), object(6), string(7)
memory usage: 42.6+ MB

In [416]:
df.columns

Index(['Games', 'Event', 'Team', 'Pos', 'Medal', 'As', 'athlete_id', 'NOC',
       'Discipline', 'Nationality', 'Unnamed: 7', 'game_year', 'game_name',
       'Gender', 'Event_Type', 'Handicap', 'Name_of_player', 'place'],
      dtype='object')

In [417]:
columns_to_keep = ['athlete_id','Games','Name_of_player','place','NOC','Medal','Discipline','game_year','game_name','Gender','Event_Type','Handicap',]

In [418]:
df_clean = df[columns_to_keep]

In [419]:
df_clean.head()

,athlete_id,Games,Name_of_player,place,NOC,Medal,Discipline,game_year,game_name,Gender,Event_Type,Handicap
0,1,1912 Summer Olympics,Jean-François Blanchy,17.0,FRA,<NA>,Tennis,1912,Summer Olympics,Men,Singles,False
1,1,1912 Summer Olympics,Jean-François Blanchy,NaN,FRA,<NA>,Tennis,1912,Summer Olympics,Men,Doubles,False
2,1,1920 Summer Olympics,Jean-François Blanchy,32.0,FRA,<NA>,Tennis,1920,Summer Olympics,Men,Singles,False
3,1,1920 Summer Olympics,Jean-François Blanchy,8.0,FRA,<NA>,Tennis,1920,Summer Olympics,Mixed,Doubles,False
4,1,1920 Summer Olympics,Jean-François Blanchy,4.0,FRA,<NA>,Tennis,1920,Summer Olympics,Men,Doubles,False

In [420]:
df_clean.to_csv('clean_result_data.csv')