In [225]:
import pandas as pd
import numpy as np

In [226]:
data = pd.read_csv('global_freelancers_raw.csv')
data.head()

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,FL250001,Ms. Nicole Kidd,f,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,FL250002,Vanessa Garcia,FEMALE,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,FL250003,Juan Nelson,male,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,FL250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,FL250005,Lynn Curtis DDS,female,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%

In [227]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   freelancer_ID        1000 non-null   object
 1   name                 1000 non-null   object
 2   gender               1000 non-null   object
 3   age                  970 non-null    float64
 4   country              1000 non-null   object
 5   language             1000 non-null   object
 6   primary_skill        1000 non-null   object
 7   years_of_experience  949 non-null    float64
 8   hourly_rate (USD)    906 non-null    object
 9   rating               899 non-null    float64
 10  is_active            911 non-null    object
 11  client_satisfaction  824 non-null    object
dtypes: float64(3), object(9)
memory usage: 93.9+ KB

In [228]:
df = data.copy()

In [229]:
df.head()

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,FL250001,Ms. Nicole Kidd,f,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,FL250002,Vanessa Garcia,FEMALE,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,FL250003,Juan Nelson,male,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,FL250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,FL250005,Lynn Curtis DDS,female,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%

In [230]:
df.describe()

              age  years_of_experience      rating
count  970.000000           949.000000  899.000000
mean    40.509278            11.340358    2.512570
std     11.942605             9.680610    1.546599
min     20.000000             0.000000    0.000000
25%     31.000000             3.000000    1.400000
50%     41.000000             9.000000    2.600000
75%     51.000000            17.000000    3.800000
max     60.000000            41.000000    5.000000

In [231]:
df.duplicated().sum()

np.int64(0)

In [232]:
df.isna().sum()

freelancer_ID            0
name                     0
gender                   0
age                     30
country                  0
language                 0
primary_skill            0
years_of_experience     51
hourly_rate (USD)       94
rating                 101
is_active               89
client_satisfaction    176
dtype: int64

In [233]:
for col in df:
    print(df[col].unique())

['FL250001' 'FL250002' 'FL250003' 'FL250004' 'FL250005' 'FL250006'
 'FL250007' 'FL250008' 'FL250009' 'FL250010' 'FL250011' 'FL250012'
 'FL250013' 'FL250014' 'FL250015' 'FL250016' 'FL250017' 'FL250018'
 'FL250019' 'FL250020' 'FL250021' 'FL250022' 'FL250023' 'FL250024'
 'FL250025' 'FL250026' 'FL250027' 'FL250028' 'FL250029' 'FL250030'
 'FL250031' 'FL250032' 'FL250033' 'FL250034' 'FL250035' 'FL250036'
 'FL250037' 'FL250038' 'FL250039' 'FL250040' 'FL250041' 'FL250042'
 'FL250043' 'FL250044' 'FL250045' 'FL250046' 'FL250047' 'FL250048'
 'FL250049' 'FL250050' 'FL250051' 'FL250052' 'FL250053' 'FL250054'
 'FL250055' 'FL250056' 'FL250057' 'FL250058' 'FL250059' 'FL250060'
 'FL250061' 'FL250062' 'FL250063' 'FL250064' 'FL250065' 'FL250066'
 'FL250067' 'FL250068' 'FL250069' 'FL250070' 'FL250071' 'FL250072'
 'FL250073' 'FL250074' 'FL250075' 'FL250076' 'FL250077' 'FL250078'
 'FL250079' 'FL250080' 'FL250081' 'FL250082' 'FL250083' 'FL250084'
 'FL250085' 'FL250086' 'FL250087' 'FL250088' 'FL250089' 'FL250090'
 'FL250091' 'FL250092' 'FL250093' 'FL250094' 'FL250095' 'FL250096'
 'FL250097' 'FL250098' 'FL250099' 'FL250100' 'FL250101' 'FL250102'
 'FL250103' 'FL250104' 'FL250105' 'FL250106' 'FL250107' 'FL250108'
 'FL250109' 'FL250110' 'FL250111' 'FL250112' 'FL250113' 'FL250114'
 'FL250115' 'FL250116' 'FL250117' 'FL250118' 'FL250119' 'FL250120'
 'FL250121' 'FL250122' 'FL250123' 'FL250124' 'FL250125' 'FL250126'
 'FL250127' 'FL250128' 'FL250129' 'FL250130' 'FL250131' 'FL250132'
 'FL250133' 'FL250134' 'FL250135' 'FL250136' 'FL250137' 'FL250138'
 'FL250139' 'FL250140' 'FL250141' 'FL250142' 'FL250143' 'FL250144'
 'FL250145' 'FL250146' 'FL250147' 'FL250148' 'FL250149' 'FL250150'
 'FL250151' 'FL250152' 'FL250153' 'FL250154' 'FL250155' 'FL250156'
 'FL250157' 'FL250158' 'FL250159' 'FL250160' 'FL250161' 'FL250162'
 'FL250163' 'FL250164' 'FL250165' 'FL250166' 'FL250167' 'FL250168'
 'FL250169' 'FL250170' 'FL250171' 'FL250172' 'FL250173' 'FL250174'
 'FL250175' 'FL250176' 'FL250177' 'FL250178' 'FL250179' 'FL250180'
 'FL250181' 'FL250182' 'FL250183' 'FL250184' 'FL250185' 'FL250186'
 'FL250187' 'FL250188' 'FL250189' 'FL250190' 'FL250191' 'FL250192'
 'FL250193' 'FL250194' 'FL250195' 'FL250196' 'FL250197' 'FL250198'
 'FL250199' 'FL250200' 'FL250201' 'FL250202' 'FL250203' 'FL250204'
 'FL250205' 'FL250206' 'FL250207' 'FL250208' 'FL250209' 'FL250210'
 'FL250211' 'FL250212' 'FL250213' 'FL250214' 'FL250215' 'FL250216'
 'FL250217' 'FL250218' 'FL250219' 'FL250220' 'FL250221' 'FL250222'
 'FL250223' 'FL250224' 'FL250225' 'FL250226' 'FL250227' 'FL250228'
 'FL250229' 'FL250230' 'FL250231' 'FL250232' 'FL250233' 'FL250234'
 'FL250235' 'FL250236' 'FL250237' 'FL250238' 'FL250239' 'FL250240'
 'FL250241' 'FL250242' 'FL250243' 'FL250244' 'FL250245' 'FL250246'
 'FL250247' 'FL250248' 'FL250249' 'FL250250' 'FL250251' 'FL250252'
 'FL250253' 'FL250254' 'FL250255' 'FL250256' 'FL250257' 'FL250258'
 'FL250259' 'FL250260' 'FL250261' 'FL250262' 'FL250263' 'FL250264'
 'FL250265' 'FL250266' 'FL250267' 'FL250268' 'FL250269' 'FL250270'
 'FL250271' 'FL250272' 'FL250273' 'FL250274' 'FL250275' 'FL250276'
 'FL250277' 'FL250278' 'FL250279' 'FL250280' 'FL250281' 'FL250282'
 'FL250283' 'FL250284' 'FL250285' 'FL250286' 'FL250287' 'FL250288'
 'FL250289' 'FL250290' 'FL250291' 'FL250292' 'FL250293' 'FL250294'
 'FL250295' 'FL250296' 'FL250297' 'FL250298' 'FL250299' 'FL250300'
 'FL250301' 'FL250302' 'FL250303' 'FL250304' 'FL250305' 'FL250306'
 'FL250307' 'FL250308' 'FL250309' 'FL250310' 'FL250311' 'FL250312'
 'FL250313' 'FL250314' 'FL250315' 'FL250316' 'FL250317' 'FL250318'
 'FL250319' 'FL250320' 'FL250321' 'FL250322' 'FL250323' 'FL250324'
 'FL250325' 'FL250326' 'FL250327' 'FL250328' 'FL250329' 'FL250330'
 'FL250331' 'FL250332' 'FL250333' 'FL250334' 'FL250335' 'FL250336'
 'FL250337' 'FL250338' 'FL250339' 'FL250340' 'FL250341' 'FL250342'
 'FL250343' 'FL250344' 'FL250345' 'FL250346' 'FL250347' 'FL250348'
 'FL250349' 'FL250350' 'FL250351' 'FL250352' 'FL250353' 'FL250354'
 'FL250355' 'FL250356' 'FL250357' 'FL250358' 'FL250359' 'FL250360'
 'FL250361' 'FL250362' 'FL250363' 'FL250364' 'FL250365' 'FL250366'
 'FL250367' 'FL250368' 'FL250369' 'FL250370' 'FL250371' 'FL250372'
 'FL250373' 'FL250374' 'FL250375' 'FL250376' 'FL250377' 'FL250378'
 'FL250379' 'FL250380' 'FL250381' 'FL250382' 'FL250383' 'FL250384'
 'FL250385' 'FL250386' 'FL250387' 'FL250388' 'FL250389' 'FL250390'
 'FL250391' 'FL250392' 'FL250393' 'FL250394' 'FL250395' 'FL250396'
 'FL250397' 'FL250398' 'FL250399' 'FL250400' 'FL250401' 'FL250402'
 'FL250403' 'FL250404' 'FL250405' 'FL250406' 'FL250407' 'FL250408'
 'FL250409' 'FL250410' 'FL250411' 'FL250412' 'FL250413' 'FL250414'
 'FL250415' 'FL250416' 'FL250417' 'FL250418' 'FL250419' 'FL250420'
 'FL250421' 'FL250422' 'FL250423' 'FL250424' 'FL250425' 'FL250426'
 'FL250427' 'FL250428' 'FL250429' 'FL250430' 'FL250431' 'FL250432'
 'FL250433' 'FL250434' 'FL250435' 'FL250436' 'FL250437' 'FL250438'
 'FL250439' 'FL250440' 'FL250441' 'FL250442' 'FL250443' 'FL250444'
 'FL250445' 'FL250446' 'FL250447' 'FL250448' 'FL250449' 'FL250450'
 'FL250451' 'FL250452' 'FL250453' 'FL250454' 'FL250455' 'FL250456'
 'FL250457' 'FL250458' 'FL250459' 'FL250460' 'FL250461' 'FL250462'
 'FL250463' 'FL250464' 'FL250465' 'FL250466' 'FL250467' 'FL250468'
 'FL250469' 'FL250470' 'FL250471' 'FL250472' 'FL250473' 'FL250474'
 'FL250475' 'FL250476' 'FL250477' 'FL250478' 'FL250479' 'FL250480'
 'FL250481' 'FL250482' 'FL250483' 'FL250484' 'FL250485' 'FL250486'
 'FL250487' 'FL250488' 'FL250489' 'FL250490' 'FL250491' 'FL250492'
 'FL250493' 'FL250494' 'FL250495' 'FL250496' 'FL250497' 'FL250498'
 'FL250499' 'FL250500' 'FL250501' 'FL250502' 'FL250503' 'FL250504'
 'FL250505' 'FL250506' 'FL250507' 'FL250508' 'FL250509' 'FL250510'
 'FL250511' 'FL250512' 'FL250513' 'FL250514' 'FL250515' 'FL250516'
 'FL250517' 'FL250518' 'FL250519' 'FL250520' 'FL250521' 'FL250522'
 'FL250523' 'FL250524' 'FL250525' 'FL250526' 'FL250527' 'FL250528'
 'FL250529' 'FL250530' 'FL250531' 'FL250532' 'FL250533' 'FL250534'
 'FL250535' 'FL250536' 'FL250537' 'FL250538' 'FL250539' 'FL250540'
 'FL250541' 'FL250542' 'FL250543' 'FL250544' 'FL250545' 'FL250546'
 'FL250547' 'FL250548' 'FL250549' 'FL250550' 'FL250551' 'FL250552'
 'FL250553' 'FL250554' 'FL250555' 'FL250556' 'FL250557' 'FL250558'
 'FL250559' 'FL250560' 'FL250561' 'FL250562' 'FL250563' 'FL250564'
 'FL250565' 'FL250566' 'FL250567' 'FL250568' 'FL250569' 'FL250570'
 'FL250571' 'FL250572' 'FL250573' 'FL250574' 'FL250575' 'FL250576'
 'FL250577' 'FL250578' 'FL250579' 'FL250580' 'FL250581' 'FL250582'
 'FL250583' 'FL250584' 'FL250585' 'FL250586' 'FL250587' 'FL250588'
 'FL250589' 'FL250590' 'FL250591' 'FL250592' 'FL250593' 'FL250594'
 'FL250595' 'FL250596' 'FL250597' 'FL250598' 'FL250599' 'FL250600'
 'FL250601' 'FL250602' 'FL250603' 'FL250604' 'FL250605' 'FL250606'
 'FL250607' 'FL250608' 'FL250609' 'FL250610' 'FL250611' 'FL250612'
 'FL250613' 'FL250614' 'FL250615' 'FL250616' 'FL250617' 'FL250618'
 'FL250619' 'FL250620' 'FL250621' 'FL250622' 'FL250623' 'FL250624'
 'FL250625' 'FL250626' 'FL250627' 'FL250628' 'FL250629' 'FL250630'
 'FL250631' 'FL250632' 'FL250633' 'FL250634' 'FL250635' 'FL250636'
 'FL250637' 'FL250638' 'FL250639' 'FL250640' 'FL250641' 'FL250642'
 'FL250643' 'FL250644' 'FL250645' 'FL250646' 'FL250647' 'FL250648'
 'FL250649' 'FL250650' 'FL250651' 'FL250652' 'FL250653' 'FL250654'
 'FL250655' 'FL250656' 'FL250657' 'FL250658' 'FL250659' 'FL250660'
 'FL250661' 'FL250662' 'FL250663' 'FL250664' 'FL250665' 'FL250666'
 'FL250667' 'FL250668' 'FL250669' 'FL250670' 'FL250671' 'FL250672'
 'FL250673' 'FL250674' 'FL250675' 'FL250676' 'FL250677' 'FL250678'
 'FL250679' 'FL250680' 'FL250681' 'FL250682' 'FL250683' 'FL250684'
 'FL250685' 'FL250686' 'FL250687' 'FL250688' 'FL250689' 'FL250690'
 'FL250691' 'FL250692' 'FL250693' 'FL250694' 'FL250695' 'FL250696'
 'FL250697' 'FL250698' 'FL250699' 'FL250700' 'FL250701' 'FL250702'
 'FL250703' 'FL250704' 'FL250705' 'FL250706' 'FL250707' 'FL250708'
 'FL250709' 'FL250710' 'FL250711' 'FL250712' 'FL250713' 'FL250714'
 'FL250715' 'FL250716' 'FL250717' 'FL250718' 'FL250719' 'FL250720'
 'FL250721' 'FL250722' 'FL250723' 'FL250724' 'FL250725' 'FL250726'
 'FL250727' 'FL250728' 'FL250729' 'FL250730' 'FL250731' 'FL250732'
 'FL250733' 'FL250734' 'FL250735' 'FL250736' 'FL250737' 'FL250738'
 'FL250739' 'FL250740' 'FL250741' 'FL250742' 'FL250743' 'FL250744'
 'FL250745' 'FL250746' 'FL250747' 'FL250748' 'FL250749' 'FL250750'
 'FL250751' 'FL250752' 'FL250753' 'FL250754' 'FL250755' 'FL250756'
 'FL250757' 'FL250758' 'FL250759' 'FL250760' 'FL250761' 'FL250762'
 'FL250763' 'FL250764' 'FL250765' 'FL250766' 'FL250767' 'FL250768'
 'FL250769' 'FL250770' 'FL250771' 'FL250772' 'FL250773' 'FL250774'
 'FL250775' 'FL250776' 'FL250777' 'FL250778' 'FL250779' 'FL250780'
 'FL250781' 'FL250782' 'FL250783' 'FL250784' 'FL250785' 'FL250786'
 'FL250787' 'FL250788' 'FL250789' 'FL250790' 'FL250791' 'FL250792'
 'FL250793' 'FL250794' 'FL250795' 'FL250796' 'FL250797' 'FL250798'
 'FL250799' 'FL250800' 'FL250801' 'FL250802' 'FL250803' 'FL250804'
 'FL250805' 'FL250806' 'FL250807' 'FL250808' 'FL250809' 'FL250810'
 'FL250811' 'FL250812' 'FL250813' 'FL250814' 'FL250815' 'FL250816'
 'FL250817' 'FL250818' 'FL250819' 'FL250820' 'FL250821' 'FL250822'
 'FL250823' 'FL250824' 'FL250825' 'FL250826' 'FL250827' 'FL250828'
 'FL250829' 'FL250830' 'FL250831' 'FL250832' 'FL250833' 'FL250834'
 'FL250835' 'FL250836' 'FL250837' 'FL250838' 'FL250839' 'FL250840'
 'FL250841' 'FL250842' 'FL250843' 'FL250844' 'FL250845' 'FL250846'
 'FL250847' 'FL250848' 'FL250849' 'FL250850' 'FL250851' 'FL250852'
 'FL250853' 'FL250854' 'FL250855' 'FL250856' 'FL250857' 'FL250858'
 'FL250859' 'FL250860' 'FL250861' 'FL250862' 'FL250863' 'FL250864'
 'FL250865' 'FL250866' 'FL250867' 'FL250868' 'FL250869' 'FL250870'
 'FL250871' 'FL250872' 'FL250873' 'FL250874' 'FL250875' 'FL250876'
 'FL250877' 'FL250878' 'FL250879' 'FL250880' 'FL250881' 'FL250882'
 'FL250883' 'FL250884' 'FL250885' 'FL250886' 'FL250887' 'FL250888'
 'FL250889' 'FL250890' 'FL250891' 'FL250892' 'FL250893' 'FL250894'
 'FL250895' 'FL250896' 'FL250897' 'FL250898' 'FL250899' 'FL250900'
 'FL250901' 'FL250902' 'FL250903' 'FL250904' 'FL250905' 'FL250906'
 'FL250907' 'FL250908' 'FL250909' 'FL250910' 'FL250911' 'FL250912'
 'FL250913' 'FL250914' 'FL250915' 'FL250916' 'FL250917' 'FL250918'
 'FL250919' 'FL250920' 'FL250921' 'FL250922' 'FL250923' 'FL250924'
 'FL250925' 'FL250926' 'FL250927' 'FL250928' 'FL250929' 'FL250930'
 'FL250931' 'FL250932' 'FL250933' 'FL250934' 'FL250935' 'FL250936'
 'FL250937' 'FL250938' 'FL250939' 'FL250940' 'FL250941' 'FL250942'
 'FL250943' 'FL250944' 'FL250945' 'FL250946' 'FL250947' 'FL250948'
 'FL250949' 'FL250950' 'FL250951' 'FL250952' 'FL250953' 'FL250954'
 'FL250955' 'FL250956' 'FL250957' 'FL250958' 'FL250959' 'FL250960'
 'FL250961' 'FL250962' 'FL250963' 'FL250964' 'FL250965' 'FL250966'
 'FL250967' 'FL250968' 'FL250969' 'FL250970' 'FL250971' 'FL250972'
 'FL250973' 'FL250974' 'FL250975' 'FL250976' 'FL250977' 'FL250978'
 'FL250979' 'FL250980' 'FL250981' 'FL250982' 'FL250983' 'FL250984'
 'FL250985' 'FL250986' 'FL250987' 'FL250988' 'FL250989' 'FL250990'
 'FL250991' 'FL250992' 'FL250993' 'FL250994' 'FL250995' 'FL250996'
 'FL250997' 'FL250998' 'FL250999' 'FL251000']
['Ms. Nicole Kidd' 'Vanessa Garcia' 'Juan Nelson' 'Amanda Spencer'
 'Lynn Curtis DDS' 'Lisa Johnson' 'Eric Myers' 'Ricky Graham'
 'Sean Martin' 'Matthew Lloyd' 'Gavin Randall' 'Michelle Curtis'
 'Alice Schneider' 'Phillip Shelton' 'Edward Ferguson' 'Wyatt Stout'
 'Laura Johnson' 'Scott Burns' 'Tyler Aguirre' 'Matthew Lawson'
 'James Cherry' 'Samuel Sanford' 'Cesar Greene' 'Melanie Carter'
 'Jennifer Martin' 'Anna Mccann' 'Marissa Bass' 'Alexis Day' 'Megan Jones'
 'Lori Smith' 'Eric Carpenter' 'Timothy Daniels' 'Robert Nelson'
 'Michael Anderson' 'Jessica Snyder' 'Emily Daniels' 'Jamie Ramirez'
 'Amy Harrison' 'Melinda White' 'James Hernandez' 'Angelica Rogers'
 'Savannah Williams' 'Kaitlyn Schmidt' 'Jason Singh' 'Michelle Ramirez'
 'James Brown' 'Mrs. Samantha Simmons' 'Chase Mason' 'Dominique Ward'
 'Lance Griffin' 'Julie Burgess' 'Don Scott' 'Kyle Atkinson' 'Jimmy Hogan'
 'Jennifer Mcintyre' 'Larry Simpson' 'Laura Price' 'Mark Wright'
 'Samantha Mcdaniel' 'Barbara Foster' 'Courtney Tran' 'Eddie Todd'
 'Christine Johnson' 'Leah Phelps' 'Rebekah Williams' 'Crystal Wilson'
 'Ashley Cordova' 'Vicki Kelly' 'Corey Warren' 'Gina Thompson'
 'Yvonne Berg' 'Thomas Miller' 'Nicholas Burton' 'Jorge Riley'
 'Melvin Harris' 'Jeremy Meyer' 'Timothy Lee' 'Diana Bautista'
 'Leslie Rodriguez' 'Noah Wiggins' 'Bridget Williams' 'Veronica Baker'
 'Andrew Avila' 'Michael Roberson' 'Austin Jenkins' 'Brenda Green'
 'Samuel Pierce' 'Briana Smith' 'Ronald Barrett' 'Matthew Smith'
 'Logan Huang' 'Miranda Hutchinson' 'Paul Richardson' 'Jose Jones'
 'Denise Smith' 'Shelby Mcmahon' 'Bethany Wright' 'David Ortiz'
 'Andrew Lynch' 'Kristopher Meyers' 'Thomas Roth' 'Vicki Brown'
 'Stacy Sutton' 'Kimberly Holland' 'Travis Richardson' 'Jasmin Ho'
 'Mark Paul' 'Jennifer Lewis' 'Elizabeth Lester' 'Kimberly Griffin'
 'Tyler Warner' 'Jane Cox' 'Leah Williams' 'Kevin Wong' 'Robert Andrews'
 'Jessica Torres' 'Teresa Kim' 'Jon Morgan' 'Gloria Chaney'
 'Jesse Campbell' 'Allison Tucker MD' 'Candice Petersen'
 'Christopher Nichols' 'Debra Garcia' 'Andrew Fuentes' 'Jason Carter'
 'Austin Romero' 'Clayton Burns' 'Jonathan Clark' 'Alexander Griffin'
 'Shelly Whitehead' 'Kaitlyn Davis' 'Christopher Jones' 'Cindy Jacobs'
 'Penny Day' 'Thomas Ingram' 'Donna Hansen' 'Donna Bailey'
 'Joshua Armstrong' 'Jonathan Garza' 'Charles Jones' 'Lindsey Miles'
 'Eduardo Reed' 'Lee Fowler' 'Steven Jones Jr.' 'Ashley Chen'
 'Erica Davis' 'Wayne Gonzales' 'Gary Ballard' 'Maria Mcguire'
 'Matthew Richards' 'Patrick Malone' 'Cindy Martin' 'Anne Edwards'
 'Mitchell Martin' 'Mitchell Patrick' 'Rebecca Lyons' 'Christian Lopez'
 'Nathan Blair' 'Patricia Lopez' 'Michelle Wu' 'Donald Mitchell'
 'Sean Gordon' 'Gregory Clarke' 'Steven Whitney' 'Robin Acosta'
 'John Smith' 'Susan Baker' 'Anthony Larsen' 'Nicholas Carpenter'
 'Debra Salazar' 'William Smith' 'Caroline Gross' 'Jeremy Sawyer'
 'Eduardo Burns' 'Amanda Jones' 'Frederick Ware' 'Michael Black'
 'Patricia Sanders' 'Marc Joseph' 'Vanessa White' 'Jennifer Garcia'
 'Michael Zavala' 'Kimberly Williams' 'Elizabeth Jenkins' 'Brandon Ford'
 'Justin House' 'Henry Mullen' 'Jesse Cochran' 'Melissa Rich'
 'Patrick Dunlap' 'Troy Carson' 'Jennifer Cherry' 'Brandi Tucker'
 'Zachary Burke' 'Thomas Jones' 'Brian Dunn' 'Shirley Strickland'
 'Nicole Meyers' 'Jill Stephens' 'Heidi Miranda' 'Jesus Martinez'
 'Adam Payne' 'Walter Williams' 'Shannon Farmer' 'Peter Reyes'
 'Kristen Knight' 'William Moore Jr.' 'Jennifer Rowe' 'Mikayla Henry'
 'Jacob Kerr' 'Ryan Johnson' 'Michael Ruiz' 'Monica Roberts' 'Danny Brown'
 'Karen Larsen' 'Robert Evans' 'Sean Poole' 'Richard Quinn'
 'Jennifer Gonzalez' 'James Skinner' 'Michelle Hill' 'Jacqueline Williams'
 'Darrell Johnson' 'Ryan Crawford' 'Chelsea Barber' 'Elaine Martinez'
 'Joseph Kent' 'Megan Welch' 'Stephen Ramirez' 'Chloe Gray'
 'Michael Williams Jr.' 'Matthew Martin' 'Julia Murphy' 'Anna Evans'
 'Brenda Fleming' 'Daniel Harrington' 'Daniel Barnett' 'Mark Cummings'
 'Christopher Guerra' 'Sarah Ho' 'Veronica Thomas' 'Mitchell Watson'
 'Monica Murphy' 'Kristen Williams' 'Nicole Wright' 'Andrew Ruiz'
 'Zachary Jackson' 'Stephanie Carter' 'Amy Olson' 'Fred Stark'
 'Jacob Gill' 'Anthony Nichols' 'William Knapp' 'Elizabeth Walker'
 'Brenda Reeves' 'Carrie Little' 'Steven Jackson' 'Mark Perry'
 'Cameron Spencer' 'Jennifer Holmes' 'Jacob Joseph' 'Jeffery Tucker'
 'Jacqueline Drake' 'Brian Bautista' 'Dakota Wells' 'Julie White'
 'Barbara Keith' 'Heather Camacho' 'Melanie Harris' 'Jacqueline Peterson'
 'Nancy Long' 'Mr. Juan Mitchell' 'William Gaines' 'Haley Yates'
 'Richard Mcguire' 'Stephanie Fisher' 'Anthony Goodwin DDS'
 'Meagan Walters' 'David Powell' 'Kelly Jones' 'Dr. Michael Aguilar'
 'Alex Novak' 'Ann Contreras' 'Mary Reed' 'Lauren Ross' 'Candice Wise'
 'Joyce Humphrey' 'James Carr' 'Joseph Mendoza' 'Cathy Baldwin'
 'Christine Hart' 'Mike Stanley' 'Jeffrey Edwards' 'Amy Lee'
 'Mark Thompson' 'Alex Wilson' 'Nancy Mendez' 'Beth Crane' 'Miguel Rogers'
 'Thomas Robles' 'Joel Brown III' 'Olivia Schultz' 'Clayton Pena'
 'Ashley Salazar' 'Robert Lucas' 'David Cox' 'Christian Campbell'
 'Mrs. Angela Ward' 'Lucas Chen' 'Ruben Nelson' 'Brenda Briggs'
 'Ronald Smith' 'Dakota Giles' 'Angela Castillo' 'Allen Lee'
 'Michael Rogers' 'Danielle Costa' 'William Nunez' 'Christopher Riggs'
 'Kathryn Myers' 'Robert Walls' 'Justin Johnson' 'Paula Stevens'
 'Jennifer Allen' 'Mark Hudson' 'Jessica Smith' 'Mike Dean' 'Jose Wilson'
 'Tammy Hill' 'Nathaniel Flores' 'Edwin Carter' 'Patricia Miller'
 'Rebecca Schneider' 'John Greene' 'Brittany Mcdowell' 'Lori Miller'
 'Joseph Robinson' 'Aaron Pruitt' 'Victoria Miller' 'Clarence Vega'
 'Deborah Day' 'Nicole Rocha' 'Elijah Green' 'Emily Johnson'
 'Richard Velasquez Jr.' 'Kurt Wilson' 'Jeremiah Rodriguez' 'Lauren Lang'
 'Matthew Phillips' 'Michael Andersen' 'Amanda Mayo' 'Jessica Vance'
 'Alexa Gallegos' 'Charles Pratt' 'Brian Baker' 'Christina Norman'
 'Laura Kelly' 'John Webb' 'Christopher Burton' 'Bradley Aguilar'
 'Arthur Vasquez' 'Angela Castro' 'Summer Yoder' 'Jackie Allen'
 'Brandon Williams' 'Manuel Torres' 'Scott Keller' 'Deborah Brown'
 'Jennifer Lara' 'Jason Scott' 'Gregory Garrison' 'Chelsea Anderson'
 'Gerald Johnson' 'Kevin Ellis' 'Mitchell Keller' 'Mary Brown'
 'Ronald Walls' 'Anthony Avila' 'Douglas Goodwin' 'James Mills'
 'Nicole Marks' 'Phyllis Dawson' 'Renee Arnold' 'Eric Robinson'
 'Paul Brown' 'Sarah Proctor' 'Matthew Hicks' 'Christopher Black'
 'Joanne Reyes' 'Isaac Gray' 'Joshua Roberts' 'Elizabeth Estrada'
 'Lori Malone' 'Anthony Huynh MD' 'Mindy York' 'Ms. Christine Cherry'
 'Daniel Foster' 'Mr. David Valencia' 'Ethan Adams' 'Brett Moore'
 'Phillip Griffin' 'Stacie Wall' 'Jacob Austin' 'Sabrina Davidson'
 'Dustin Douglas' 'Steven Norris' 'Mindy Sullivan' 'Elizabeth Stone'
 'Diane Flores' 'Jessica Erickson' 'Sara Moses' 'Allison Henderson'
 'Susan Dixon' 'David Morrison' 'James Jacobs' 'Kathleen Quinn'
 'Natalie Frank MD' 'Michael Reed' 'Sheila Smith' 'Morgan Ford'
 'Linda Schultz' 'Regina Daniel' 'Allison Perkins' 'Bradley Weaver'
 'Sarah Hall' 'Diana Walton' 'Donna Davis' 'Christopher Mcclain'
 'Dr. Paul Williamson' 'Barbara Brown' 'Kimberly Allen'
 'Elizabeth Edwards' 'Anthony Downs' 'Jack Ortega' 'Marvin Moore'
 'Tony French' 'Stacy Hudson' 'Scott Washington' 'Timothy Wright'
 'Joseph Gonzalez' 'Andrea Perez' 'Angel Collins' 'Daniel Terry'
 'Steven Whitaker' 'Denise Neal' 'Amanda Jacobs' 'Karen Mercer'
 'Lindsay Hudson' 'Stephanie Armstrong' 'Dr. Jessica Campbell'
 'Curtis Maxwell' 'Adam Kelly PhD' 'Julie Becker' 'James Moore'
 'Danielle Barrera' 'David Sanchez' 'Tiffany Bowman' 'Jesus Quinn'
 'Mr. Danny Morris DDS' 'Nicole York' 'John Mathis' 'Julie Barnett'
 'Jasmine Harris' 'Mary Henry' 'Judith Riggs' 'Justin Ruiz'
 'Jennifer Sullivan' 'Jesse Moran' 'Monica Smith' 'Ian May' 'Kayla Meyers'
 'John Bray' 'James Smith' 'Mark Duncan' 'Matthew Gay' 'Cheryl Freeman'
 'Patrick Welch' 'Craig Levine' 'Richard Harvey' 'Bonnie Sherman'
 'Keith Trujillo' 'Corey Combs' 'Antonio King' 'Jennifer Rogers'
 'Jeffrey Cooper' 'Allison Williams' 'Raymond Sherman' 'Jennifer Nelson'
 'Jennifer Carter' 'Todd Williams' 'Emily Horton' 'Lance Lester'
 'Kevin Flores' 'Aaron Stewart PhD' 'Robin Moore' 'Suzanne Ingram'
 'Jacob Mclaughlin' 'Michael Nunez' 'Isabel Brown' 'Michael Stein'
 'Robert Stone' 'Dillon Henry' 'James Todd' 'Clifford Moore MD'
 'John Rios' 'Anthony Gaines' 'Kristi Brown DVM' 'Ashley Odonnell'
 'Ronald Elliott' 'Lorraine Lowery' 'Victoria Chapman' 'Heather Davis'
 'Diana Chase' 'Danielle Adkins' 'Kenneth Arias' 'Victoria Owen'
 'Christina King' 'Samantha King' 'Scott Compton' 'Monica West'
 'Theresa Stewart' 'Steven Kim' 'Kristi Knight' 'Jason Bryant'
 'Maureen Keith' 'Shawn Hogan' 'William Davis' 'Stacy Bailey'
 'Thomas Dixon' 'Maria Hall' 'Tony Lee' 'Catherine Mccoy MD'

In [234]:
df.columns

Index(['freelancer_ID', 'name', 'gender', 'age', 'country', 'language',
       'primary_skill', 'years_of_experience', 'hourly_rate (USD)', 'rating',
       'is_active', 'client_satisfaction'],
      dtype='object')

Insights gathered
- []  freelancer_ID if want we can remmove the FL Which is in the start and there's no missing values and remove the extra white space and conver it into numeric 
- [] name  make it standardized and remove the extra spaces make the data type to string it has no missing values 
- [] gender we can feature scale this as we can see there many format so keep it short like M and F for all those format and if want you could scale it to 0 and 1 so that it will be easy for the model to understand
- [] age handle the missing values and nothign much in min and max we have seen it has no negative values and any outliers too
- [] country no nul values make it standardized and remove the extra spaces  dtype to string
- [] language same no null value smake it standardized and remove extra spaces dt ype to string
- [] primary_skill  no missing values make it standardized and remove extra spcae and change the stype to string 
- [] years_of_experience it has null values analyze them and follow accordingly else change it to unknown better if ddn't find any relation to other column else we can mediain of the age as the age is raltewd to year of  experiecne 
- []hourly_rate (USD) we have many format where it includes teh dfollar symbols and mention the USD remove all thsoe and make just number and make the dtype to int handle the missing values to unknown or we take median of yeears of experince median like year of experince linkt o hourpay can get the hourly rate too 
- [] rating we could make it median or just fill unknown the missing values
- [] is_active have many format so make 0 to 1 like yes to 1 and no to 0 and we can fill the null by inspwecting like we don't know whether we can fill the midain or keep the naa values as no
- [] client_satisfaction has many missing values we can either get the median or make it null only and remove the percentage sumbol make it to int and mention the %b symbol in colum name

Claude given insights : almost matched with my insights

- [] freelancer_ID — no missing values; remove "FL" prefix if needed, but keep as string/category (not numeric) since it's an identifier, not a value to do math on. Just trim whitespace.
- []  name — no missing values; standardize casing, strip extra whitespace, keep dtype as string.
- []  gender — many formats (f, FEMALE, male, M, etc.); standardize to just M/F, optionally encode to 0/1 for modeling later.
- []  age — has 30 missing values; no negative values or outliers (range 20–60). Fill missing values (median is reasonable here since no outliers).
- []  country — no missing values; standardize casing, remove extra whitespace, dtype string.
- []  language — no missing values; standardize casing, remove extra whitespace, dtype string.
- []  primary_skill — no missing values; standardize casing, remove extra whitespace, dtype string.
- []  years_of_experience — has missing values; fill using median grouped by age bucket (e.g. 20s/30s/40s) since age and experience are related, rather than one global median.
- [] hourly_rate (USD) — mixed formats ($40, USD 100, plain 30); strip $/USD, convert to float (not int, in case of decimals); fill missing values using median grouped by years_of_experience.
- []  rating — has missing values; fill with median, or mark as unknown if you don't want to assume.
- [] is_active — many formats (Yes/No, Y/N, True/False, 1/0); standardize to 0/1; fill missing values with mode (most frequent value), not median, since it's binary.
- [] client_satisfaction — has the most missing values (176); mixed format (84% vs plain 92 with no %); strip % symbol, convert to numeric, fill missing with median or leave as null; rename column to something like client_satisfaction_% to indicate units.

freelancer_ID — no missing values; remove "FL" prefix if needed, but keep as string/category (not numeric) since it's an identifier, not a value to do math on. Just trim whitespace.

In [235]:
df['freelancer_ID'].isna().sum()
df['freelancer_ID']  = df['freelancer_ID'].str.replace('FL' , '')
df

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,250001,Ms. Nicole Kidd,f,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,250002,Vanessa Garcia,FEMALE,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,250003,Juan Nelson,male,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,250005,Lynn Curtis DDS,female,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%
...,...,...,...,...,...,...,...,...,...,...,...,...
995,250996,Albert Wilcox,Male,56.0,Turkey,Turkish,DevOps,13.0,100,0.0,no,68%
996,250997,Cheryl Norris,f,26.0,Germany,German,Blockchain Development,6.0,USD 40,2.8,N,82
997,250998,Kathy Watkins,female,37.0,Japan,Japanese,Data Analysis,15.0,75,NaN,False,94%
998,250999,John Obrien,m,46.0,Russia,Russian,Machine Learning,22.0,100,2.8,yes,97
999,251000,Dawn Green,Female,36.0,Mexico,Spanish,UI/UX Design,18.0,$20,1.7,1,72

In [236]:
df['freelancer_ID'].str.contains('FL').sum()

np.int64(0)

In [237]:
df['freelancer_ID'] = df['freelancer_ID'].str.strip()

In [238]:
df['freelancer_ID'].str.contains(r'^\s|s$', regex=True).sum() # ensuring that there are no white spaces

np.int64(0)

name — no missing values; standardize casing, strip extra whitespace, keep dtype as string.

In [239]:
df['name'].isna().sum()

np.int64(0)

In [240]:
df['name'].duplicated().sum()

np.int64(8)

In [241]:
df[df['name'].duplicated(keep= False)].sort_values('name')

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
669,250670,Amanda Mitchell,FEMALE,25.0,Canada,English,DevOps,1.0,USD 30,3.2,0,87%
692,250693,Amanda Mitchell,female,31.0,France,French,Mobile Apps,NaN,50,1.4,no,80%
295,250296,Amy Lee,FEMALE,56.0,United Kingdom,English,DevOps,34.0,NaN,2.1,yes,84%
486,250487,Amy Lee,f,48.0,Russia,Russian,Blockchain Development,13.0,$100,2.7,NaN,62%
125,250126,Jason Carter,Male,49.0,South Korea,Korean,Data Analysis,19.0,NaN,5.0,Y,83%
416,250417,Jason Carter,M,38.0,Mexico,Spanish,Data Analysis,9.0,$50,0.0,0,74%
5,250006,Lisa Johnson,female,59.0,Netherlands,Dutch,AI,14.0,$30,2.4,False,NaN
689,250690,Lisa Johnson,Female,52.0,Canada,English,UI/UX Design,25.0,100,4.8,N,NaN
377,250378,Mary Brown,female,23.0,Germany,German,Machine Learning,4.0,USD 20,4.7,True,84%
694,250695,Mary Brown,FEMALE,53.0,South Africa,Afrikaans,Graphic Design,35.0,NaN,0.0,1,67%
89,250090,Matthew Smith,m,32.0,India,Hindi,Mobile Apps,10.0,$20,2.4,0,86%
192,250193,Matthew Smith,MALE,41.0,Italy,Italian,DevOps,NaN,$30,1.4,False,74%
217,250218,Robert Evans,M,39.0,South Korea,Korean,Web Development,14.0,USD 100,0.0,Y,92%
912,250913,Robert Evans,MALE,49.0,South Africa,Afrikaans,Data Analysis,NaN,$30,NaN,yes,74%
241,250242,Sarah Ho,female,32.0,Mexico,Spanish,AI,1.0,100,4.7,0,67%
885,250886,Sarah Ho,F,33.0,Netherlands,Dutch,UI/UX Design,6.0,$50,3.1,no,90%

In [242]:
df['name'] = df['name'].str.title()

In [243]:
df['name'] = df['name'].str.strip()

In [244]:
df[df['name'].str.contains(r'^\s|s$')] # this it is for checking the middle spaces which they have.

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
4,250005,Lynn Curtis Dds,female,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%
6,250007,Eric Myers,m,52.0,Indonesia,Indonesian,Data Analysis,10.0,USD 75,3.1,0,94%
11,250012,Michelle Curtis,FEMALE,55.0,Argentina,Spanish,UI/UX Design,15.0,NaN,NaN,Y,86%
17,250018,Scott Burns,M,56.0,India,Hindi,Blockchain Development,NaN,NaN,NaN,NaN,87%
26,250027,Marissa Bass,female,34.0,Japan,Japanese,Blockchain Development,8.0,$20,0.0,True,89%
...,...,...,...,...,...,...,...,...,...,...,...,...
989,250990,Evan Ramos,Male,37.0,Australia,English,Graphic Design,4.0,75,3.2,False,76%
990,250991,Michelle Solis,FEMALE,21.0,Argentina,Spanish,AI,2.0,100,3.7,yes,73
993,250994,Jim Weiss,male,46.0,Russia,Russian,Mobile Apps,8.0,20,2.2,NaN,89
996,250997,Cheryl Norris,f,26.0,Germany,German,Blockchain Development,6.0,USD 40,2.8,N,82
997,250998,Kathy Watkins,female,37.0,Japan,Japanese,Data Analysis,15.0,75,NaN,False,94%

In [245]:
df.loc[df['name'].str.contains(r'[^A-Za-z0-9,.\s]',na=False , regex= True),'name'].sum() # this explains that there is no special character

0

In [246]:
df['name']  = df['name'].astype('string')
df['name'].dtype

string[python]

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   freelancer_ID        1000 non-null   object
 1   name                 1000 non-null   string
 2   gender               1000 non-null   object
 3   age                  970 non-null    float64
 4   country              1000 non-null   object
 5   language             1000 non-null   object
 6   primary_skill        1000 non-null   object
 7   years_of_experience  949 non-null    float64
 8   hourly_rate (USD)    906 non-null    object
 9   rating               899 non-null    float64
 10  is_active            911 non-null    object
 11  client_satisfaction  824 non-null    object
dtypes: float64(3), object(8), string(1)
memory usage: 93.9+ KB

gender — many formats (f, FEMALE, male, M, etc.); standardize to just M/F, optionally encode to 0/1 for modeling later.

In [248]:
df['gender'].unique()

array(['f', 'FEMALE', 'male', 'F', 'female', 'm', 'MALE', 'Female', 'M',
       'Male'], dtype=object)

In [249]:
df['gender'] = df['gender'].replace({

    'f' : 'F', 'FEMALE' : 'F', 'female': 'F','Female': 'F',

     'male': 'M' , 'm' : 'M' , 'MALE':'M' , 'Male' : 'M'
    })

In [250]:
df['gender'].unique()

array(['F', 'M'], dtype=object)

In [251]:
df.head()

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,250001,Ms. Nicole Kidd,F,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,250002,Vanessa Garcia,F,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,250003,Juan Nelson,M,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,250005,Lynn Curtis Dds,F,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%

age — has 30 missing values; no negative values or outliers (range 20–60). Fill missing values (median is reasonable here since no outliers).

In [252]:
df['age'].describe()

count    970.000000
mean      40.509278
std       11.942605
min       20.000000
25%       31.000000
50%       41.000000
75%       51.000000
max       60.000000
Name: age, dtype: float64

In [253]:
df['age'].median()
df[df['age'].isna()]

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
20,250021,James Cherry,M,NaN,Indonesia,Indonesian,AI,9.0,50,1.8,False,65%
33,250034,Michael Anderson,M,NaN,South Korea,Korean,AI,9.0,40,2.4,yes,82
53,250054,Jimmy Hogan,M,NaN,Spain,Spanish,UI/UX Design,1.0,30,0.0,0,68%
68,250069,Corey Warren,M,NaN,Argentina,Spanish,UI/UX Design,6.0,100,1.5,False,NaN
82,250083,Andrew Avila,M,NaN,China,Mandarin,DevOps,3.0,40,4.6,N,74%
98,250099,Andrew Lynch,M,NaN,United States,English,UI/UX Design,5.0,$20,1.1,no,74%
133,250134,Cindy Jacobs,F,NaN,Brazil,Portuguese,Machine Learning,4.0,NaN,2.5,NaN,70%
150,250151,Matthew Richards,M,NaN,Turkey,Turkish,Data Analysis,10.0,USD 40,0.0,NaN,NaN
161,250162,Donald Mitchell,M,NaN,Argentina,Spanish,Data Analysis,12.0,$30,4.1,no,68%
170,250171,Debra Salazar,F,NaN,Netherlands,Dutch,Blockchain Development,NaN,40,2.8,N,80%
213,250214,Michael Ruiz,M,NaN,Germany,German,Blockchain Development,8.0,$40,0.0,N,64%
215,250216,Danny Brown,M,NaN,India,Hindi,Machine Learning,12.0,$20,0.0,True,80%
272,250273,Nancy Long,F,NaN,United Kingdom,English,Cybersecurity,5.0,100,1.3,0,60%
299,250300,Beth Crane,F,NaN,Netherlands,Dutch,Mobile Apps,6.0,40,3.5,0,76%
316,250317,Allen Lee,M,NaN,Netherlands,Dutch,DevOps,0.0,$100,5.0,N,NaN
366,250367,Brandon Williams,M,NaN,China,Mandarin,AI,9.0,USD 40,1.7,1,72
374,250375,Gerald Johnson,M,NaN,Argentina,Spanish,Blockchain Development,NaN,$50,2.1,1,82%
383,250384,Phyllis Dawson,F,NaN,United Kingdom,English,UI/UX Design,0.0,USD 20,4.8,0,74%
404,250405,Jacob Austin,M,NaN,South Africa,Afrikaans,Web Development,10.0,20,1.8,yes,85
462,250463,Nicole York,F,NaN,Japan,Japanese,DevOps,12.0,$50,4.1,Y,62%
481,250482,Richard Harvey,M,NaN,United Kingdom,English,Web Development,NaN,40,1.9,1,94%
482,250483,Bonnie Sherman,F,NaN,Netherlands,Dutch,Mobile Apps,11.0,$20,3.6,no,69%
624,250625,David Bishop,M,NaN,Spain,Spanish,Blockchain Development,1.0,USD 50,2.8,no,87%
646,250647,Brandon Newman,M,NaN,India,Hindi,Cybersecurity,9.0,100,4.8,Y,72%
709,250710,David Griffin,M,NaN,Russia,Russian,AI,12.0,30,2.6,Y,NaN
751,250752,Patricia Scott,F,NaN,Argentina,Spanish,Web Development,0.0,40,NaN,Y,74%
782,250783,Cynthia Walton,F,NaN,Argentina,Spanish,Blockchain Development,9.0,$100,4.5,Y,83
891,250892,Austin Allen,M,NaN,Italy,Italian,UI/UX Design,11.0,USD 100,2.5,yes,80
946,250947,Thomas Jackson,M,NaN,Mexico,Spanish,AI,1.0,75,0.0,True,94%
982,250983,Cindy Williams,F,NaN,South Africa,Afrikaans,Graphic Design,0.0,$40,0.0,no,97%

In [254]:
df

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,250001,Ms. Nicole Kidd,F,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,250002,Vanessa Garcia,F,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,250003,Juan Nelson,M,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,250005,Lynn Curtis Dds,F,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%
...,...,...,...,...,...,...,...,...,...,...,...,...
995,250996,Albert Wilcox,M,56.0,Turkey,Turkish,DevOps,13.0,100,0.0,no,68%
996,250997,Cheryl Norris,F,26.0,Germany,German,Blockchain Development,6.0,USD 40,2.8,N,82
997,250998,Kathy Watkins,F,37.0,Japan,Japanese,Data Analysis,15.0,75,NaN,False,94%
998,250999,John Obrien,M,46.0,Russia,Russian,Machine Learning,22.0,100,2.8,yes,97
999,251000,Dawn Green,F,36.0,Mexico,Spanish,UI/UX Design,18.0,$20,1.7,1,72

In [255]:
mising_values = df['age'].isna()

In [256]:
df['years_of_experience'].isna().sum()

np.int64(51)

In [257]:
df['exp_group'] = pd.cut(df['years_of_experience'] , bins = [-1,2,5,20,30,100], labels=['Beginner','Junior','Mid','Professional','Veteran'])
df['age'] = df.groupby('exp_group')['age'].transform(lambda x : x.fillna(x.median()))
df['age'] = df['age'].fillna(df['age'].median())

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_73665/1661787127.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['age'] = df.groupby('exp_group')['age'].transform(lambda x : x.fillna(x.median()))

In [258]:
df[['years_of_experience','exp_group']]

     years_of_experience     exp_group
0                   11.0           Mid
1                   34.0       Veteran
2                   31.0       Veteran
3                    4.0        Junior
4                   27.0  Professional
..                   ...           ...
995                 13.0           Mid
996                  6.0           Mid
997                 15.0           Mid
998                 22.0  Professional
999                 18.0           Mid

[1000 rows x 2 columns]

In [259]:
df['age'].isna().sum()

np.int64(0)

In [260]:

df[mising_values][['age','years_of_experience','exp_group']]

      age  years_of_experience exp_group
20   41.0                  9.0       Mid
33   41.0                  9.0       Mid
53   26.0                  1.0  Beginner
68   41.0                  6.0       Mid
82   34.0                  3.0    Junior
98   34.0                  5.0    Junior
133  34.0                  4.0    Junior
150  41.0                 10.0       Mid
161  41.0                 12.0       Mid
170  41.0                  NaN       NaN
213  41.0                  8.0       Mid
215  41.0                 12.0       Mid
272  34.0                  5.0    Junior
299  41.0                  6.0       Mid
316  26.0                  0.0  Beginner
366  41.0                  9.0       Mid
374  41.0                  NaN       NaN
383  26.0                  0.0  Beginner
404  41.0                 10.0       Mid
462  41.0                 12.0       Mid
481  41.0                  NaN       NaN
482  41.0                 11.0       Mid
624  26.0                  1.0  Beginner
646  41.0                  9.0       Mid
709  41.0                 12.0       Mid
751  26.0                  0.0  Beginner
782  41.0                  9.0       Mid
891  41.0                 11.0       Mid
946  26.0                  1.0  Beginner
982  26.0                  0.0  Beginner

In [261]:
df[['age','years_of_experience','exp_group']]

      age  years_of_experience     exp_group
0    52.0                 11.0           Mid
1    52.0                 34.0       Veteran
2    53.0                 31.0       Veteran
3    38.0                  4.0        Junior
4    53.0                 27.0  Professional
..    ...                  ...           ...
995  56.0                 13.0           Mid
996  26.0                  6.0           Mid
997  37.0                 15.0           Mid
998  46.0                 22.0  Professional
999  36.0                 18.0           Mid

[1000 rows x 3 columns]

country — no missing values; standardize casing, remove extra whitespace, dtype string.

In [262]:
df['country'].isna().sum()

np.int64(0)

In [263]:
df['country'] = df['country'].str.title()

In [264]:
df['country'] = df['country'].str.strip()

In [265]:
df[df['country'].str.contains(r'^\s|\s$',regex=True)]

Empty DataFrame
Columns: [freelancer_ID, name, gender, age, country, language, primary_skill, years_of_experience, hourly_rate (USD), rating, is_active, client_satisfaction, exp_group]
Index: []

In [266]:
df['country'] = df['country'].astype('string')

In [267]:
df['country'].dtype

string[python]

language — no missing values; standardize casing, remove extra whitespace, dtype string.
primary_skill — no missing values; standardize casing, remove extra whitespace, dtype string.

In [268]:
df['language'].isna().sum()

np.int64(0)

In [269]:
df['language'] = df['language'].str.title()

In [270]:
df['language'] = df['language'].str.strip()

In [271]:
df[df['language'].str.contains(r'^\s|\s$',regex=True)]

Empty DataFrame
Columns: [freelancer_ID, name, gender, age, country, language, primary_skill, years_of_experience, hourly_rate (USD), rating, is_active, client_satisfaction, exp_group]
Index: []

In [272]:
df['primary_skill'].isna().sum()

np.int64(0)

In [273]:
df['primary_skill'] = df['primary_skill'].str.title()

In [274]:
df['primary_skill'] = df['primary_skill'].str.strip()

In [275]:
df

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction,exp_group
0,250001,Ms. Nicole Kidd,F,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN,Mid
1,250002,Vanessa Garcia,F,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%,Veteran
2,250003,Juan Nelson,M,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%,Veteran
3,250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%,Junior
4,250005,Lynn Curtis Dds,F,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%,Professional
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,250996,Albert Wilcox,M,56.0,Turkey,Turkish,Devops,13.0,100,0.0,no,68%,Mid
996,250997,Cheryl Norris,F,26.0,Germany,German,Blockchain Development,6.0,USD 40,2.8,N,82,Mid
997,250998,Kathy Watkins,F,37.0,Japan,Japanese,Data Analysis,15.0,75,NaN,False,94%,Mid
998,250999,John Obrien,M,46.0,Russia,Russian,Machine Learning,22.0,100,2.8,yes,97,Professional
999,251000,Dawn Green,F,36.0,Mexico,Spanish,Ui/Ux Design,18.0,$20,1.7,1,72,Mid

years_of_experience — has missing values; fill using median grouped by age bucket (e.g. 20s/30s/40s) since age and experience are related, rather than one global median.

In [276]:
missing_values = df['years_of_experience'].isna()
missing_values.sum()

np.int64(51)

In [277]:
df['age_group'] = pd.cut(df['age'], bins=[19,29,39,49,60], labels=['20s','30s','40s','50s'])
grouped_median = df.groupby('age_group')['years_of_experience'].transform(lambda x : x.fillna(x.median()))
df['years_of_experience'] =df['years_of_experience'].fillna(grouped_median)

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_73665/3711717219.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_median = df.groupby('age_group')['years_of_experience'].transform(lambda x : x.fillna(x.median()))

In [278]:
df['age_group'].isna().sum()

np.int64(0)

In [279]:
df['years_of_experience'].isna().sum()

np.int64(0)

In [280]:
df[missing_values][['age','years_of_experience','age_group']]

      age  years_of_experience age_group
17   41.0                 12.0       40s
21   41.0                 12.0       40s
43   41.0                 12.0       40s
58   41.0                 12.0       40s
75   41.0                 12.0       40s
157  41.0                 12.0       40s
165  41.0                 12.0       40s
170  41.0                 12.0       40s
189  41.0                 12.0       40s
192  41.0                 12.0       40s
314  41.0                 12.0       40s
340  41.0                 12.0       40s
355  41.0                 12.0       40s
365  41.0                 12.0       40s
368  41.0                 12.0       40s
374  41.0                 12.0       40s
392  41.0                 12.0       40s
426  41.0                 12.0       40s
430  41.0                 12.0       40s
441  41.0                 12.0       40s
443  41.0                 12.0       40s
449  41.0                 12.0       40s
456  41.0                 12.0       40s
473  41.0                 12.0       40s
481  41.0                 12.0       40s
506  41.0                 12.0       40s
529  41.0                 12.0       40s
550  41.0                 12.0       40s
575  41.0                 12.0       40s
626  41.0                 12.0       40s
630  41.0                 12.0       40s
687  41.0                 12.0       40s
688  41.0                 12.0       40s
692  41.0                 12.0       40s
696  41.0                 12.0       40s
733  41.0                 12.0       40s
734  41.0                 12.0       40s
757  41.0                 12.0       40s
805  41.0                 12.0       40s
859  41.0                 12.0       40s
861  41.0                 12.0       40s
866  41.0                 12.0       40s
872  41.0                 12.0       40s
875  41.0                 12.0       40s
882  41.0                 12.0       40s
884  41.0                 12.0       40s
887  41.0                 12.0       40s
912  41.0                 12.0       40s
927  41.0                 12.0       40s
962  41.0                 12.0       40s
986  41.0                 12.0       40s

In [281]:
print(df['years_of_experience'].unique())

[11. 34. 31.  4. 27. 14. 10. 22. 17. 15. 18. 20.  0. 13. 12.  3.  9. 21.
  8. 19. 32. 28.  6. 23.  7.  1. 33. 16. 35. 38.  5. 30.  2. 25. 39. 29.
 40. 26. 24. 37. 41.]

hourly_rate (USD) — mixed formats ($40, USD 100, plain 30); strip $/USD, convert to float (not int, in case of decimals); fill missing values using median grouped by years_of_experience.

In [282]:
df['hourly_rate (USD)']

0          100
1      USD 100
2           50
3          $40
4           30
        ...
995        100
996     USD 40
997         75
998        100
999        $20
Name: hourly_rate (USD), Length: 1000, dtype: object

In [283]:
df['hourly_rate (USD)'].unique()

array(['100', 'USD 100', '50', '$40', '30', '$30', 'USD 75', 'USD 40',
       nan, '$50', '40', '75', 'USD 50', 'USD 30', '$20', '20', '$75',
       '$100', 'USD 20'], dtype=object)

In [284]:
df['hourly_rate (USD)'] = df['hourly_rate (USD)'].str.replace(r'USD|\$' , '' , regex= True)

In [285]:
df['hourly_rate (USD)'].unique()

array(['100', ' 100', '50', '40', '30', ' 75', ' 40', nan, '75', ' 50',
       ' 30', '20', ' 20'], dtype=object)

In [286]:
df['hourly_rate (USD)']
missing_hours=df['hourly_rate (USD)'].isna()

In [287]:
df[df['hourly_rate (USD)'].isna()]
df['hourly_rate (USD)'] = df['hourly_rate (USD)'].astype('float')
df['hourly_rate (USD)'].dtype

dtype('float64')

In [288]:
grouped_median = df.groupby('exp_group')['hourly_rate (USD)'].transform(lambda x : x.fillna(x.median()))
df['hourly_rate (USD)'] =df['hourly_rate (USD)'].fillna(grouped_median)
df['hourly_rate (USD)'] =df['hourly_rate (USD)'].fillna(df['hourly_rate (USD)'].median())

/var/folders/qw/_nk9z1hd74q9vjp80k85r5l80000gn/T/ipykernel_73665/1999403151.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_median = df.groupby('exp_group')['hourly_rate (USD)'].transform(lambda x : x.fillna(x.median()))

In [289]:
df['hourly_rate (USD)'].isna().sum()

np.int64(0)

In [290]:
df[missing_hours][['age','hourly_rate (USD)' , 'years_of_experience' , 'exp_group']]

      age  hourly_rate (USD)  years_of_experience exp_group
8    26.0               40.0                  4.0    Junior
11   55.0               40.0                 15.0       Mid
12   57.0               40.0                 18.0       Mid
17   41.0               40.0                 12.0       NaN
21   41.0               40.0                 12.0       NaN
..    ...                ...                  ...       ...
934  38.0               40.0                 11.0       Mid
937  21.0               40.0                  0.0  Beginner
945  24.0               40.0                  2.0  Beginner
969  49.0               40.0                  1.0  Beginner
974  43.0               40.0                  2.0  Beginner

[94 rows x 4 columns]

In [291]:
df['exp_group'] = pd.cut(df['years_of_experience'], bins=[-1,2,15,20,25,100], labels=['Beginner','Junior','Mid','Professional','Veteran'])
print(df['exp_group'].isnull().sum())  # should now be 0

0

In [292]:
df

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction,exp_group,age_group
0,250001,Ms. Nicole Kidd,F,52.0,Italy,Italian,Blockchain Development,11.0,100.0,NaN,0,NaN,Junior,50s
1,250002,Vanessa Garcia,F,52.0,Australia,English,Mobile Apps,34.0,100.0,3.3,1,84%,Veteran,50s
2,250003,Juan Nelson,M,53.0,Germany,German,Graphic Design,31.0,50.0,0.0,N,71%,Veteran,50s
3,250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,40.0,1.5,N,90%,Junior,30s
4,250005,Lynn Curtis Dds,F,53.0,Germany,German,Web Development,27.0,30.0,4.8,0,83%,Veteran,50s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,250996,Albert Wilcox,M,56.0,Turkey,Turkish,Devops,13.0,100.0,0.0,no,68%,Junior,50s
996,250997,Cheryl Norris,F,26.0,Germany,German,Blockchain Development,6.0,40.0,2.8,N,82,Junior,20s
997,250998,Kathy Watkins,F,37.0,Japan,Japanese,Data Analysis,15.0,75.0,NaN,False,94%,Junior,30s
998,250999,John Obrien,M,46.0,Russia,Russian,Machine Learning,22.0,100.0,2.8,yes,97,Professional,40s
999,251000,Dawn Green,F,36.0,Mexico,Spanish,Ui/Ux Design,18.0,20.0,1.7,1,72,Mid,30s

In [293]:
df['hourly_rate (USD)'].isna().sum()

np.int64(0)

rating — has missing values; fill with median, or mark as unknown if you don't want to assume.

In [294]:
df['rating'].isna().sum()

np.int64(101)

In [295]:
df['rating'] = df['rating'].fillna(df['rating'].median())

In [296]:
df['rating'].isna().sum()

np.int64(0)

is_active — many formats (Yes/No, Y/N, True/False, 1/0); standardize to 0/1; fill missing values with mode (most frequent value), not median, since it's binary.

In [297]:
df['is_active'].unique()

array(['0', '1', 'N', 'False', 'True', 'yes', 'Y', nan, 'no'],
      dtype=object)

In [298]:
df['is_active'] = df['is_active'].replace({
    'N' : '0' ,'False' : '0' , 'no' : '0',
    'True' : '1', 'yes' : '1', 'Y' : '1'
})

In [299]:
df['is_active'].unique()

array(['0', '1', nan], dtype=object)

In [300]:
df['is_active'].isna().sum()

np.int64(89)

In [301]:
df['is_active'] = df['is_active'].fillna(df['is_active'].mode()[0])

In [302]:
df['is_active'].isna().sum()

np.int64(0)

In [303]:
df['is_active'].mode()[0]

'0'

In [305]:
df['is_active'].unique()

array(['0', '1'], dtype=object)

client_satisfaction — has the most missing values (176); mixed format (84% vs plain 92 with no %); strip % symbol, convert to numeric, fill missing with median or leave as null; rename column to something like client_satisfaction_% to indicate units.

In [ ]:
df['client_satisfaction'].isna().sum()

np.int64(176)

In [309]:
df['client_satisfaction'] =  df['client_satisfaction'].str.replace('%' , '')

In [310]:
df['client_satisfaction'].unique()

array([nan, '84', '71', '90', '83', '94', '76', '77', '86', '93', '70',
       '69', '60', '87', '75', '68', '65', '100', '92', '89', '62', '82',
       '81', '63', '67', '80', '74', '85', '79', '72', '64', '88', '96',
       '61', '97', '73', '78', '95', '66', '91', '99', '98'], dtype=object)

In [316]:
df['client_satisfaction'] = pd.to_numeric(df['client_satisfaction'],errors='coerce')

df['client_satisfaction']  = df['client_satisfaction'].fillna(df['client_satisfaction'].median())

In [318]:
df['client_satisfaction'].isna().sum()

np.int64(0)

In [319]:
df.describe()

,age,years_of_experience,hourly_rate (USD),rating,client_satisfaction
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,40.482000,11.374000,51.420000,2.521400,79.222000
std,11.565528,9.431388,26.228258,1.466572,10.434059
min,20.000000,0.000000,20.000000,0.000000,60.000000
25%,31.000000,3.000000,30.000000,1.500000,71.000000
50%,41.000000,10.000000,40.000000,2.600000,79.000000
75%,50.000000,17.000000,75.000000,3.700000,87.000000
max,60.000000,41.000000,100.000000,5.000000,100.000000

In [320]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   freelancer_ID        1000 non-null   object
 1   name                 1000 non-null   string
 2   gender               1000 non-null   object
 3   age                  1000 non-null   float64
 4   country              1000 non-null   string
 5   language             1000 non-null   object
 6   primary_skill        1000 non-null   object
 7   years_of_experience  1000 non-null   float64
 8   hourly_rate (USD)    1000 non-null   float64
 9   rating               1000 non-null   float64
 10  is_active            1000 non-null   object
 11  client_satisfaction  1000 non-null   float64
 12  exp_group            1000 non-null   category
 13  age_group            1000 non-null   category
dtypes: category(2), float64(5), object(5), string(2)
memory usage: 96.2+ KB

In [322]:
df['is_active'] = pd.to_numeric(df['is_active'])

In [323]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   freelancer_ID        1000 non-null   object
 1   name                 1000 non-null   string
 2   gender               1000 non-null   object
 3   age                  1000 non-null   float64
 4   country              1000 non-null   string
 5   language             1000 non-null   object
 6   primary_skill        1000 non-null   object
 7   years_of_experience  1000 non-null   float64
 8   hourly_rate (USD)    1000 non-null   float64
 9   rating               1000 non-null   float64
 10  is_active            1000 non-null   int64
 11  client_satisfaction  1000 non-null   float64
 12  exp_group            1000 non-null   category
 13  age_group            1000 non-null   category
dtypes: category(2), float64(5), int64(1), object(4), string(2)
memory usage: 96.2+ KB

In [324]:
df.to_csv("cleaned_freelance.csv")