In [125]:
import os
os.listdir()

['Housing.csv',
 'salesdata.csv',
 'first program.ipynb',
 'sales_data.csv',
 'returnsdata.csv',
 'weather_data.csv',
 'Iris_data.csv',
 'state_wise_covid_data.csv',
 'heart_data.csv',
 'Loan_payments_data.csv',
 'students_marks.csv',
 '.ipynb_checkpoints',
 'sales_data_preprocess.csv']

In [126]:
import pandas as pd
df_check = pd.read_csv("state_wise_covid_data.csv")
df_check

,State,Confirmed,Recovered,Deaths,Active,State_code
0,Total,34285612,33661339,458470,152606,TT
1,Andaman and Nicobar Islands,7651,7518,129,4,AN
2,Andhra Pradesh,2066450,2047722,14373,4355,AP
3,Arunachal Pradesh,55155,54774,280,101,AR
4,Assam,610645,600974,5997,2327,AS
5,Bihar,726098,716390,9661,46,BR
6,Chandigarh,65351,64495,820,36,CH
7,Chhattisgarh,1006052,992159,13577,316,CT
8,Dadra and Nagar,10681,10644,4,2,DN
9,Delhi,1439870,1414431,25091,348,DL
10,Goa,178108,174392,3364,352,GA
11,Gujarat,826577,816283,10089,205,GJ
12,Haryana,771252,761068,10049,135,HR
13,Himachal Pradesh,224106,218410,3738,1942,HP
14,Jammu and Kashmir,332249,326915,4432,902,JK
15,Jharkhand,348764,343518,5138,108,JH
16,Karnataka,2988333,2941578,38082,8644,KA
17,Kerala,4968657,4857181,31681,79266,KL
18,Ladakh,20962,20687,208,67,LA
19,Lakshadweep,10365,10270,51,0,LD
20,Madhya Pradesh,792854,782215,10524,115,MP
21,Maharashtra,6611078,6450585,140216,16658,MH
22,Manipur,123731,121102,1921,708,MN
23,Meghalaya,83627,81746,1450,431,ML
24,Mizoram,121359,114612,432,6315,MZ
25,Nagaland,31842,29904,685,210,NL
26,Odisha,1041457,1029147,8386,3924,OR
27,Puducherry,128013,125726,1857,430,PY
28,Punjab,602401,585591,16559,251,PB
29,Rajasthan,954429,945443,8954,32,RJ
30,Sikkim,31979,31063,396,195,SK
31,State Unassigned,0,0,0,0,UN
32,Tamil Nadu,2702623,2655015,36116,11492,TN
33,Telangana,671463,663498,3956,4009,TG
34,Tripura,84468,83466,813,126,TR
35,Uttar Pradesh,1710158,1687151,22900,107,UP
36,Uttarakhand,343896,330195,7400,151,UT
37,West Bengal,1592908,1565471,19141,8296,WB

In [127]:
import pandas as pd
df = pd.read_csv("sales_data.csv")

In [128]:
import pandas as pd
df = pd.read_csv("sales_data.csv")
df["Quantity"]

0      2
1      3
2      2
3      5
4      2
      ..
685    3
686    2
687    3
688    2
689    1
Name: Quantity, Length: 690, dtype: int64

In [129]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.head()

,State,Confirmed,Recovered,Deaths,Active,State_code
0,Total,34285612,33661339,458470,152606,TT
1,Andaman and Nicobar Islands,7651,7518,129,4,AN
2,Andhra Pradesh,2066450,2047722,14373,4355,AP
3,Arunachal Pradesh,55155,54774,280,101,AR
4,Assam,610645,600974,5997,2327,AS

In [130]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.tail()

            State  Confirmed  Recovered  Deaths  Active State_code
33      Telangana     671463     663498    3956    4009         TG
34        Tripura      84468      83466     813     126         TR
35  Uttar Pradesh    1710158    1687151   22900     107         UP
36    Uttarakhand     343896     330195    7400     151         UT
37    West Bengal    1592908    1565471   19141    8296         WB

In [131]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       38 non-null     object
 1   Confirmed   38 non-null     int64
 2   Recovered   38 non-null     int64
 3   Deaths      38 non-null     int64
 4   Active      38 non-null     int64
 5   State_code  38 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.9+ KB

In [132]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.describe()

          Confirmed     Recovered         Deaths         Active
count  3.800000e+01  3.800000e+01      38.000000      38.000000
mean   1.804506e+06  1.771649e+06   24130.000000    8031.894737
std    5.587947e+06  5.484967e+06   76125.758653   27398.553940
min    0.000000e+00  0.000000e+00       0.000000       0.000000
25%    8.383725e+04  8.217600e+04     814.750000     107.250000
50%    4.755825e+05  4.645545e+05    5567.500000     283.500000
75%    1.032606e+06  1.019900e+06   14174.000000    3524.750000
max    3.428561e+07  3.366134e+07  458470.000000  152606.000000

In [133]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.shape

(38, 6)

In [134]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.columns

Index(['State', 'Confirmed', 'Recovered', 'Deaths', 'Active', 'State_code'], dtype='object')

In [135]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.dtypes

State         object
Confirmed      int64
Recovered      int64
Deaths         int64
Active         int64
State_code    object
dtype: object

In [136]:
import pandas as pd
df = pd.read_csv("state_wise_covid_data.csv")
df.isnull()

    State  Confirmed  Recovered  Deaths  Active  State_code
0   False      False      False   False   False       False
1   False      False      False   False   False       False
2   False      False      False   False   False       False
3   False      False      False   False   False       False
4   False      False      False   False   False       False
5   False      False      False   False   False       False
6   False      False      False   False   False       False
7   False      False      False   False   False       False
8   False      False      False   False   False       False
9   False      False      False   False   False       False
10  False      False      False   False   False       False
11  False      False      False   False   False       False
12  False      False      False   False   False       False
13  False      False      False   False   False       False
14  False      False      False   False   False       False
15  False      False      False   False   False       False
16  False      False      False   False   False       False
17  False      False      False   False   False       False
18  False      False      False   False   False       False
19  False      False      False   False   False       False
20  False      False      False   False   False       False
21  False      False      False   False   False       False
22  False      False      False   False   False       False
23  False      False      False   False   False       False
24  False      False      False   False   False       False
25  False      False      False   False   False       False
26  False      False      False   False   False       False
27  False      False      False   False   False       False
28  False      False      False   False   False       False
29  False      False      False   False   False       False
30  False      False      False   False   False       False
31  False      False      False   False   False       False
32  False      False      False   False   False       False
33  False      False      False   False   False       False
34  False      False      False   False   False       False
35  False      False      False   False   False       False
36  False      False      False   False   False       False
37  False      False      False   False   False       False

In [137]:
import pandas as p
df = p.read_csv("state_wise_covid_data.csv")
df['State'].value_counts

<bound method IndexOpsMixin.value_counts of 0                           Total
1     Andaman and Nicobar Islands
2                  Andhra Pradesh
3               Arunachal Pradesh
4                           Assam
5                           Bihar
6                      Chandigarh
7                    Chhattisgarh
8                Dadra and Nagar
9                           Delhi
10                            Goa
11                        Gujarat
12                        Haryana
13               Himachal Pradesh
14              Jammu and Kashmir
15                      Jharkhand
16                      Karnataka
17                         Kerala
18                         Ladakh
19                    Lakshadweep
20                 Madhya Pradesh
21                    Maharashtra
22                        Manipur
23                      Meghalaya
24                        Mizoram
25                       Nagaland
26                         Odisha
27                     Puducherry
28                         Punjab
29                      Rajasthan
30                         Sikkim
31               State Unassigned
32                     Tamil Nadu
33                      Telangana
34                        Tripura
35                  Uttar Pradesh
36                    Uttarakhand
37                    West Bengal
Name: State, dtype: object>

In [138]:
import pandas as p
df = p.read_csv("state_wise_covid_data.csv")
print (df['State'])

0                           Total
1     Andaman and Nicobar Islands
2                  Andhra Pradesh
3               Arunachal Pradesh
4                           Assam
5                           Bihar
6                      Chandigarh
7                    Chhattisgarh
8                Dadra and Nagar
9                           Delhi
10                            Goa
11                        Gujarat
12                        Haryana
13               Himachal Pradesh
14              Jammu and Kashmir
15                      Jharkhand
16                      Karnataka
17                         Kerala
18                         Ladakh
19                    Lakshadweep
20                 Madhya Pradesh
21                    Maharashtra
22                        Manipur
23                      Meghalaya
24                        Mizoram
25                       Nagaland
26                         Odisha
27                     Puducherry
28                         Punjab
29                      Rajasthan
30                         Sikkim
31               State Unassigned
32                     Tamil Nadu
33                      Telangana
34                        Tripura
35                  Uttar Pradesh
36                    Uttarakhand
37                    West Bengal
Name: State, dtype: object

In [139]:
print(df.Active)

0     152606
1          4
2       4355
3        101
4       2327
5         46
6         36
7        316
8          2
9        348
10       352
11       205
12       135
13      1942
14       902
15       108
16      8644
17     79266
18        67
19         0
20       115
21     16658
22       708
23       431
24      6315
25       210
26      3924
27       430
28       251
29        32
30       195
31         0
32     11492
33      4009
34       126
35       107
36       151
37      8296
Name: Active, dtype: int64

In [140]:
print(df.iloc[0,2])

33661339

In [141]:
greater = df[df['Active'] > 10]
print(greater)

                State  Confirmed  Recovered  Deaths  Active State_code
0               Total   34285612   33661339  458470  152606         TT
2      Andhra Pradesh    2066450    2047722   14373    4355         AP
3   Arunachal Pradesh      55155      54774     280     101         AR
4               Assam     610645     600974    5997    2327         AS
5               Bihar     726098     716390    9661      46         BR
6          Chandigarh      65351      64495     820      36         CH
7        Chhattisgarh    1006052     992159   13577     316         CT
9               Delhi    1439870    1414431   25091     348         DL
10                Goa     178108     174392    3364     352         GA
11            Gujarat     826577     816283   10089     205         GJ
12            Haryana     771252     761068   10049     135         HR
13   Himachal Pradesh     224106     218410    3738    1942         HP
14  Jammu and Kashmir     332249     326915    4432     902         JK
15          Jharkhand     348764     343518    5138     108         JH
16          Karnataka    2988333    2941578   38082    8644         KA
17             Kerala    4968657    4857181   31681   79266         KL
18             Ladakh      20962      20687     208      67         LA
20     Madhya Pradesh     792854     782215   10524     115         MP
21        Maharashtra    6611078    6450585  140216   16658         MH
22            Manipur     123731     121102    1921     708         MN
23          Meghalaya      83627      81746    1450     431         ML
24            Mizoram     121359     114612     432    6315         MZ
25           Nagaland      31842      29904     685     210         NL
26             Odisha    1041457    1029147    8386    3924         OR
27         Puducherry     128013     125726    1857     430         PY
28             Punjab     602401     585591   16559     251         PB
29          Rajasthan     954429     945443    8954      32         RJ
30             Sikkim      31979      31063     396     195         SK
32         Tamil Nadu    2702623    2655015   36116   11492         TN
33          Telangana     671463     663498    3956    4009         TG
34            Tripura      84468      83466     813     126         TR
35      Uttar Pradesh    1710158    1687151   22900     107         UP
36        Uttarakhand     343896     330195    7400     151         UT
37        West Bengal    1592908    1565471   19141    8296         WB

In [145]:
df1=pd.DataFrame({
    'State':['TS'],
    'Confirmed':[567889],
    'Recovered':[234567],
    'Deaths':[67890],
    'Active':[789],
    'State_code':['TEL'],
})
df1=pd.concat([df,df1],axis=1)
print(df1)

                          State  Confirmed  Recovered  Deaths  Active  \
0                         Total   34285612   33661339  458470  152606
1   Andaman and Nicobar Islands       7651       7518     129       4
2                Andhra Pradesh    2066450    2047722   14373    4355
3             Arunachal Pradesh      55155      54774     280     101
4                         Assam     610645     600974    5997    2327
5                         Bihar     726098     716390    9661      46
6                    Chandigarh      65351      64495     820      36
7                  Chhattisgarh    1006052     992159   13577     316
8              Dadra and Nagar       10681      10644       4       2
9                         Delhi    1439870    1414431   25091     348
10                          Goa     178108     174392    3364     352
11                      Gujarat     826577     816283   10089     205
12                      Haryana     771252     761068   10049     135
13             Himachal Pradesh     224106     218410    3738    1942
14            Jammu and Kashmir     332249     326915    4432     902
15                    Jharkhand     348764     343518    5138     108
16                    Karnataka    2988333    2941578   38082    8644
17                       Kerala    4968657    4857181   31681   79266
18                       Ladakh      20962      20687     208      67
19                  Lakshadweep      10365      10270      51       0
20               Madhya Pradesh     792854     782215   10524     115
21                  Maharashtra    6611078    6450585  140216   16658
22                      Manipur     123731     121102    1921     708
23                    Meghalaya      83627      81746    1450     431
24                      Mizoram     121359     114612     432    6315
25                     Nagaland      31842      29904     685     210
26                       Odisha    1041457    1029147    8386    3924
27                   Puducherry     128013     125726    1857     430
28                       Punjab     602401     585591   16559     251
29                    Rajasthan     954429     945443    8954      32
30                       Sikkim      31979      31063     396     195
31             State Unassigned          0          0       0       0
32                   Tamil Nadu    2702623    2655015   36116   11492
33                    Telangana     671463     663498    3956    4009
34                      Tripura      84468      83466     813     126
35                Uttar Pradesh    1710158    1687151   22900     107
36                  Uttarakhand     343896     330195    7400     151
37                  West Bengal    1592908    1565471   19141    8296

   State_code State  Confirmed  Recovered   Deaths  Active State_code
0          TT    TS   567889.0   234567.0  67890.0   789.0        TEL
1          AN   NaN        NaN        NaN      NaN     NaN        NaN
2          AP   NaN        NaN        NaN      NaN     NaN        NaN
3          AR   NaN        NaN        NaN      NaN     NaN        NaN
4          AS   NaN        NaN        NaN      NaN     NaN        NaN
5          BR   NaN        NaN        NaN      NaN     NaN        NaN
6          CH   NaN        NaN        NaN      NaN     NaN        NaN
7          CT   NaN        NaN        NaN      NaN     NaN        NaN
8          DN   NaN        NaN        NaN      NaN     NaN        NaN
9          DL   NaN        NaN        NaN      NaN     NaN        NaN
10         GA   NaN        NaN        NaN      NaN     NaN        NaN
11         GJ   NaN        NaN        NaN      NaN     NaN        NaN
12         HR   NaN        NaN        NaN      NaN     NaN        NaN
13         HP   NaN        NaN        NaN      NaN     NaN        NaN
14         JK   NaN        NaN        NaN      NaN     NaN        NaN
15         JH   NaN        NaN        NaN      NaN     NaN        NaN
16         KA   NaN        NaN        NaN      NaN     NaN        NaN
17         KL   NaN        NaN        NaN      NaN     NaN        NaN
18         LA   NaN        NaN        NaN      NaN     NaN        NaN
19         LD   NaN        NaN        NaN      NaN     NaN        NaN
20         MP   NaN        NaN        NaN      NaN     NaN        NaN
21         MH   NaN        NaN        NaN      NaN     NaN        NaN
22         MN   NaN        NaN        NaN      NaN     NaN        NaN
23         ML   NaN        NaN        NaN      NaN     NaN        NaN
24         MZ   NaN        NaN        NaN      NaN     NaN        NaN
25         NL   NaN        NaN        NaN      NaN     NaN        NaN
26         OR   NaN        NaN        NaN      NaN     NaN        NaN
27         PY   NaN        NaN        NaN      NaN     NaN        NaN
28         PB   NaN        NaN        NaN      NaN     NaN        NaN
29         RJ   NaN        NaN        NaN      NaN     NaN        NaN
30         SK   NaN        NaN        NaN      NaN     NaN        NaN
31         UN   NaN        NaN        NaN      NaN     NaN        NaN
32         TN   NaN        NaN        NaN      NaN     NaN        NaN
33         TG   NaN        NaN        NaN      NaN     NaN        NaN
34         TR   NaN        NaN        NaN      NaN     NaN        NaN
35         UP   NaN        NaN        NaN      NaN     NaN        NaN
36         UT   NaN        NaN        NaN      NaN     NaN        NaN
37         WB   NaN        NaN        NaN      NaN     NaN        NaN

In [146]:
df1=pd.DataFrame({
    'State':['TS'],
    'Confirmed':[567889],
    'Recovered':[234567],
    'Deaths':[67890],
    'Active':[789],
    'State_code':['TEL'],
})
df1=pd.concat([df,df1],axis=1)
print(df1)

                          State  Confirmed  Recovered  Deaths  Active  \
0                         Total   34285612   33661339  458470  152606
1   Andaman and Nicobar Islands       7651       7518     129       4
2                Andhra Pradesh    2066450    2047722   14373    4355
3             Arunachal Pradesh      55155      54774     280     101
4                         Assam     610645     600974    5997    2327
5                         Bihar     726098     716390    9661      46
6                    Chandigarh      65351      64495     820      36
7                  Chhattisgarh    1006052     992159   13577     316
8              Dadra and Nagar       10681      10644       4       2
9                         Delhi    1439870    1414431   25091     348
10                          Goa     178108     174392    3364     352
11                      Gujarat     826577     816283   10089     205
12                      Haryana     771252     761068   10049     135
13             Himachal Pradesh     224106     218410    3738    1942
14            Jammu and Kashmir     332249     326915    4432     902
15                    Jharkhand     348764     343518    5138     108
16                    Karnataka    2988333    2941578   38082    8644
17                       Kerala    4968657    4857181   31681   79266
18                       Ladakh      20962      20687     208      67
19                  Lakshadweep      10365      10270      51       0
20               Madhya Pradesh     792854     782215   10524     115
21                  Maharashtra    6611078    6450585  140216   16658
22                      Manipur     123731     121102    1921     708
23                    Meghalaya      83627      81746    1450     431
24                      Mizoram     121359     114612     432    6315
25                     Nagaland      31842      29904     685     210
26                       Odisha    1041457    1029147    8386    3924
27                   Puducherry     128013     125726    1857     430
28                       Punjab     602401     585591   16559     251
29                    Rajasthan     954429     945443    8954      32
30                       Sikkim      31979      31063     396     195
31             State Unassigned          0          0       0       0
32                   Tamil Nadu    2702623    2655015   36116   11492
33                    Telangana     671463     663498    3956    4009
34                      Tripura      84468      83466     813     126
35                Uttar Pradesh    1710158    1687151   22900     107
36                  Uttarakhand     343896     330195    7400     151
37                  West Bengal    1592908    1565471   19141    8296

   State_code State  Confirmed  Recovered   Deaths  Active State_code
0          TT    TS   567889.0   234567.0  67890.0   789.0        TEL
1          AN   NaN        NaN        NaN      NaN     NaN        NaN
2          AP   NaN        NaN        NaN      NaN     NaN        NaN
3          AR   NaN        NaN        NaN      NaN     NaN        NaN
4          AS   NaN        NaN        NaN      NaN     NaN        NaN
5          BR   NaN        NaN        NaN      NaN     NaN        NaN
6          CH   NaN        NaN        NaN      NaN     NaN        NaN
7          CT   NaN        NaN        NaN      NaN     NaN        NaN
8          DN   NaN        NaN        NaN      NaN     NaN        NaN
9          DL   NaN        NaN        NaN      NaN     NaN        NaN
10         GA   NaN        NaN        NaN      NaN     NaN        NaN
11         GJ   NaN        NaN        NaN      NaN     NaN        NaN
12         HR   NaN        NaN        NaN      NaN     NaN        NaN
13         HP   NaN        NaN        NaN      NaN     NaN        NaN
14         JK   NaN        NaN        NaN      NaN     NaN        NaN
15         JH   NaN        NaN        NaN      NaN     NaN        NaN
16         KA   NaN        NaN        NaN      NaN     NaN        NaN
17         KL   NaN        NaN        NaN      NaN     NaN        NaN
18         LA   NaN        NaN        NaN      NaN     NaN        NaN
19         LD   NaN        NaN        NaN      NaN     NaN        NaN
20         MP   NaN        NaN        NaN      NaN     NaN        NaN
21         MH   NaN        NaN        NaN      NaN     NaN        NaN
22         MN   NaN        NaN        NaN      NaN     NaN        NaN
23         ML   NaN        NaN        NaN      NaN     NaN        NaN
24         MZ   NaN        NaN        NaN      NaN     NaN        NaN
25         NL   NaN        NaN        NaN      NaN     NaN        NaN
26         OR   NaN        NaN        NaN      NaN     NaN        NaN
27         PY   NaN        NaN        NaN      NaN     NaN        NaN
28         PB   NaN        NaN        NaN      NaN     NaN        NaN
29         RJ   NaN        NaN        NaN      NaN     NaN        NaN
30         SK   NaN        NaN        NaN      NaN     NaN        NaN
31         UN   NaN        NaN        NaN      NaN     NaN        NaN
32         TN   NaN        NaN        NaN      NaN     NaN        NaN
33         TG   NaN        NaN        NaN      NaN     NaN        NaN
34         TR   NaN        NaN        NaN      NaN     NaN        NaN
35         UP   NaN        NaN        NaN      NaN     NaN        NaN
36         UT   NaN        NaN        NaN      NaN     NaN        NaN
37         WB   NaN        NaN        NaN      NaN     NaN        NaN